### ISSUE TITLE
Team 11 (UI)

### ISSUE THREAD

**Issue by ArthurW4130** [UQcsse3200/2024-studio-2#10]
# **Description**

In this feature, the main user interface will be designed and implemented. Elements and functions such as the main map, mini-map, and inventories will be included. These elements provide visual aesthetics, colour schemes, and the overall appeal of the user interface. Then, the character's nickname, health bars, levels, weapons, buffs, and debuffs will be implemented and displayed. This is to provide the responsiveness of the interface to player inputs and player's in-game engagement. Additionally, since the UI holds a large range of designs and functions, frequent communication and discussion with the other teams are required.

## SubFeature/component (optional)
- Name: the character's name in game
- Health bar: how much health the player has currently
- Levels: The player's current levels
- Weapons: tools made by human
- Inventory: Collection notification
- Buffs: Periodical Add-on benefits
- Debuffs: Periodical affection dealt by enemies
- Quests - Displaying dialog when message received
- Animals - Animals and its amount collected by the player
- Dialogue box: optional interaction between player and npc.

## **Examples (optional)**
- Health Bar: a visual representation of how much energy or life force we have left as we progress through the game
- Inventory: a common UI feature where one can view all the items that have been collected thus far.

# **Dependencies**
T1, Animals #4 
T10, Combat #7 

# **Milestones**

- [x] [Completion of Hunger bar - Pratul] #42 (Aug 29)
- [x] [Completion of Experience bar - Jared]  #84 (Aug 29)
- [x] [Completion of Health bar - Christian] #36 (Aug 29)
- [x] [Completion of Player Icon - Amos]  #91 (Aug 29)
- [ ] [Completion of Player Name - Arthur] #46 (Aug 29)
- [x] [Completion of DialogBox Class - Whole Team ] #48  (Aug 22)

**Completion Deadline:** Aug. 29

# **Extras**
- [ ] Special animation for stats.
- [ ] Auto play.
- [ ] Settings Button for Other Teams Use

# **Documentation**
- TBC

# **Members**
- Christian Almario (@ChristianMario4)
- Pratul Wadhwa (@Pratulw5 )
- Jiatong Wang (@ArthurW4130)
- Aaradheya Sharma (@Dabbyyyy)
- Jared Smith (@Jared946 )

**Comment by ChristianMario4** [comment]
Most features completed.
