### ISSUE TITLE
[Team 4] Creation of in-game Dialogue Box

### ISSUE THREAD

**Issue by shubhgupta2510** [UQcsse3200/2024-studio-2#101]
# **Description**
**Task:** Implement Chat Overlay (Dialogue Box).
**Feature:** [Friendly Animals (NPC) (Team 4)]

Implement a Dialogue Box Overlay system in the game to facilitate interactions between the player and NPCs. The dialogue box will pop up when the player is close to any friendly NPC. The text of the dialogue box will vary depending on the NPC the player interacts with. This will provide entity-specific hints based on the player's quest progression. 

Quest/Storyline Progression/Hints: The text being shown by the dialogue box must be tied to the current story progression. 

# **Dependencies**
Team 5 Tasks Flag to provide the correct time to provide gameplay hints. (#64)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement the dialogue box class (Aug 23)
- [x] Integrate quest specific dialogue boxes (Aug 25)
- [x] Test all implementation of the dialogue boxes (Aug 25)
- [x] Friendly NPC Testing (Aug 27)

**Completion Deadline:**
Completion Deadline: Aug. 27
 
# **Documentation**
- [Friendly NPC Documentation](https://github.com/UQcsse3200/2024-studio-2/issues/5)
- [Dialogue Box (NPC)](https://github.com/UQcsse3200/2024-studio-2/wiki/Dialogue-Box)
 
# **Member**
- Julian Wong (@Jul-Wong)
- Hyunmin Cho (@eftg1000)
- Nahin Khan (@nreyana)
- Shubh Gupta (@shubhgupta2510)
- Bailey Stoodley (@BaileyS03)
