### ISSUE TITLE
Snake Mini-Game Image rendering 

### ISSUE THREAD

**Issue by 0NATE4** [UQcsse3200/2024-studio-2#102]
# **Description**
**Task:** Image rendering in snake minigame
**Feature:** Snake Minigame

This task will work on using the ServiceLocator class to handle rendering of images for the snake game. This will be done in the SnakeScreen class, and it will also involve creating assets to be rendered.

 
## **Example**
- **Apple**: Will feature apple pixel art
- **Snake**: Will feature snake pixel art

# **Dependencies**

- [x] Snake Movement #87 
- [x] Grid and Apple (#72 )

 
# **Milestones**

- [x] Apple Rendering (Aug. 26)
- [x] Snake Rendering (Aug. 26)
- [x] Test Rendering (Aug. 27)

 
**Completion Deadline:** Aug. 27

 
# **Documentation**
- [Rendering](https://github.com/UQcsse3200/2024-studio-2/wiki/Renderer-Components)
- [Apple Renderer](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/components/minigame/snake/rendering/AppleRenderer.html)
- [Grid Renderer](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/components/minigame/snake/rendering/GridRenderer.html)
- [Snake Renderer](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/components/minigame/snake/rendering/SnakeRenderer.html)
- [Snake Game Renderer](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/components/minigame/snake/rendering/SnakeGameRenderer.html)
 
# **Member**
@[0NATE4](https://github.com/0NATE4)
0NATE4
