### ISSUE TITLE
Place Items in Map

### ISSUE THREAD

**Issue by PHONGNGYUEN1** [UQcsse3200/2024-studio-2#105]
# **Description**
**Task:** [Place Items in Map](#3).
**Feature:** [#3 ]

Statically place rendered items into the map using sprite and make event handling to pick up items from the map and add to the inventory.
 
## **Example**
- **Picking up**: The player encounters a candy near its proximity and decides to collect it to use for later. This candy will then be stored in the inventory
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create food items and Potions items(Aug. 22)
- [x] Update map (Aug. 26)
- [x] Allow items to be picked up when in proximity of player by button press
- [x]  Display those items in the inventory
- [ ] Merge into main

**Completion Deadline:** Aug. 26
 
# **Documentation**
- [Items Wiki Page](https://github.com/UQcsse3200/2024-studio-2/wiki/Items)
- [Inventory Wiki Page](https://github.com/UQcsse3200/2024-studio-2/wiki/Inventory)

 
# **Member**
- (PHONGNGUYEN1) (Phong Nguyen)
- (lhick2108) (Lewis)
