### ISSUE TITLE
[Team 4] EntityChatService for appropriate Entity Access to Dialogue Box. 

### ISSUE THREAD

**Issue by BaileyS03** [UQcsse3200/2024-studio-2#112]
# **Description**
**Task:** [Team 4] Friendly Animals (NPC)s(#5).
**Feature:** [Team 4] EntityChatService for appropriate Entity Access to Dialogue Box. 

Implement the EntityChatService class to manage the display and lifecycle of chat overlay in the game. This service should ensure that only one instance of the chat overlay is active at any given time and should provide methods to create, update, and dispose of the chat overlay based on events triggered by game FNPCs entities.
 
# **Usage**
This service is currently available on the main game screen. Hence to utilise it with the FNPCs: 
```java
public some_function() {
      String eventPausedStart = String.format("PauseStart%s", config.getAnimalName());
      String eventPausedEnd = String.format("PauseEnd%s", config.getAnimalName());
      npc.getEvents().addListener(eventPausedStart, (String[] hintText) -> initiateDialogue(animalSoundPaths, hintText));
      npc.getEvents().addListener(eventPausedEnd, () -> endDialogue());
}
```

Where these helper functions are:
```java
  private static void initiateDialogue(String[] animalSoundPaths, String[] hintText) {
    if (animalSoundPaths != null && animalSoundPaths.length > 0) {
      for (String animalSoundPath : animalSoundPaths) {
        Sound animalSound = ServiceLocator.getResourceService().getAsset(animalSoundPath, Sound.class);
        ...
      }
    }

    EntityChatService chatOverlayService = ServiceLocator.getEntityChatService();
    chatOverlayService.updateText(hintText);
  }

  private static void endDialogue() {
    EntityChatService chatOverlayService = ServiceLocator.getEntityChatService();
    chatOverlayService.disposeCurrentOverlay();
  }
```

# **Dependencies**
- [x] Team 4 Chat Overlay Class (#191)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Integrate a template service which isn't used by anything (Aug. 25)
- [x] Utilise the ChatOverlay class in the service (Aug. 25)
- [x] Attatch the service to FNPCs using events (Aug. 25)
- [x] Test the service is functional (Aug. 25)
 
**Completion Deadline:** Aug. 25
 
# **Documentation**
- [Service Locator](../wiki/Service-Locator)
 
# **Member**
- e.g. Bailey Stoodley (@BaileyS03)
