### ISSUE TITLE
Mini-Game Scoring and Medals 

### ISSUE THREAD

**Issue by rp3002** [UQcsse3200/2024-studio-2#116]
# **Description**
**Task:** [Scoring and Medals (Snake Mini-game](#116).
**Feature:** [Mini Games](#6)

This task involves establishing a scoring system and implementing medals to reward player achievements in the mini-games. The scoring system will track player progress and performance, while medals (e.g., gold, silver and bronze) will be awarded based on scores achieved. 
 
## **Example (optional)**
Scoring System: Developing a  system to track and display player scores throughout the game.
Medal Awards: Implementing medal tiers (gold, silver and bronze) based on player scores, and displaying them at the end of each game session.

# **Dependencies**
- [x] Completion of core game functionality to ensure accurate scoring. (#116)
- [x] Integration with game interface to display scores and medals. (#116)
 
# **Milestones**

- [x] Design scoring criteria and medal tiers. (Aug 24)
- [x] Implement scoring system and medal logic. (Aug 24)
- [x] Integrate scoring funcitonality into the snake screen. (Aug 25)
- [x] Display and format score and medal definitoins onto the snake screen (Aug 25)
- [x] Integrate scoring and medals into the snake end game screen. (Aug 25)
- [x] Implement highest score and medal storage. (Aug 25)
- [x] Test scoring system and medal rewards. (Aug 26)
 
**Completion Deadline:** Aug. 26
 
# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2024-studio-2/wiki/Scoring-and-Medals)
- [JavaDoc MiniGameMedals](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/components/minigame/MiniGameMedals.html)
- [JavaDoc MiniGameScores](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/components/minigame/MiniGamesScores.html)
- [JavaDoc MiniGameConstants](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/components/minigame/MiniGameConstants.html)
 
# **Member**

Rajanya Paul Choudhury
@[rp3002](https://github.com/rp3002)
rp3002

Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas
