### ISSUE TITLE
Snake Mini-Game Termination

### ISSUE THREAD

**Issue by rp3002** [UQcsse3200/2024-studio-2#117]
# **Description**

**Task:** [Game Termination & End Screen](#117).
**Feature:** [Mini Games](#6)

This task involves designing and implementing the game termination logic and end screen for the snake game. The end screen will display the player's final results, including score, earned medals, buttons and any other relevant information. The game termination logic will handle conditions under which the game ends and transition to the end screen smoothly.

Termination Logic: Develop the logic to handle game over conditions and transition to the end screen.
Smooth Transition: Ensure a seamless transition from gameplay to the end screen with appropriate animations and feedback.

# **Dependencies**

- [x] Integration with scoring and medals system to display results on the end screen. (#116)
 
# **Milestones**
- [x] Design game termination logic. (Aug. 25)
- [x] Integrate game termination logic with the end screen. (Aug. 26)
- [x] Test game termination and end screen functionality. (Aug. 26)
 
**Completion Deadline:** Aug. 26
 
# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2024-studio-2/wiki/Snake-Mini%E2%80%90Game)
- [JavaDoc SnakeScreen](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/screens/SnakeScreen.html)
- [JavaDoc SnakeGame](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/components/minigame/snake/SnakeGame.html)
 
# **Member**

Rajanya Paul Choudhury
@[rp3002](https://github.com/rp3002)
rp3002

Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas

**Comment by EllaBerglas** [comment]
Completed in Sprint 1
