### ISSUE TITLE
Team 4/5: NPC Quest Integration 

### ISSUE THREAD

**Issue by lellis0406** [UQcsse3200/2024-studio-2#119]
# **Description**
**Task:** NPC Quest Integration (#13).
**Feature:** Team 5: Quests and Progression(#2) and [Team 4] Friendly Animals (NPC)s (#5) 

Questlines must be integrated into the NPC dialogue system. This will have quest progression trigger specific dialogue with NPCs, and NPC dialogue trigger quest flags.
 
# **Dependencies**
- [x] (#67)
- [x] (#5)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Design example questline and dialogue for NPCs (Aug 21)
- [x] Attach required dialogue and quest IDs to related NPC (Aug 29)
- [x] Add quest trigger flags to NPC dialogue (Aug 29)
- [x] Unit tests (Aug 29)
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
- See individual tickets for documentation.
 
# **Member**
- Lachlan (@lellis0406)
- Bailey (@BaileyS03)
