### ISSUE TITLE
Start Screen/Settings Menu

### ISSUE THREAD

**Issue by jt-09** [UQcsse3200/2024-studio-2#12]
# **Description**
The start screen is vital for the user's experience and is initially displayed when the user opens the game. It should contain a visual The settings feature outlines the important settings that are vital to the game such as sound, tutorial etc. Ultimately as the user starts the game and is shown a start menu which redirects them to the settings menu etc. The menu also would contain a help button which lists actions etc that can be done in the game. 

## SubFeature/component
Splash/Start screen: This component of the feature is vital to the storyline and the UI design. It refers to the initial screen that the users are greeted with when they first open the game. It will also include a button to view the tutorial again.
Settings: This component of the feature is crucial for the usability of the game. It refers to the settings menu which offers the user control over sound, movement settings etc. 
Help menu: This component of the feature is vital to the usability of the game. It refers to the help screen which contains information about different aspects of the game, including Combat, Movement, Minigames etc to name a few. 
UI design: Altered UI design for the splash screen to display name, details and theme of new game. 

## **Examples**
- **Settings menu**: Settings menu can be found in the splash screen and will contain the options to modify sound, movement, frame rate, brightness, aspect ratio etc

# **Dependencies**
Minigame Tutorial #6 

# **Milestones**
- [x] Exit confirmation & button (Aug 22nd)  #76 
- [x] Settings menu design setup (Aug 25th)  #21 
- [x] Integration and testing of new settings menu (Aug 25th)
- [x] Added minimum viable product: minigame tutorial (Collab) (Aug 28th) #74 
- [x] Help menu (Aug 28th) #20 
- [x] Testing of Help Menu and Minigame Tutorial (Aug 29th) #20 
- [x] Added new options on splash screen (Aug 29th) #17  #49 
- [x] Altered theme (UI design) for splash screen (Aug 29th) #17 #49

**Completion Deadline:** Aug. 29

# **Documentation**
[Main description of feature](https://github.com/UQcsse3200/2024-studio-2/wiki/Game-Screens)
[User documentation (Settings)](https://github.com/UQcsse3200/2024-studio-2/wiki/Settings)
[User documentation (Help)](https://github.com/UQcsse3200/2024-studio-2/wiki/Help-Menu)
[Testing documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Main-Menu-Display-Tests)

# **Members**
- @[TarushiG](https://github.com/TarushiG): Tarushi Gera
- @[Slothlesss](https://github.com/Slothlesss): Minh
- @[ishusharma13](https://github.com/ishusharma13): Ishu Sharma
- @[jt-09](https://github.com/jt-09): Jay Thakkar
- @[jtayl647](https://github.com/jtayl647): Jaimee Taylor
