### ISSUE TITLE
Team 10 - Fight Countdown

### ISSUE THREAD

**Issue by sneha-zazen** [UQcsse3200/2024-studio-2#127]
**Task:** [Fight Countdown Screen](#3).
**Feature:** [Team 10] Combat System #7

Implement the fight countdown screen in the game that appears when the player chooses to engage in combat. This screen should display a countdown from 3 to 1, followed by the text "FIGHT!!" before transitioning to the combat screen.  

## **Example (optional)**
Part: When the player chooses to fight, a new screen is displayed, counting down from 3 to 1. After the countdown, "BAM!!" is displayed before transitioning to the combat screen.
Countdown Display: The countdown is displayed in large, bold text in the center of the screen, against a dark background, with each number displayed for one second. The transition to the combat screen occurs automatically after the countdown finishes.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Combat screen implementation (#73)
- [ ] Event handling for combat initiation

 
# **Milestones**

- [x]  Design the countdown screen UI and layout (Aug. 25)
- [x]  Implement the countdown logic using Timer (Aug. 26)
- [x] Integrate the countdown screen with the existing combat system (Aug. 27)
- [ ] Test the countdown functionality in various scenarios (Moved for Next Sprint)
 
**Completion Deadline:** Aug. 28

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)

 
# **Member**
- Sneha Zazen (@sneha-zazen )
