### ISSUE TITLE
Team 5: Progression

### ISSUE THREAD

**Issue by lellis0406** [UQcsse3200/2024-studio-2#13]
# **Description**
We are implementing the Quest handler system. This includes a struct that contains the state of the game world, an event listener/broadcaster system, and a basic UI. The state of the game world will ensure that all data is consistently tracked and updated. Additionally, the event listener/broadcaster system will allow for seamless communication between multiple game components. Lastly, the basic UI will allow access to the task menu, manage pop-ups and provide feedback on quest progress and objectives. Overall, this system will add depth to the gameplay.

## SubFeature/component
Event handler: Our event handler will be an expansion of the existing event handler system, to be adapted to a more global scale.  (#47)
Quest Handler: The quest handler system will store the state of the game progression and process events based on input from the event handler. (#64 ) (#67) (#69) (#65) (#68 )
Game State Struct: This will contain information on the persistent state of the world. This will be referenced by the map team to handle changes to the map/enemy spawns. This will also be saved and loaded at game start/end and event completion using a JSON. (#15 )
Rewards: Experience UI and points and achievements.

## **Dependencies**
- [x] (#5)

## **Examples**
Tracking story completion (for example, triggering the spawn of the final boss based on game events)
Tracking story information (attributes, tasks, hints)

# **Milestones**
- [x] Saving: Implement Saving and Loading with Gamestate (18th Aug.)
- [x] Events: Implement Event Service (18th Aug.)
- [x] Story: Sprint 1 Quest Design (22 Aug.)
- [x] Achievements: Achievements Screen in Main menu (22 Aug.)
- [x] QuestTracker: Quest details screen (per quest) (25 Aug.)
- [x] Tasks: (Integration) Integrations with other teams/functions (25 Aug.)
- [x] QuestManager: (Integration) Quest dependant actions  (25 Aug.)
- [x] Quests: (Integration) Completion of Final Boss Quest (25th Aug.)
- [x] All: Functionality Completed (25th Aug.)
- [x] All: All Documentation Completed (26th Aug.)
- [x] All: All Unit Tests Completed (27th Aug.)
- [x] All: Reference Assets (29th Aug.)

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- Additional integration with other game features

# **Documentation**
- [Main description of feature](../wiki/Event-System)
TBA

# **Members**
- Noah Stevens (@theboah)
- Lachlan (@lellis0406)
- Jaden (@jaden-z-fng)
- Maree (@MargoCode)
- Reemzheem Hossain (@reemmi)
