### ISSUE TITLE
Create Snake Score Board

### ISSUE THREAD

**Issue by 0NATE4** [UQcsse3200/2024-studio-2#133]
# **Description**
**Task:** Create Snake Score Board
**Feature:** (#6 Minigames)

This feature will allow the scoring system of the game to be displayed visually in the snake minigame screen. It will involve dynamic resizing to account for different screen dimensions, and will feature the player's current score, and possible medals they can achieve by getting a higher score.

 
## **Example (optional)**

- **Score Increase**: As the player eats food, the score will increment
- **Different screen dimension**: If the user has a different screen dimension, the score board will remain consistent in relative size
# **Dependencies**

- [ ] Dependency 1 (#116 ) Scoring and medals
- [ ] Dependency 2 (#40 ) Snake Screen
- [ ] Dependency 3 (#72) Snake grid and apples

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Implement score board visual aspects (Aug. 26)
- [ ] Integrate score board with game scores (Aug. 26)
- [ ] Test scoreboard (Aug 27)

 
**Completion Deadline:** Aug. 27

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**

0NATE4
