### ISSUE TITLE
Snake Mini-Game End Screen

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#137]
# **Description**
**Task:** Snake Mini-Game End Screen #137
**Feature:** Mini Games #6

Create an end game screen. Display the score and medal. Change the background colour to represent the medal. Also integrate en exit button, try again button and mini-games menu button. Ensure integration with button style and fonts as well as placement of ui is consistent.

End Screen Design: Create an end screen that displays the player’s final score, medals earned, and other relevant statistics. 
Buttons for exit, try again and minigames menu: Ensure buttons follow game skin and work accordingly.

## **Example (optional)**
- **Part**: Depending on the task, you may want to provide some examples of how it would play out in the game. See next point for example...
- **Armour Benefits**: Players can wear different classes of armour. Armour takes damage until it breaks. Armour cannot be healed but can be replaced. If a player is wearing armour, its health is not affected when it takes damage unless the armour is broken.

# **Dependencies**

- [x] Snake Mini-Game Termination #117
 
# **Milestones**
- [x] Implement end screen layout and content. (Aug 24)
- [x] Implement buttons (Aug 26)
- [x] Visually test (as implemented)
- [x] Implement escape key and R key to exit and restart the game (respectively) (Aug 26)
- [x] Integrate existing font conistent with the game (Aug 26)

 
**Completion Deadline:** Aug. 26
 
# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2024-studio-2/wiki/Snake-Mini%E2%80%90Game)
- [JavaDoc EndSnakeScreen](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/screens/EndSnakeScreen.html)
 
# **Member**
Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas

Rajanya Paul Choudhury
@[rp3002](https://github.com/rp3002)
rp3002

**Comment by EllaBerglas** [comment]
Completed in Sprint 1
