### ISSUE TITLE
Intergration: Screen switching and pausing

### ISSUE THREAD

**Issue by theboah** [UQcsse3200/2024-studio-2#139]
# **Description**
Game screens should be able to be "hotswapped" for other screens maintaing assets, entities and all relevant service and component data. Game screens should be able to be paused using overlays.  Feature is used by team 10 for combat and team 5 for QuestOverlay in game menu.

Sub Freatures
Screen switching with Service containers
Overlays

## **Examples (optional)**
- **MainGameDup**:  A duplicate of the main game was used as testing and appeared on top of the original. This was removed prior to pulling into main.
- **Pause Overlay**: This overlay paused the main game screen and gave access to other menus and the main menu and allowed the user to resume gameplay.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Initial idea
- [x] Service container implementation and screen switching
- [x] Basic pause implementation
- [x] Overlay implementation
- [x] Quest Overlay intergration
- [x] Testing
- [x] Bugfixing input and motion issues
- [x] Intergration into combat and implementing combat starting from collision
- [x] Relevant unit tests
- [x] Pull request into main

# **Documentation**
- [Preserving Screens](https://github.com/UQcsse3200/2024-studio-2/wiki/Preserving-Screens)
- [Event Service](https://github.com/UQcsse3200/2024-studio-2/wiki/Eventservice)
- [Overlays](https://github.com/UQcsse3200/2024-studio-2/wiki/Overlays)

# **Members**
- Noah Stevens (@theboah) (@noahxl234) (theboah)
- Lucas Ryall (@LucasRyall) (mr._derp)
