### ISSUE TITLE
Task Ticket: Add Lion NPC

### ISSUE THREAD

**Issue by Jul-Wong** [UQcsse3200/2024-studio-2#14]
# **Description**
**Task:** Add a Lion NPC.
**Feature:** Friendly Animals (NPC) (Team 4) 
Adds an interactable NPC that resembles a lion. Each NPC will have specific stats (possibly including but not limited to HP, Speed, Attack etc.) and possibly slightly different roaming AI. NPC should also allow interaction with the player with a dialogue box and accommodate quest giving to the player. They may also offer helpful gameplay hints.
 
## **Example (optional)**
- **Part**: A lion NPC sprite will wander the map, being drawn to the player if in close proximity. 
- **Quest/Storyline Progression/Hints**: The player will then have an option to interact with the lion and trigger dialogue and/or quests. This may either give hints or progress the storyline with a quest. 

# **Dependencies**

- [x] #58 
- [x] Dialogue Box https://github.com/UQcsse3200/2024-studio-2/issues/101
- [x] Questline Flag/Trigger Handling from Team 5

 
# **Milestones**

- [x] Create base NPC behavior for Lion and document on wiki (August 15)
- [x] Create lion sounds for when lion pauses (August 20)
- [x] Implement tests for Lion (August 21)
- [x] Accommodate Dialogue/Quest Progression (August 21)
- [x] Lion NPC implemented and tested (August 25)
- [x] Update documentation on wiki (August 25)
 
**Completion Deadline:** Aug. 30(TBD)

 
# **Documentation**
- [Friendly NPC Documentation](../wiki/Friendly-NPC's)
- [Lion (NPC) Documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Lion)
- [Dialogue Box (NPC)](https://github.com/UQcsse3200/2024-studio-2/wiki/Dialogue-Box)
# **Member**
- Julian Wong (@Jul-Wong)
