### ISSUE TITLE
Team 5: Saving

### ISSUE THREAD

**Issue by lellis0406** [UQcsse3200/2024-studio-2#15]
# **Description**
**Task:** Implement Saves.
**Feature:** Team 5: Quests and Progression(#13)

A saving/loading system will be implemented into the game. This will be a module that implements behaviour for multiple data structures to be both saved at certain points in the game, as well as loaded at runtime.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create class structure for generic implementation
- [x] Implement writing to JSON for saves
- [x] Implement wiki for saving and distribute to relevant teams
 
**Completion Deadline:** Aug. 30
 
# **Documentation**
- [Save Handler Documentation](../wiki/Game-State-Saves)
 
# **Member**
- Lachlan (@lellis0406)
