### ISSUE TITLE
[Team 4] Friendly NPCs Extension

### ISSUE THREAD

**Issue by Jul-Wong** [UQcsse3200/2024-studio-2#152]
# **Description**
This sprint will aim to fix some issues caused with some integrations with other teams from Sprint One. These include dialogue/quests handling, distinguish between friendly and enemy AI etc. In addition for Sprint Two, additional NPCs will be implemented for the next kingdoms. Some NPCs may be moved to match their specific kingdoms. The Chatbox UI will be fleshed out and will work in relation to Quests and Progression.

## Components
- Establish functionality to easily distinguish between Enemy and Friendly NPCs (Outline the Enemy and Friendly NPCs in different colours or show Friendly NPC animal's names)
- Implement new NPCs specific to each kingdom.
- More sophisticated hint/interaction system
- Implement a new system to display ChatBox UI (hiding box after creation instead of dispose to remove lag when interacting with Friendly NPCs)

## **Examples**
- **Chat Overlay**: Fix lag with UI overlay (Hide chat box instead of using `dispose()`
- **Implement new NPCs**: Move some of sprint one's npcs to each of the kingdoms (ground, water, sky).
- **Improved NPC Interaction**: Allow player to choose which NPC and when to interact with instead of closest proximity

# **Dependencies**
- Collaboration with Team 7 to combine snake npc and snake minigame.
- Team 5 for Quests and Progression

# **Milestones**
- [x] #161
- [x] #162
- [x] Add options for the users to choose during the dialogue with the NPCs (Sep. 9)
- [x] Add additional FNPCs (Sep. 9) (#253)
- [x] Add additional FNPCs (Sep. 9) (#205)

**Completion Deadline:** Sep. 9

# **Documentation**
[Dialogue Box Service](https://github.com/UQcsse3200/2024-studio-2/wiki/Service-Locator)
[Fish & Fish Testing Documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Fish)

# **Members**
- Julian Wong (@Jul-Wong)
- Shubh Gupta (@shubhgupta2510)
- Hyunmin Cho (@eftg1000)
- Bailey Stoodley (@BaileyS03)
- Nahin Khan (@nreyana)
