### ISSUE TITLE
[Team 5] Achievement Popup

### ISSUE THREAD

**Issue by jaden-z-fng** [UQcsse3200/2024-studio-2#153]
# **Description**
**Task:** [Detailed Achievements](#153).
**Feature:** [Quests & Progression](#154)

Implement an popup on the main game screen whenever someone completes a new achievement.

# **Dependencies**
- [ ] Bug free achievement class

# **Milestones**

e.g.

- [x] Create imagery and sounds for the popup (Sep. 7).
- [x] Implement and integrate the popup (Sep.7).
- [x] Documentation updated on wiki (Sep. 11).
 
**Completion Deadline:** Sep. 11

# **Documentation**
- [Wiki page] (https://github.com/UQcsse3200/2024-studio-2/wiki/Quests)

 
# **Member**
- Jaden (jaden-z-fng)
