### ISSUE TITLE
[Team 3] Item/Inventory Sprint 2 features

### ISSUE THREAD

**Issue by PHONGNGYUEN1** [UQcsse3200/2024-studio-2#157]
# **Description**
This feature introduces a system for the players to apply the items to their stats to improve their performance levels. The inventory will  be able to manage the items stored (use or remove) and more items will be introduced into the map. 

## SubFeature/component
- #163
- #164
- #121
- #215 
- #216 
- #177 

## **Examples (optional)**
- Consumable Items will be able to affect the player's stats either permanently or temporarily 
- Hotbar display will allow players to select one of the 5 items available in their inventory from a sidebar instead of accessing the inventory through the inventory display.

# **Dependencies**
- 7 has partial dependency on 4.
- Loot chests prizes depends on #6 to complete snake game

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] 1. Add further items to the game (08/09)
- [x] 2. Allow items to be usable by Player (and on entities in future) (in collaboration with Team 1) (#163) (08/09)
- [x] 3. Randomly generate items on map with chunk generation (TBD) - (in collaboration with Team 8) (06/09)
- [x] 4. #177 (09/06)
- [x] 5. BUG: Fix large lag in pop up dialogue for when hovering over item in inventory - (in collaboration with Team 4)  and/or remove dependency on dialogue box. (07/09)
- [x] 6. Improve UI of inventory to fit in with overall game asthetic. 
- [x] 7. Adding popup when mouse hovering over item in inventory (06/09)
- [x] 8. Add event trigger on use or pick up item for Quest progression (08/09) - (in collaboration with Team 5)
- [x] 9. Add items as minigame loot (10/09) - (in collaboration with Team 7)
- [ ] 10. #215 (Will be completed in sprint 3)
- [x] 11. Adding loot boxes for certain achievements in mini-games - (In collaboration with team 7) (10/09)
- [x] 12. Saving Inventory (11/09) - (in collaboration with Team 5)
- [x] 13. Abstract away the proximity task so it can be reused by other teams. (06/09)

**Completion Deadline:** Sep. 12

# **Extras (optional)**
- [ ] Create stealth improvement items

# **Documentation**
- [UML](https://github.com/UQcsse3200/2024-studio-2/wiki/Inventory-and-Items-UML)
- [Saving - Integrated Inventory into Team 5's Saving](https://github.com/UQcsse3200/2024-studio-2/wiki/Game-State-Saves)
- [Inventory](https://github.com/UQcsse3200/2024-studio-2/wiki/Inventory)
- [Items](https://github.com/UQcsse3200/2024-studio-2/wiki/Items)
- [Test Plan](https://github.com/UQcsse3200/2024-studio-2/wiki/Item-and-Inventory-Test-Plan)

# **Members**
- Phong Nguyen (@PHONGNGYUEN1 ) `beannie`
- Lewis (@lhick2108 ) `prehistoricmesopotamiantablet`
- Mittun (@mitsudz) `mitsudz`
- Pratul (@Pratulw5) `cactusjuice`
- Thomas (@tompreston1) `tom152738379`
