### ISSUE TITLE
Implement Animal Selection Screen

### ISSUE THREAD

**Issue by shaivikaaaa** [UQcsse3200/2024-studio-2#16]
# **Description**
**Task:** Implement Animal Selection Screen
**Feature:** #4 
This task involves implementing an animal selection screen that appears when the player clicks on the "Start" button. The screen layout will include icons representing different animals. However, the focus of this task (Task 1) is on designing and implementing the screen layout itself, with placeholders for the animal icons. The selection process will be implemented in Task 2. This screen will serve as the entry point for players to begin their journey by selecting their desired anima.. The task will focus on the visual design and the basic functionality of showing the animal icons on the screen.

## **Example* 
-Screen Layout: Upon clicking "Start," the player sees a grid layout with animal icons in placeholder positions. The icons may be static for now, and the focus is on the screen's design and transition from the "Start" button to this screen.

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design and document the layout of the animal selection screen (Aug. 15)
- [x] Implement the basic screen layout with placeholder icons (Aug. 17)
- [x] Ensure smooth transition from "Start" button to the selection screen (Aug. 19)
- [x] Complete wiki documentation (Aug. 20)

**Completion Deadline:** Aug. 23
 
# **Documentation**
- #4 
- [Animal Selection Display Wiki](https://github.com/UQcsse3200/2024-studio-2/wiki/Animal-Selection-Display)
- [Animal Selection Screen Wiki](https://github.com/UQcsse3200/2024-studio-2/wiki/Animal-Selection-Screen)
- [Animal Selection Actions Wiki](https://github.com/UQcsse3200/2024-studio-2/wiki/AnimalSelectionActions)
# **Member**
- Shaivika Anand ( @shaivikaaaa ) Discord : shaivika21

**Comment by shaivikaaaa** [comment]
Unit testing to be done by @davidaraba
