### ISSUE TITLE
Fix Lag Caused from Interaction of Friendly NPC and Player

### ISSUE THREAD

**Issue by Jul-Wong** [UQcsse3200/2024-studio-2#161]
# **Description**
**Task:** [Fix Chat Overlay Lag](161).
**Feature:** #152

From its implementation in sprint one, the chat box overlay does not function as well as intended. This was due to the lag caused when a player is in close proximity to a friendly NPC. This was cause the game to create a new chat overlay each time to be used and then disposed of afterwards. This ticket will solve this problem. Additionally items had the same issues hence their implementation will also be refactored to make the service.
 
## **Example (optional)**
- [x] Fix lag caused by unnecessary creation and deletion of chat overlay each time.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Remove use of dispose() (Sep. 9)
- [x] Implement a method to hide chat overlay to be called on and used on a later interaction with the NPC (Sep. 9)
 
# **Documentation**
- TBD.
 
# **Member**
- Bailey Stoodley @BaileyS03
