### ISSUE TITLE
Random Spawning of Items - Integrated into Chunk Generation

### ISSUE THREAD

**Issue by PHONGNGYUEN1** [UQcsse3200/2024-studio-2#164]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Team 3 Sprint 2 Features](#157 )

Item spawning needs to be integrated into chunk generation to only spawn items based on a) time and b) player location (ie items should only be spawned on chunks nearby the player, and disposed of if far from the player to avoid unnecessary lag).

# **Dependencies**
 
# **Milestones**
List of steps that need to be completed for this task. At the end of each step, tests must be written
- [ ] Set up system for spawning items randomly within a chunk (Sep 3)
- [ ] Enable chunks around player to spawn items dynamically (Sep 3)
- [ ] Dispose of items far from the player (ie, more than a certain number of chunks away) (Sep 4)
- [ ] Enable timed spawning of items randomly based on some probability distribution. (Sep 4)
- [ ] Check all tests (should be written with each step) (Sep 5)
- [ ] Tweak configuration files for probability distributions per tile for spawn rates. (Sep 5)
- [ ] Merge into team 3 branch (Sep 5)
- [ ] Create release version to be merged into main (Sep 5)
- [ ] Merge into main (Sep 6)
 
**Completion Deadline:** Sep. 7

 
# **Documentation**
- TBC

 
# **Member**
- Mittun (@mitsudz) `mitsudz`
- Howie (@Howard-12)
- Praneet (@praneetdhoolia)
- TEAM 8 MEMBER TBC
