### ISSUE TITLE
Implement Camera for Bird Game

### ISSUE THREAD

**Issue by 0NATE4** [UQcsse3200/2024-studio-2#167]
# **Description**
**Task:** [Implement Camera for Bird Game](#3).
**Feature:** [Minigames](#6)

This task will involve implementing the camera for the bird game. This will allow a partial portion of the screen to be used for the game, allowing rendering and resizing to be done easily. For example, the camera could be set with width 200x200 pixels, and positioned at coordinates (200, 0). This could represent the game area, which would then be constant throughout all types of screens.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Bird Screen (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement the camera (September 2)
- [x] Test the camera (September. 3)
- [ ] Integrate with bird screen (Sep 4)
- [ ] Test camera in screen (Sep 4)

 
**Completion Deadline:** Sep. 4

 
# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2024-studio-2/wiki/MinigameRenderer)
- ...
 
# **Member**
0NATE4
