### ISSUE TITLE
[Team 10] Combat Logic Framework

### ISSUE THREAD

**Issue by owenrharding** [UQcsse3200/2024-studio-2#171]
# **Description**
**Task:** [Combat Logic Framework](#171)
**Feature:** [Implementation of Basic Turn-Based Combat](#166)

After being passed a `player` and `enemy` (as instances of the `Entity` class), a simulated combat environment (CombatManager) will be set up using their unique instances of `CombatStatsComponents`. The environment will continuously receive the player's moves and generate the enemy's moves, handling the outcomes of their unique move combinations, priority matchups, and status effects. At the end of the combat sequence, once one of either the player or enemy's health has been reduced to zero, the game will return to the main game screen, handling any post-combat statuses when doing so.

The combat logic itself will be self-contained in a simulated environment (both the player and enemy's stats won't be affected during combat). This allows for status effects to later be implemented without affecting the entities outside of the scope of combat.
 
## **Example**
- **Self-contained combat**: an enemy may perform a move that reduces the player's strength attribute by half. The player proceeds to defeat the enemy. If this status-effect move was handled in the player's actual CombatStatsComponent, their strength would remain half of what it should be post battle. In a simulated environment, any status effects which should remain post-combat (such as health reduction) can be applied upon exit based on the results of the combat sequence.

# **Dependencies**
- #174 
- #188 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create combat manager class (Sep 2)
- [x] Add combat manager to combat screen with proper intialisation (Sep 3)
- [x] Integrate manager with combat actions (Sep 6)
- [x] Integrate manager with combat buttons (Sep 6)
- [x] Document combat logic on wiki (Sep 7) _Done by Alex from Team 1 - see Documentation - Combat System_
- [x] Create abstract combat move class (Sep 7)
- [x] Create class templates for Attack, Guard, Sleep, Special (Sep 8)
- [x] Implement logic for Attack move (Sep 8)
- [x] Implement logic for Guard move (Sep 9)
- [x] Implement logic for Sleep move (Sep 9)
- [x] Implement logic for Special move (Sep 10)
- [x] Implement sequencing logic in manager class (Sep 11)
 
**Completion Deadline:** Sep. 12
 
# **Documentation**
- [Combat System](../wiki/Combat-System)
- [Combat Moves](../wiki/Combat-Moves)
 
# **Member**
- Peeranat Leelawattanapanit (@paulpleela on GitHub) (pa._.l on Discord)
- Owen Harding (@owenrharding on GitHub) (owen8232 on Discord)
- Phurin Vanasrivilai (@phurinjeffy on GitHub) (jeff. on Discord)
