### ISSUE TITLE
[Team10] Triggering Combat Screen to Spawn with Statistics Bar

### ISSUE THREAD

**Issue by ChristianMario4** [UQcsse3200/2024-studio-2#172]
# **Description**
**Task:** Triggering Combat Screen to Spawn with Statistics Bars.
**Feature:** Implementation of Basic Turn Based Combat (#166 )

Upon encountering an EnemyNPC entity on the map, the game's screen will be swapped to a different CombatScreen. On this screen, the user will no longer be able to move the main player. Instead, they will have the ability to click multiple buttons to complete specific actions. This combat screen will reuse multiple pre-existing components that have already been implemented as such as the statistics bars (experience and health), the player character, and the enemy characters. (More code specific details will be added once I've determined how I'm going to implement this after reading the Wiki). 
 
## **Example**
- Players can encounter different enemy NPCs on the map whilst playing the game. Once reaching an appropriate distance from the EnemyNPC and triggering an event listener, the screen will be changed from the main game screen to the battle screen. In this main battle screen, the current animal friend's health and experience stats will be displayed, as well as multiple buttons that the player can click on to complete different actions (item use, different combat actions, escaping battle, switching friends, comparing stats). 

# **Dependencies**
- [x] Combat Buttons on Screen to Control Combat Moves (#174)
- [x] Combat Logic Implementation (#171) 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Understand the Functionalities Currently Implemented by New Team and Other Teams Related to Combat Screen (Sep. 3)
- [x] Design and Create Relevant Pixel Arts (Sep. 5)
- [x] Display Health and Experience Bars in the Combat Screen (Sep. 5)
- [x] Display Buttons in the Combat Screen (Sep 7.)
- [x] Complete Testing/Debugging and Documentation (Sep. 9)
 
**Completion Deadline:** Sep 9.

 
# **Documentation**
- [Displaying Stats Bars in CombatStatsDisplay](https://github.com/UQcsse3200/2024-studio-2/wiki/CombatStatsDisplay)
 
# **Member**
- Christian Almario (@ChristianMario4 on Github), (CAllMario101 on Discord)
