### ISSUE TITLE
Spawn Player and Enemy Entities on Combat Screen

### ISSUE THREAD

**Issue by yessica-s** [UQcsse3200/2024-studio-2#173]
# **Description**
**Task:** Spawn Player and Enemy Entities on Combat Screen
**Feature:** Implementation of Basic Turned Based Combat (#166)

Implement the spawning of player and enemy entities onto the Combat Screen. Position the entities as required and make them static for future development of combat visuals. This will involve passing the player and combat enemies onto the combat screen and accessing existing functions and creating new ones to spawn them into the new Combat Screen (and potentially new Combat Area)

# **Dependencies**

- [x] Creation of new Combat Screen (completed in Sprint 1)

# **Milestones**

- [x] Access and, if required, modify, spawn functions for the player and enemy (Sept. 2)
- [x] Use the functions to spawn entities onto the combat screen (or area if later required) (Sept. 4)
- [x] Position the entities to be static (i.e. potentially turning off key handling during combat) (Sept. 6)
- [x] Integrate and merge with the new game screen design implemented by another team member (Sept. 9)
 
**Completion Deadline:** Sept. 13

# **Documentation**
- [Combat Screen Design](https://github.com/UQcsse3200/2024-studio-2/wiki/Combat-Screen)
- [Combat Area](https://github.com/UQcsse3200/2024-studio-2/wiki/CombatArea)
 
# **Member**
- Yessica (@yessica-s)
- Jonah (@Jaycoba1)
