### ISSUE TITLE
Implement Action Buttons in Combat

### ISSUE THREAD

**Issue by sneha-zazen** [UQcsse3200/2024-studio-2#174]
# **Description**
**Task:** [Implement Action Buttons in Combat](#174).
**Feature:** [Implementation of Basic Turned Based Combat](#166 )

Implementing four action buttons for the combat screen: Attack, Guard, Sleep, and Items. Each button will trigger its respective event, such as attacking an enemy, guarding to reduce damage, sleeping to regain health, or using items from the player's inventory. These buttons will be displayed on the bottom of the screen with appropriate event listeners, and actions will be executed based on player interaction. Additionally, there will be logic to handle button availability depending on player status and conditions during combat.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Design buttons and their properties (Sep. 1).
- [x] Implement action trigger listener (Sep. 3).
- [x] Test button functionalities (Sep. 5).

**Completion Deadline:** Sep. 5

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)

 
# **Member**
- Sneha Zazen (@sneha-zazen on GitHub) (@zaza7_13 on Discord)
