### ISSUE TITLE
Animal Stats Update and Display 

### ISSUE THREAD

**Issue by AndreBissell** [UQcsse3200/2024-studio-2#175]
# **Description**
**Feature:** [Animal ( Player ) Feature #165 ]

Implement a levelling up mechanic, where player stats are increased when they level up (experience is full). The task aims to make statistics affect the game. The rate at which hunger decreases will be changed and health and experience will only decrease/increase when appropriate. The player stat values will also be displayed in the animal selection screen. 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Adjust rate at which Hunger, health and experience change (Sep. 6)
- [x] Implement levelling up mechanics (Sep. 7)
- [x] Implement way to view player stats (Sep 9)
 
**Completion Deadline:** Sep. 11
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)

 
# **Members**
- Kavya Sikka (@falgonn)
- Andre Bissell (@AndreBissell ) (Andre)
