### ISSUE TITLE
Procedural Map Generation with Convolutional Layers and Chunk-Based Spawning

### ISSUE THREAD

**Issue by JonnaHerman** [UQcsse3200/2024-studio-2#176]
# **Description**
This feature focuses on generating a procedural map using the wave function collapse algorithm, with the potential for incorporating convolutional layers for enhanced map tile generation. Additionally, it includes developing spawning methods for entities based on map chunks, which might be reassigned to another team. The feature also explores an advanced approach for more refined biome creation by using weighted sums of tiles and chunk types.

## SubFeature/component

- [x] Wave Function Map Generation (#81 )
Refine the wave function collapse algorithm to procedurally generate the base map. The algorithm should follow adjacency rules and constraints to ensure coherent tile placement. 

- [x] Chunk-Based Spawning Methods (#231)
Develop methods for spawning entities based on the chunk structure of the map. This component may be transferred to another team, so code should be modular and well-documented.

- [x] Convolutional Layers in Tile Generation (#229)
  Integrate a convolutional layers to enhance map tile generation, offering a more sophisticated alternative to the wave function approach. The mechanism involves considering adjacent tiles and using a weighted sum to determine the most suitable tile for each position.

- [x] Further development of tiles for new kingdoms (#233) 
Furthering the catalogue of tiles both to address new kingdoms (new regions, new map), and potentially fix some bugs that may be derived from a lack of tile pieces that can connect in certain positions. 

- [x] Implementation of a minimap feature (#294 )
This task involves creation of a minimap on the player's HUD. For Sprint 2, only the outer frame along with other UI components is setup and the full creation of the minimap mechanic is reserved for later sprints. A minimap will set up in the top right corner of the screen which will change based on what kingdom the player is in at the moment.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Goal 1 (Sep. 6): Complete the implementation of the wave function map generation.
- [x] Goal 2 (Sep. 8): Finish the chunk-based spawning methods and test them.
- [x] Goal 3 (Sep.10): Integrate and test the layers for map tile generation.
- [x] Goal 4 (Sep.12):  Final testing and bug fixing for the entire system.

**Completion Deadline:** Sep. 12

# **Extras**
- [x] Introduction of new kingdoms, the ocean and sky kingdom. 
- [x] Dynamic map updates, implementing a feature where the map updates in real time based off player actions. 

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
- @chloemicah 
- @praneetdhoolia 
- @JonnaHerman 
- @Howard-12 
- @BenGhahramaniUQ 
- @Dabbyyyy
