### ISSUE TITLE
Create inventory hotbar

### ISSUE THREAD

**Issue by Pratulw5** [UQcsse3200/2024-studio-2#177]
# **Description**

TODO: UPDATE TICKET - COLLABORATION WITH MAP TEAM (8)

**Task:** [Task Name](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

This task is for implementing spawning items on the map randomly. Some items may spawn less than others depending on their rarity 

# **Dependencies**
#121 hovering over hotbar should display item description.
rearranging items by mouse click and drag.
 
# **Milestones**
List of steps that need to be completed for this task.

- [x] display on screen when not toggled [3/Sept]
- [x] Functional Testing [3/Sept]
- [ ] Merging into team 3 main branch [4/Sept]

 
**Completion Deadline:** 5/Sept

 
# **Documentation**
- TODO  
- [JavaDoc](JavaDoc/Location/Package/Class)
- Wiki

 
# **Member**
- Pratul Wadhwa (@Pratulw5 ) `cactusjuice`
