### ISSUE TITLE
[Team 2] Transition to combat scene for enemy NPCs

### ISSUE THREAD

**Issue by nownver** [UQcsse3200/2024-studio-2#178]
# **Description**
**Task:** [Transition to combat scene for enemy NPCs](#178)
**Feature:** [Enemy NPCs Interaction Feature](#156 )

Implement a new transition screen that will appear before entering a combat scene involving enemy NPCs. This feature aims to provide an enemy detail, and differentiate between normal gameplay and combat.

# **Dependencies**

- [Combat scene] (#73 )

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial concept sketches for the screen (Sep. 2)
- [x] Approval of concept designs by the design committee (Sep. 3)
- [x] Implement the transition screen's animation and create the necessary texture assets.(Sep. 7)
- [x] Integration of animation and texture into the game (Sep. 8)
- [ ] Testing and adjustments (Sep. 9)

**Completion Deadline:** Sep. 10
 
# **Documentation**
* [Transition to Combat Screen for Enemy NPCs](https://github.com/UQcsse3200/2024-studio-2/wiki/Transition-to-Combat-Screen-for-Enemy-NPCs)
 
# **Member**
- Jade (@nownver) (Urawee Thani)
