### ISSUE TITLE
[Team 2] Implement Enemy Animation Before Combat

### ISSUE THREAD

**Issue by jl1324** [UQcsse3200/2024-studio-2#179]
# **Description**
Task: [Implement Sprite Animation Before Combat](https://github.com/UQcsse3200/2024-studio-2/issues/179 )
**Feature:** [Enemy NPC Improvement and Cleanup](https://github.com/UQcsse3200/2024-studio-2/issues/647) 

This task involves implementing a sprite animation sequence that plays immediately before combat is triggered, serving as a visual indicator to the player that combat cut scene is about to start. The animation sequence will be designed to provide a clear and engaging cue, preparing the player for the transition into combat mode. The sprite animation will be triggered when the player reaches a certain radius distance from the user (functionality from ```proximityComponent ``` class).

# **Dependencies**
- [x] ChaseTask (#83 )
- [x] Combat Initiation Functionality  (#79 )

# **Milestones**
List of steps that need to be completed for this task.
- [x] Design the animation frames and implement movement and animation definitions (Sept. 1)
- [x] Trigger the animation by modifying proximityComponent and implementing it to trigger combat animation when player is within certain radius (Sept. 12)
- [x] Ensure specific pull interaction works (Oct 16) 
- [x] Ensure combat is triggered after animation is played (Oct 16)
- [x] Testing animation to ensure it behaves correctly. (Oct. 17)
 
**Completion Deadline:** Oct. 17

# **Documentation**
 - [Enemy NPC Pull Interaction](https://github.com/UQcsse3200/2024-studio-2/wiki/Enemy-NPC-Pull-Interaciton)
 
# **Member**
- (@jl1324) (Lily Ji)
