### ISSUE TITLE
Create Item Abstract Class

### ISSUE THREAD

**Issue by PHONGNGYUEN1** [UQcsse3200/2024-studio-2#18]
# **Description**
**Task:** [Create Item Abstract Class](#3).
**Feature:** [#3 Items/Inventory]
 
Initialise the abstract class for items. This class will have functions and fields which can be inherited by other subclasses such as all item subclasses.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add Abstract Class (Aug. 11)
- [x] Add Tests for Abstract Class (Aug. 12)
- [x] Add Documentation to wiki (Aug. 14)
- [ ] Merge into main (27 Aug)

**Completion Deadline:** Aug. 14

# **Documentation**
- [Abstract Item Documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Abstract-Item)
 
# **Member**
- Name (GitHub username) `Discord Username`
- Mittun (@mitsudz) `mitsudz`

**Comment by mitsudz** [comment]
Abstract Item Class added - merged into branch 3-inventory-and-items (Team 3 main branch)
