### ISSUE TITLE
Minigames End Game Screen Generalisation

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#180]
# **Description**
**Task:** [Minigames End Game Screen Generalisation](#180)
**Feature:** [Team 7 Mini-Games](#6)

Generalise the end game screen used in the snake game for all mini-games. This wil require updatign the existing end game screen for snake and implementing funcitonality for Birdy Dash and Underwater Maze.

# **Dependencies**
- [ ] The current End game screen for the snake game (#137)
- [ ] Snake game termination (#117)
- [ ] Birdy Dash game termination
- [ ] Underwater maze game termination
- [ ] Scoring and medal system (#116)
 
# **Milestones**
- [ ] Refactor input parameters sept 4th
- [ ] Implement and test for snake sept 4th
- [ ] Implement and test for Birdy Dash sept 10
- [ ] Documentation of end game screen sept 10
- [ ] Integration with all mini-games by end of sprint 3
 
**Completion Deadline:** Sept. 10

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas
