### ISSUE TITLE
Integration of Snake Mini-Game with Snake NPC

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#181]
# **Description**
**Task:** [Integration of Snake Mini-Game with Snake NPC](#181).
**Feature:** [[Team 7] Mini-Games](#6)

Integrate the snake mini-game into the main game. This will be from interaction with a snake npc.
 
## **Example**
- The player will approach the snake character and the able to read the story line from the dialogue box. They will then have the option to play and boot up the snake mini-game.

# **Dependencies**
- [ ] Creation of snake character (#60)
- [ ]  Dialogue box for npc characters (#101)
 
# **Milestones**
- [ ] Implementation by Sept. 10
- [ ] Complete Documentation Sept 10
- [ ] Complete Relevant Testing Sept 10
 
**Completion Deadline:** Sept. 10
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas
