### ISSUE TITLE
Integration of Bird Dash Mini-Game with Magpie NPC

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#182]
# **Description**
**Task:** [Integration of Bird Dash Mini-Game with Magpie NPC](#182).
**Feature:** [[Team 7] Mini-Games](#6)

Integrate the snake mini-game into the main game. 
 
## **Example**
- The player will approach the magpie character and be able to read the story line from the dialogue box. They will then have the option to play and boot up the bird dash mini-game.

# **Dependencies**
- [ ] Creation of magpie character
- [ ]  Dialogue box for npc characters (#101)
 
# **Milestones**
- [ ] Implementation by Sept. 10
 
**Completion Deadline:** Sept. 10
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas
