### ISSUE TITLE
Team 9 - Boss Abilities

### ISSUE THREAD

**Issue by phurinjeffy** [UQcsse3200/2024-studio-2#188]
# **Description**
**Task:** [Boss Abilities](#3).
**Feature:** [[Team 9] Boss (improvements)](#155)

This task will covers the boss abilities in the turn-based combat system, like a unique special combat movesets for the boss attacks/blocks/dodges, and also implementing the animations for the boss as well. 

# **Dependencies**
- #166 

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create class for the boss abilities (Sep. 6)
- [ ] Design the animations (Sep. 6)
- [ ] Integrate into the combat system (Sep. 12)
- [ ] Testing and documenting (Sep 12.)
 
**Completion Deadline:** Sep. 12
 
# **Documentation**
- [Boss Abilities](../wiki/Boss-Abilities)
 
# **Member**
- Phurin Vanasrivilai (phurinjeffy)
