### ISSUE TITLE
Inventory Class

### ISSUE THREAD

**Issue by mitsudz** [UQcsse3200/2024-studio-2#19]
# **Description**
**Task:** [Create Inventory Abstract Class](#3 ).
**Feature:** [Items and Inventory](#3 )

A class to support various types of inventory's (e.g. combat inventory, general inventory etc.). Should implement abstract interface for handling using, adding and removing from inventory. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add interface for inventories (12 Aug)
- [x] Add inventory class with basic functionality (13 Aug)
- [x] Test inventory class (13 Aug)
- [x] Merge into 3-inventory-and-items (16 Aug)
- [x] Write wiki (16 Aug)
- [ ] Merge into main (27 Aug)

# **Dependencies**
- [x] Item Abstract Class needs to be generated for storage of items (#18 )
 
**Completion Deadline:** Aug. 16

# **Documentation**
- [Inventory Wiki Page](https://github.com/UQcsse3200/2024-studio-2/wiki/Inventory)
 
# **Member**
- Name (Github Username) `Discord Username`
- Mittun (@mitsudz ) `mitsudz`
