### ISSUE TITLE
Extended FNPC Dialogue Functionality: Option Buttons for hints

### ISSUE THREAD

**Issue by nreyana** [UQcsse3200/2024-studio-2#190]
# **Description**
**Task:** Add options for user to pick when interacting with the dialogue box (for hints and quest progression).
**Feature:** Friendly Animals (NPC) [Team 4]

Involves modifying the existing `DialogueBox` to include selectable options that players can choose from during interactions with Friendly NPCs. This functionality will enable NPCs to offer hints or present quest-related choices, improving the player's engagement and enhancing the game's narrative. Dialogue options will be displayed as buttons within the DialogueBox, and the player's choice will trigger corresponding responses or actions within the game.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Update DialogueBox to include option buttons and handle user selections (Sep. 7).
- [x] Implement basic test cases for dialogue option functionality (Sep. 9).
- [x] Document updated changes in the DialogueBox wiki (Sep. 11)
 
# **Documentation**
- [Dialogue Box Documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Dialogue-Box)
- [Friendly NPCs Documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Friendly-NPCs)
 
# **Members**

- Hyunmin Cho (@eftg1000)
- Nahin Khan (@nreyana)
- Shubh Gupta (@shubhgupta2510)
