### ISSUE TITLE
Convert EnemyNPC to FriendlyNPC once the enemy is beaten

### ISSUE THREAD

**Issue by shubhgupta2510** [UQcsse3200/2024-studio-2#191]
# **Description**
**Task:** Once an EnemyNPC is beaten, change the entity type of the beaten NPC to a FriendlyNPC
**Feature:** Friendly Animals (NPC) [Team 4]

This task involves modifying the game's logic to recognise when an EnemyNPC has been defeated. Upon defeat, the EnemyNPC's entity type will be updated to FriendlyNPC. This change will trigger corresponding behaviors and interactions, such as preventing the FriendlyNPC from attacking the player and potentially introducing new gameplay elements or interactions. This feature will add a dynamic element to the game world by allowing defeated enemies to become potential allies or sources of information.

# **Dependencies**
- Team 5 for Combat Interaction
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement a class for the conversion of the entities (Sep. 2)
- [x] Implement a check to see if an NPC has been defeated (Sep. 5)
- [x] Convert EnemyNPC to FriendlyNPC (Sep. 5)
- [x] Implement testing for the conversion of entities (Sep. 9)
- [x] Write up the documentation for the new class in the wiki (Sep. 10)
 
**Completion Deadline:** Sep. 11
 
# **Documentation**
[Entity Conversion Details](https://github.com/UQcsse3200/2024-studio-2/wiki/Enemy-Converting-to-Friendly-Upon-Defeat)
 
# **Member**
- Shubh Gupta (@shubhgupta2510)
