### ISSUE TITLE
SnakeMiniGame JunitTests

### ISSUE THREAD

**Issue by rp3002** [UQcsse3200/2024-studio-2#193]
# **Description**
**Task:** [SnakeMiniGame JunitTests](#193)
**Feature:** [Mini-Games](#6)

The Snake Mini-Game requires JUnit testing to ensure that all key components function correctly and interact seamlessly. This task involves writing and executing JUnit tests for the following components: `Events`, `SnakeGrid`, `SnakeController`,`AppleRenderer`, `GridRenderer`, `SnakeGameRenderer`, `SnakeRenderer`, `EndSnakeScreen`, `MiniGameMenuScreen`, and `SnakeScreen`. The tests will validate the correct behaviour of game events, rendering processes, screen transitions, and other critical functionalities. This includes verifying that each component performs as expected under various scenarios and integrates properly with other parts of the game.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Base implementation for each component should be completed (Done in Sprint 1)

 
# **Milestones**
- [x] Write  and run JUnit tests for `Events` (Sep. 1)  
- [x] Write  and run JUnit tests for `SnakeGrid` (Sep. 1)  
- [x] Write  and run JUnit tests for `SnakeController`(Sep. 2) 
- [ ] Write  and run JUnit tests for `AppleRenderer`(Sep. 2)  
- [x] Write  and run JUnit tests for `GridRenderer` (Sep 2)
- [ ] Write  and run JUnit tests for `SnakeGameRenderer`(Sep. 2)  
- [x] Write  and run JUnit tests for `SnakeRenderer` (Sep. 2) 
- [ ] Write  and run JUnit tests for `EndSnakeScreen` (Sep. 3)  
- [ ] Write  and run JUnit tests for `MiniGameMenuScreen` (Sep. 3)  
- [ ] Write  and run JUnit tests for `SnakeScreen` (Sep. 3)  
 
**Completion Deadline:** Sep. 4
 
# **Documentation**
to be updated
 
# **Member**
- Rajanya Paul Choudhury (@rp3002)
- Ella Berglas (@EllaBerglas)
