### ISSUE TITLE
Bird Screen

### ISSUE THREAD

**Issue by 24msingh24** [UQcsse3200/2024-studio-2#196]
# **Description**
**Task:** [Bird Screen](#3).
**Feature:** [https://github.com/UQcsse3200/2024-studio-2/issues/6](#2)

The task is to implement Bird Screen with a background Image. Also this involves Rendering the bird on the screen .")
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Get the Basic Screen for Flappy bird Mini Game
- [x] Upload it with background 
- [x] Render the bird 
- [x] Documentation and Unit 
 
**Completion Deadline:** Sept 4

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (@24msingh24 )

**Comment by 24msingh24** [comment]
Completed
