### ISSUE TITLE
Updated Help Menu

### ISSUE THREAD

**Issue by ishusharma13** [UQcsse3200/2024-studio-2#198]
# **Description**
**Task:** Help Menu
**Feature:** Descriptive window for game

Help button is already implemented, which opens a window displaying 5 slides. The task involves adding more slides to this window and populating them with relevant information based on the game's content and input from other teams.
 
## **Example (optional)**
Gather information from other teams, such as the combat team, to accurately detail the key moves and controls of the game. 

# **Dependencies**

- [x]  Dependent on other teams for the information to be included in the slides.
- [x] Depends on UI of the game

# **Milestones**

- [x] Identify Required Information(Sept 5)
- [x] Coordination with Teams(Sept 5)
- [x] Collection of Information(Sept 6)
- [x] Organizing and Structuring Content(Sept 7)
- [x] Slide Creation and Content Population(Sept 8)
- [x] Internal Review and Feedback(Sept 9)
- [x] Final Adjustments(Sept 9)
- [x] Testing and Implementation(Sept 11)
 
# **Documentation**
[Updated Help Menu](https://github.com/UQcsse3200/2024-studio-2/wiki/Help-Menu)
[Test cases: Slides ](https://github.com/UQcsse3200/2024-studio-2/wiki/Test-Cases:-Slides-(Help-Menu))
 
# **Member**

- Ishu (@ishusharma13 ) (discord: @ishusharrma)
- Jay (@jt-09 )
