### ISSUE TITLE
Tutorial Button

### ISSUE THREAD

**Issue by ishusharma13** [UQcsse3200/2024-studio-2#199]
# **Description**
**Task:** Tutorial Menu
**Feature:** Text/Visual game guide

A Tutorial button will open a window that provides a guided walkthrough of the game, especially for beginners, allowing players to either play through the tutorial or watch a demonstration to learn how the game works. There will also be a separate window dedicated to mini-game tutorials, offering players the option to practice mini-games before encountering them in the main gameplay.
 
## **Example (optional)**
If you're playing the game for the first time and want to see a walkthrough, this feature will be incredibly helpful.

# **Dependencies**

- [ ] Depends on the game working
- [ ] Depends on minigames team for minigame tutorial
 
# **Milestones**

- [ ] Define Tutorial Content and Structure(Sept 4)
- [ ] Design the Tutorial Interface(Sept 5)
- [ ] Develop Tutorial Walkthroughs(Sept 7)
- [ ] Implement the Tutorial Button(Sept 7)
- [ ] Integrate Content(Sept 8)
- [ ] Testing and Quality Assurance(Sept 10)
- [ ] Feedback and Revisions(Sept 11)
- [ ] Final Implementation and Deployment(Sept 11)
 
# **Documentation**
- To be updated
 
# **Member**
- Ishu (@ishusharma13 ) (discord: @ishusharrma)
- Tarushi(@TarushiG )
