### ISSUE TITLE
Bird Mini-Game JUnitTests 

### ISSUE THREAD

**Issue by rp3002** [UQcsse3200/2024-studio-2#202]
# **Description**
**Task:** [Bird Mini-Game JUnitTests ](#202).
**Feature:** [Mini-Games](#6)

This task involves writing JUnit tests for different components of the Bird Game to ensure they function as expected. 
The components to be tested include Bird (including assets), Coin (including assets), Obstacles, Boundary and game termination (including score calculation), Bird and physics, and the End Game Screen. 

# **Dependencies**
- [x] Bird assets need to be integrated and accessible for testing. (#xx)
- [x] Coin assets need to be integrated and accessible for testing. (#xx)
- [x] Obstacles need to be implemented and included in the game. (#xx)
- [x] Boundary and game termination logic must be implemented and functional. (#195)
- [x] Physics for Bird’s movement and interaction need to be implemented. (#xx)
- [x] End Game Screen needs to be designed and included in the game. (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] JUnit tests for Bird (Sep 6)
- [x] JUnit tests for Coin (Sep 6)
- [x] JUnit tests for Pipes (Sep 7)
- [x] JUnit tests for Spikes (Sep 7)

**Completion Deadline:** Sep 9
 
# **Documentation**
To be Updated
 
# **Member**
- Rajanya Paul Choudhury (@rp3002)
- Nathan (@0NATE4)
- James (@jakingy)
