### ISSUE TITLE
Implement Resize for Snake Minigame

### ISSUE THREAD

**Issue by 0NATE4** [UQcsse3200/2024-studio-2#204]
# **Description**
**Task:** [Implement Resize for Snake Minigame](#3).
**Feature:** [Minigames](#6 )

Currently the game cannot handle resizing well. This will be fixed by using a camera that will always position the game with a set perspective and dimension, so that no matter the resizing and dimensions, the game will look the same to the user.
 
## **Example (optional)**
- **Using the game resize button**:  When the user presses the resize button, the snake minigame will look exactly the same, but scaled down.

# **Dependencies**

- [ ] Camera for minigame (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Integrate minigame camera into the minigame (Sep. 2)
- [ ] Allow resizing of minigame to work consistently (Sep 4)

 
**Completion Deadline:** Sep. 4

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**

@[0NATE4](https://github.com/0NATE4)
0NATE4
