### ISSUE TITLE
Add Magpie NPC

### ISSUE THREAD

**Issue by nreyana** [UQcsse3200/2024-studio-2#205]
# **Description**
Task: Add a Magpie NPC.
Feature: Friendly Animals (NPC) (Team 4)
Adds an interactable NPC that resembles a Magpie. Each NPC will have specific stats (possibly including but not limited to HP, Speed, Attack etc.) and perhaps slightly different roaming tasks. NPC should also allow interaction with the player with a dialogue box and accommodate quest-giving to the player. They may also offer helpful gameplay hints.

The Magpie NPC will be used to deliver the "Flappy-bird" mini-game.

Part: A Magpie NPC sprite will wander the map, being drawn to the player if in close proximity and then pause so the player can read dialogue if nearby.
Quest/Storyline Progression/Hints: The player will then have the option to interact with the Magpie and trigger dialogue and/or quests. This may either give hints or progress the storyline with a quest.
 
# **Dependencies**
- []  NPC Sprite of a Magpie 
- [x] Dialogue Box https://github.com/UQcsse3200/2024-studio-2/issues/101
- [ ]  Mini-game (Team 7)

# **Milestones**

- [] Create base NPC behaviour for Magpie and document on wiki (August 15)
- [] Implement tests for Magpie (August 21)
- [] Create magpie sounds for when magpie pauses
- [] Accommodate Dialogue/Quest Progression (August 21)
- [] Magpie NPC implemented and tested (August 25)
- [] Update documentation on wiki (August 25)

 
**Completion Deadline:** Aug. 25
 
# **Documentation**
- [Friendly NPC Documentation](../wiki/Friendly-NPCs)
- [Magpie NPC Documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Magpie)
- [Dialogue Box (NPC)](https://github.com/UQcsse3200/2024-studio-2/wiki/Dialogue-Box)
 
# **Member**
- Nahin (Reyana) Khan (@nreyana)
