### ISSUE TITLE
[Team 9] Boss Combat Integration

### ISSUE THREAD

**Issue by callumreillyy** [UQcsse3200/2024-studio-2#209]
# **Description**
**Task:** [Boss Combat](#209).
**Feature:** [[Team 9] Boss (improvements)](#155)

This task will cover integrating the boss into the combat system. The sprite will be loaded into the combat screen with correct stats, abilities and status effects onto the combat area. Will also entail updating the stats component (more detail in statistics task).
 
## **Example**
- **Poison Status Effect**: Player may load into combat with a poison type boss. If this occurs they will be applied a debuff which is detrimental to their character. Poison would be in the form of ticking health loss for 'x' amount of rounds.

# **Dependencies**
- General collaborative working with team 10
- (#166 )
- (#178 )
- (#179 )
- (#188 )
 
# **Milestones**
- [x] Load Kanga Boss entity into combat area (Sep. 8)
- [x] Load Kanga Boss statistics/effects into combat screen (Sep. 10)
- [x] Apply effects to combat area (Sep. 11)
- [x] Update Boss stats when 'attacked' by player (Sep 11)
- [x] Test successful load of kangaroo resources (Sep. 13)
 
**Completion Deadline:** Sep.13

# **Documentation**
- [Combat Screen Design]
(https://github.com/UQcsse3200/2024-studio-2/wiki/Combat-Screen)

# **Member**
- CallumR (@callumreillyy )
