### ISSUE TITLE
Setting Button (Option Button)

### ISSUE THREAD

**Issue by Slothlesss** [UQcsse3200/2024-studio-2#21]
# **Description**
**Task:** Setting Button (Option Button)
**Feature:** Adjusting game settings

Click this button to open the settings menu, where you can personalize your game experience. You can adjust controls, audio, graphics, language, and other things.

# **Dependencies**
- [ ] UI design for buttons needs to be created.
- [ ] UI design for setting menu background needs to be created.
- [ ] Click sound for buttons needs to be created.
- [ ] Components such as audio sliders, graphics and language dropdown menu, etc need to be developed.
 
# **Milestones**
- [x] Implement the option button with color shape. (Aug. 14)
- [x] Implement setting menu (Aug. 14)
- [x] Implement functionality to open setting Menu (Aug. 16)
- [x] Implement sliders for music settings, dropdown menu for graphics, etc. (Aug. 23)

 
**Completion Deadline:** Aug. 31
 
# **Documentation**
To be updated.

# **Member**
- Minh (@Slothlesss) (Discord: Slothless)
