### ISSUE TITLE
Update Loading Screen

### ISSUE THREAD

**Issue by Slothlesss** [UQcsse3200/2024-studio-2#210]
# **Description**
**Task:** Update Loading Screen.
**Feature:** Add more details for the loading screen

The loading screen will be implemented a background, progress text, some tips or animation to make it less boring, enhancing player experience.
 
# **Dependencies**
- [ ] Tips/trick in the game need to be made.
- [ ] UI design for background needs to be created.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add progress text (Sep. 3)
- [ ] Add background (Sep.  6)
- [ ] Add some tips/animation in the bottom of the loading screen (Sep. 13)
 
**Completion Deadline:** Sep. 13

# **Member**
- Minh Long Vu (@Slothlesss)
