### ISSUE TITLE
Drag Inventory Items

### ISSUE THREAD

**Issue by tompreston1** [UQcsse3200/2024-studio-2#215]
# **Description**
**Task:** [Drag Inventory items](#215).
**Feature:** [Item/Inventory Sprint 2 features](#157)

The Drag Inventory Items is requires for an item to be clicked by a mouse in the inventory and dragged to an empty slot in the inventory where the item is now relocated to. The item will be put in the new box if the mouse is released over an empty box otherwise the item will not move.
 
## **Example: Minecraft Inventory Item Drag**
![image](https://github.com/user-attachments/assets/dcdf1201-4ff0-4b02-ac1e-867a4f7fd1f8)
 
# **Milestones**
- [x] Have the mouse drag functionality (Sept 15)
- [x] Have Item image dragging (Sept 15)
- [x] Submit Pull Request (Sept 20)
 
**Completion Deadline:** Sep. 15

# **Documentation**
- TBD

# **Member**
- Tom (tompreston1) `tom1527383791`
- Pratul (PratulW5) `cactusjuice`
