### ISSUE TITLE
Creating LootBoxes, LootItems, LootTables

### ISSUE THREAD

**Issue by lhick2108** [UQcsse3200/2024-studio-2#216]
# **Description**
**Task:** [Creating LootBoxes, LootItems, LootTables](#3).
**Feature:** [Item/Inventory Sprint 2 features](#157)

For minigames and quest rewards, it's been decided to have a LootBox system that generates a random item for a set LootTable, for less coupling, I've decided to create a lootItem class which will hold the item and a weight which will determine rarity. The idea for this so that it should merge into the project easier and can be changed afterwards if need be.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 Create LootItem, LootTables, LootBoxes Class (Aug 6)
- [ ] Step 2 Connect these to the minigames rewards (Aug 9)
- [ ] Step 3 Connect these to quests (TBD)
**Completion Deadline:** TDB

 
# **Documentation**
- TDB
 
# **Member**
- Lewis Hickson (lhick2108)(prehistoricmesopotamiantablet)
