### ISSUE TITLE
[Team 5] Main Quest - Land kingdom

### ISSUE THREAD

**Issue by reemmi** [UQcsse3200/2024-studio-2#217]
# **Description**
Task: [Quest Integration](https://github.com/UQcsse3200/2024-studio-2/issues/217#3).
Feature: [Quests](https://github.com/UQcsse3200/2024-studio-2/issues/217#2)
Main quest design (pg 3): [Quest Design Principles](https://docs.google.com/document/d/1wU8tCjtxcwhCAz9ChNnB_ZTt52dNG77u0xnt-aH6nrA/edit#heading=h.kep2koeo5cvc)

Complete the quest design for the Land Kingdom's main quest in the first kingdom. This task includes creating textures for the player wearing armor and for armor in partially and fully broken states. Implement the mechanism that allows armor to be placed onto the map, focusing on medium-level tasks related to quest integration, dialogue, story development, task creation, and triggering. Additionally, make small adjustments to the Quests UI to clearly indicate when a quest is complete, when an NPC has a quest, and when an NPC is involved in an ongoing quest.
 
# **Dependencies**
- [x] QuestManager
- [x] Items/ inventory basic design completed
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Complete quest design for land kingdom (1st kingdom)'s main quest. (Sept. 3)
- [x] Add listeners for item collection - inventory set to listen. (Sept. 6) Maree 
- [x] Edit the inventory to count the number of required quest items present in it (Sept. 7) Maree
- [x] Edit inventory components and player keyboard actions to send out task completed message once quest task required amount of items is collected. (Sept. 8) Maree
- [x] Add listeners for item collection - quests set to listen. (Sept 8) Maree & Remmy
- [x] Set up quest tasks and integrate with existing system in QuestManager. (Sept 8) Remmy
- [ ] #271
- [x] Test new land kingdom progression quest (Sept. 10) 
- [ ] Document changes to inventory class (UML). (Sept. 10) Remmy
- [x]  Document changes to inventory class (sequence). (Sept. 10) Maree
- [ ] Document changes to QuestManager and quests list in Quests wiki. (Sept. 10) Remmy
- [x] Make sequence diagram for QuestManager (Sept. 10) Maree
 
**Completion Deadline:** Sept. 11
 
# **Documentation**
[Quests] (https://github.com/UQcsse3200/2024-studio-2/wiki/Quests)
 
# **Member**
* Remmy ([@reemmi](https://github.com/reemmi) )
* Maree ([@MargoCode](https://github.com/MargoCode) )
