### ISSUE TITLE
Minigame Improvements (Pausing, Preserving screens, Better Snake Movement and Input Handling via Events)

### ISSUE THREAD

**Issue by jakingy** [UQcsse3200/2024-studio-2#224]
# **Description**
**Task:** Minigame Improvements (#224)
**Feature:** Mini Games (#6)

This task incorporates several improvements to mini-games before the implementation of our sprint 2 game. This includes pausing, preserving screens, better snake movement and input handling via events.

# **Dependencies**
- [x] Snake game complete

# **Milestones**
List of steps that need to be completed for this task.
- [x] Incorporate the pause overlay into mini-games (5th September)
- [x] Improve snake movement snake movement (1st September)
- [x] Test snake movement (1st September)
- [x] Refactor mini-games user input to use events (2nd September)
- [x] Refactor mini-games to use preserving screens (3rd September)
 
**Completion Deadline:** 5th September
 
# **Documentation**
- [Snake Class](https://github.com/UQcsse3200/2024-studio-2/wiki/Snake-Component)
- [Snake Game](https://github.com/UQcsse3200/2024-studio-2/wiki/Snake-Game)
- [JavaDoc](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/components/minigame/snake/Snake.html)
- ...
 
# **Member**
- James (@jakingy)
