### ISSUE TITLE
Saving Inventory

### ISSUE THREAD

**Issue by mitsudz** [UQcsse3200/2024-studio-2#242]
# **Description**
**Task:** [Saving Quests](#157 ).
**Feature:** [Team 3 Sprint 2](#157 )

Enable saving and loading of inventory.
 
## **Example (optional)**
E.g, the player picks up some items and saves and exits the game, then restarts the game via the load option. Those items should still be present.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add json writer for each item (create config which handles mapping of names to codes and vice versa) (10 Sep)
- [x] Add json writer for inventory (10 Sep) 
- [x] Add json reader/creator for inventory (T10 Sep)
- [x] Integrate this into PlayerInventoryDisplay (11 Sep)
- [x] Complete functional testing (11 Sep)
- [x] Unit Testing (11 Sep)
 
**Completion Deadline:** 11 Sep

# **Documentation**
- [TBC](TBC)
 
# **Member**
- Name (GitHub Username) (`Discord Username`)
- Mittun Sudhahar (@mitsudz ) (`mitsudz`)
- Lachlan Ellis (@lellis0406 ) (`howlaire`)
