### ISSUE TITLE
Collision Detection for Bird Game

### ISSUE THREAD

**Issue by 0NATE4** [UQcsse3200/2024-studio-2#246]
# **Description**
**Task:** [Collision Detection for Bird Game](#3).
**Feature:** [Minigames](#)

Collision detection is a vital component to the minigame BirdieDash. Detection required to be implemented involves the bird colliding with the pipe, the coins, and the spikes. The collision with the pipes will stop the birds movement and drag it towards the left side of the screen towards the spikes. Collision with a coin will cause it to collected, hence incrementing the score by 1. Collision with the spikes will indicate game over.

# **Dependencies**

- [x] Bird (#)
- [x] Pipe (#247 )
- [x] Coin(#249 )
- [x] Spikes (#248 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create collisionDetection class (Sep 6)
- [x] Implement collision for pipes (Sep 7)
- [x] Test collision for pipes (Sep 7)
- [x] Implement collision for coins (Sep 8)
- [x] Test collision for coins (Sep 8)
- [x] Implement collisions for spikes (Sep 9)
- [x] Test collision for spikes (Sep 9)
- [x] Game Boundary
 
**Completion Deadline:** Sep 9

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
@[0NATE4](https://github.com/0NATE4)
0NATE4
@[rp3002](https://github.com/rp3002)
rp3002
Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas
