### ISSUE TITLE
Pipe for bird minigame

### ISSUE THREAD

**Issue by 0NATE4** [UQcsse3200/2024-studio-2#247]
# **Description**
**Task:** [Pipe for bird minigame(#3).
**Feature:** [Minigames](#2)

The pipe represents an obstacle that the player needs to avoid. Pipes will be created in pairs, one coming from the ceiling, one coming from the ground, and they will have a constant gap in between that the user can go through. Pipes will be created with random heights to ensure the game does not get repetitive. When the player hits a pipe, they will be pushed back towards the left of the screen until they can get out of the way of the pipe. Pipes will be constantly moving towards the left of the screen.
 

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Bird Screen (#196 )

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create Pipe class (Sep 5)
- [x] Test pipe class (Sep 5)
- [x] Create pipe renderer class (Sep 6)
- [x] Test pipe renderer class (Sep 6)
 
**Completion Deadline:** Sep 6

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
@[0NATE4](https://github.com/0NATE4)
0NATE4
