### ISSUE TITLE
Spike for bird minigame

### ISSUE THREAD

**Issue by 0NATE4** [UQcsse3200/2024-studio-2#248]
# **Description**
**Task:** [Spike for bird minigame](#3).
**Feature:** [Minigame](#2)

Spikes are placed on the left side of the screen. The player must avoid the spikes at all cost, as any collision with the spikes will result in the game being over. Spikes do not move, and stretch from the top of the screen to the bottom.
 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create Spike Class (Sep 6)
- [x] Test spike class (Sep 6)
- [x] Create spike renderer (Sep 7)
- [x] Test spike renderer (Sep 7)
 
**Completion Deadline:** Sep 7

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
@[0NATE4](https://github.com/0NATE4)
0NATE4
