### ISSUE TITLE
Coin for bird minigame

### ISSUE THREAD

**Issue by 0NATE4** [UQcsse3200/2024-studio-2#249]
# **Description**
**Task:** [Coin for bird minigame](#3).
**Feature:** [Minigames](#2)

The coin represents the way that the player can increase their score. Coins are spawned at a random height, but are constantly placed in terms of horizontal positioning, that is, they are spawned in the horizontal gap between two pairs of pipes. When the player collides with a coin, the coin will be collected, disappear, increment the players score, and be ready to be spawned back.

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create coin class (Sep 7)
- [x] Test coin class (Sep 7)
- [x] Create coin renderer (Sep 8)
- [x] Test coin renderer (Sep 8)
- [ ] Implement coin de-spawning and score increasing (Sep 9)
 
**Completion Deadline:** Sep 9

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
@[0NATE4](https://github.com/0NATE4)
0NATE4
@[rp3002](https://github.com/rp3002)
rp3002
