### ISSUE TITLE
Bird Classes for BirdMiniGame 

### ISSUE THREAD

**Issue by 24msingh24** [UQcsse3200/2024-studio-2#250]
# **Description**
**Task:** [Bird Classes for BirdMiniGame ](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

This task involves creating a Bird class where all functionality of Bird will be done. Also , Bird Render class wherein bird will spawn. KeyboardBirdInput class - keys for the bird moment will be handled ")
 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a bird class  
- [x] Create a bird Render class  
- [x] Create a InputKeys class  
- [x] Integrate with collision handeling class
- [ ] Do Junit Testing of all the classes
 

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (@24msingh24 ) 
- @[0NATE4](https://github.com/0NATE4)
0NATE4
