### ISSUE TITLE
Add Fish FNPC

### ISSUE THREAD

**Issue by BaileyS03** [UQcsse3200/2024-studio-2#253]
# **Description**
**Task:** Add a Fish NPC.
**Feature:** [Team 4] Friendly NPCs Extension #152

Adds an interactable friendly NPC that resembles a Fish. The fish will have specific stats (possibly including but not limited to HP, Speed, Attack etc.). The fish should also allow interaction with the player with a dialogue box. The fish will also provide hints to the player with it's base hint being a welcome to the game.
 
## **Example (optional)**
- ***Part***: A Fish NPC sprite will wander the map, being drawn to the player if in close proximity and then pause so the player can read dialogue if nearby.

# **Dependencies**
There are no dependencies. This item is completely isolated from any other teams and will be completed by solely one person to improve efficiency. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create base NPC behaviour for Fish and document on wiki (Sep. 9)
- [ ] Implement tests for fish (Sep. 9) 
- [x] Update Documentation on wiki (Sep. 9) 
 
**Completion Deadline:** Sep. 9
 
# **Documentation**
- [Friendly NPC Documentation](../wiki/Friendly-NPCs)
- - [Friendly NPC Documentation](../wiki/Friendly-NPCs/Fish)
 
# **Member**
- Bailey Stoodley (@BaileyS03)
