### ISSUE TITLE
[Team 9] Display end game stats

### ISSUE THREAD

**Issue by callumreillyy** [UQcsse3200/2024-studio-2#263]
# **Description**
**Task:** End Game Stats Display(#253 ).
**Feature:** (#155 )

This task will implement a screen upon defeating the final boss of the game, to display stats tracked throughout within the Stat class. 
 
## **Example (optional)**
- **Part**: Depending on the task, you may want to provide some examples of how it would play out in the game. See next point for example...
- **Enemies Defeated**: At the end of the game the player will be able to see how many enemies they defeated, or were defeated by.

# **Dependencies**
- [x] Combat Team 10 (#xx)
- [x] Items/Inventory 3 (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Update end game stat component after event (Sep. 10)
- [x] Fetch end game stat component count within display (Sep. 10)
- [x] Create end game stat display (Sep. 11)
- [x] Test end game stat display (Sep. 11)
 
**Completion Deadline:** Sep. 12
 
# **Documentation**
- [End Game Statistics](https://github.com/UQcsse3200/2024-studio-2/wiki/End-Game-Statistics)
 
# **Member**
- Callum Reilly (@callumreillyy)
