### ISSUE TITLE
Create Consumable Abstract class

### ISSUE THREAD

**Issue by PHONGNGYUEN1** [UQcsse3200/2024-studio-2#27]
# **Description**
**Task:** [Create Cinsumable Abstract Class](#3).
**Feature:** [#3](#2)

An abstract class to support various item types (e.g. items with a finite number of uses)

## **Example**
- Food items for animal hunger during a match and cannot perform properly until it is fed so the food item will be available for them to consume 
- Potions to improve animal stats

# **Dependencies**
- [x] Items Abstract class (#18 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create Consumable Class (Aug. 14)
- [x] Create tests for Consumable Class (Aug. 14)
- [x] Merge into 3-inventory-and-items via pull request (Team 3 main branch) (Aug 14)
- [ ]  Add documentation for Consumable class in wiki (Aug. 16)

 
**Completion Deadline:** Aug. 16

 
# **Documentation**
- [Consumable Item Wiki](https://github.com/UQcsse3200/2024-studio-2/wiki/Consumable-Item) ** NOT YET COMPLETED **
 
# **Member**
- Name (@PHONGNGYUEN1 ) (beannie)
