### ISSUE TITLE
NPC-Quest dialogue integration

### ISSUE THREAD

**Issue by MargoCode** [UQcsse3200/2024-studio-2#271]
# **Description**
Task: 
Feature: 
Main quest design (pg 3): [Quest Design Principles](https://docs.google.com/document/d/1wU8tCjtxcwhCAz9ChNnB_ZTt52dNG77u0xnt-aH6nrA/edit#heading=h.kep2koeo5cvc)

Integrate quests dialogue with cow NPC to stay up to date with current quest task completion.
 
# **Dependencies**
- [x] QuestManager
- [x] NPC basic implementation complted
- [x] Dialogue box design completed
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add get current dialogue method to QuestManager
- [x] Integrate cow NPC dialogue to get dialogue from QuestManager
- [x] Create documentation for method calling
- [x] Update Quests wiki
- [x] Update NPC wiki
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
[Quests] (https://github.com/UQcsse3200/2024-studio-2/wiki/Quests)
 
# **Member**
* Remmy ([@reemmi](https://github.com/reemmi) )
* Maree ([@MargoCode](https://github.com/MargoCode) )
