### ISSUE TITLE
Score Board and Scoring System for Birdie Dash

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#272]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

Implement on screen scoreboard and score definition for birdie dash game.
 

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Bird creation
- [ ] Coin creation
- [ ] Collision detection between bird and coin
 
# **Milestones**
- [ ] Completion by 10th september

**Completion Deadline:** Sept. 10

e.g.
- [ ] Implementation of score and score increment
- [ ] Generalise current score board
- [ ] Integrate and adjust style of scoreboard
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas
