### ISSUE TITLE
End Game Screen for Birdie Dash

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#273]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

Implement end game screen for birdie dash mini-game.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Game termiination (#xx)
- [ ] End screen generalisation (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Boot up screen at game termination
- [ ] Adjust to birdie dash game constants
- [ ] Adjust button actions
- [ ] Implement messages
 
**Completion Deadline:** Sept. 10
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas
