### ISSUE TITLE
Add EntityConverter Tests

### ISSUE THREAD

**Issue by Jul-Wong** [UQcsse3200/2024-studio-2#277]
# **Description**
**Task:** (#277).
**Feature:** (#152) 

In conjunction to the creation of the new class `EntityConverter`, the tests will ensure the correct implementation of the conversion of enemy entities to friendly NPC's. These will test the removal of certain unfriendly components and add additional friendly components to the entity.

# **Dependencies**
- [x] Entity Converter Class

# **Milestones**
- [x] Tests Implemented (Sep 12)
- [x] Documented Tests (Sep 12)

 
# **Documentation**
- [Enemy Conversion to Friendly Upon Defeat](https://github.com/UQcsse3200/2024-studio-2/wiki/Enemy-Converting-to-Friendly-Upon-Defeat)
- [Enemy Converter Test Plan](https://github.com/UQcsse3200/2024-studio-2/wiki/EntityConverter-Test-Plan)
 
# **Member**
- Julian Wong (@Jul-Wong)
