### ISSUE TITLE
[Team 2] Monkey Enemy NPCs Spawn and Throw Banana to Player

### ISSUE THREAD

**Issue by nownver** [UQcsse3200/2024-studio-2#278]
# **Description**
**Task:** [Monkey Enemy NPCs Spawn and Trow Banana to Player](#278 )
**Feature:** [Enemy NPCs Interaction Feature](#156 )

Enhance the behavior of Monkey enemy NPCs by implementing a new feature where they can throw bananas and spawn banana items within the game. This will add a unique attack mechanic and a new item for players to interact with (dodge).

# **Dependencies**

- [Enemy Texture and Animation] (#83)

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement an animation where Monkey NPCs throw bananas at the player (Sep. 9)
- [x] Create a banana item that spawns when the Monkey NPC throw it (Sep. 10)
- [x] Define the behavior of the banana item in the game, including any effects or interactions it has with the player (Sep. 11)
- [x] Integration of animation and texture into the game (Sep. 11)
- [x] Testing and adjustments (Sep. 11)

**Completion Deadline:** Sep. 12
 
# **Documentation**
[Projectile Entities](https://github.com/UQcsse3200/2024-studio-2/wiki/Projectile-Entities)
[Banana Attack (Monkey NPC)](https://github.com/UQcsse3200/2024-studio-2/wiki/Banana-Attack-(Monkey-NPC))
 
# **Member**
- Milo (@mhUnt3rS) (Milo Hunter)
- Lucas (@LucasRyall) (Lucas Ryall)
