### ISSUE TITLE
Buttons Main Screen

### ISSUE THREAD

**Issue by jtayl647** [UQcsse3200/2024-studio-2#279]
# **Description**
**Task:** Buttons
**Feature:** Start Screen & Menu Development(#158)

Button skins for main menu should be made for each button, a wiki page for similar development will be made also.
 
# **Dependencies**
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create Background for buttons (Sep. 9)
- [x] Add writing to buttons (Sep. 10)
- [x] Upload the button skins (Sep. 11)
- [x] Implement to main screen (Sep. 11)
- [x] Test functionality (Sep. 11)
 
# **Documentation**
- [Buttons Main Screen](https://github.com/UQcsse3200/2024-studio-2/wiki/Buttons-Main-Screen)
 
# **Member**
- Jaimee Taylor (@jtayl647)
- Minh Long Vu  (@Slothlesss)
