### ISSUE TITLE
Create Food Abstract class and Render Food Items

### ISSUE THREAD

**Issue by PHONGNGYUEN1** [UQcsse3200/2024-studio-2#28]
# **Description**
**Task:** [Create Food Abstract class](#3).
**Feature:** [#3 ](#2)

An abstract class to support different food types (e.g. sea, land, sky based food types) to feed to animals mid or outside of combat. This should also involve rendering 
 
## **Example (optional)**
- Animal may feel hungry during combat and requires food items to continue to perform 

# **Dependencies**
- [x] #18 
- [x] #27 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create Item class (Aug. 11)
- [x] Create Consumables  (Aug. 12)
- [x] Create Food abstract class (Aug. 12)
- [x] Create Multiple food items (Aug. 23) 
- [x] Create food assets(Aug. 20) 
 
**Completion Deadline:** Aug. 26

 
# **Documentation**
- [Food Wiki Page](https://github.com/UQcsse3200/2024-studio-2/wiki/Food) (NOT YET UPDATED TO INCLUDE RENDER INFORMATION)
 
# **Member**
- Name (@PHONGNGYUEN1) (beannie) (Nicole)
