### ISSUE TITLE
Game Over UI

### ISSUE THREAD

**Issue by jtayl647** [UQcsse3200/2024-studio-2#280]
# **Description**
**Task:** Game Over UI
**Feature:** Start Screen & Menu Development(#158)
Game over display should match UI for other sections of game. Create two new splash screens.

# **Milestones**
- [x] Copy screens UI from other sections (Sep. 9)
- [x] Add writing (Sep. 10)
- [x] Upload Splash (Sep. 10)

# **Documentation**
Game Over UI (https://github.com/UQcsse3200/2024-studio-2/wiki/Game-Over-UI)

# **Members**
- Jaimee Taylor (@jtayl647)
