### ISSUE TITLE
Altered UI for main menu

### ISSUE THREAD

**Issue by jt-09** [UQcsse3200/2024-studio-2#281]
# **Description**
**Task:** [Altering  UI for main menu](#3).
**Feature:** [Start Screen and menu development](#158 )

Altering the main menu display from a simple UI to a theme-based UI involves enhancing the visual appeal and user experience by incorporating design elements, colors, and styles that align with a particular theme or concept. Instead of a plain, functional layout, a theme-based UI adds character by using custom backgrounds, unique icons, animations, and fonts tailored to the chosen theme, whether it’s futuristic, nature-inspired, or minimalist. 
 
## **Example (optional)**
- **Part**: 
- **Altering Button skins**: Current button skins are boring and green. Altering them to different colours based on themes to further accentuate the look of the game.

# **Dependencies**
#279 Buttons main screen (to select font, theme UI formatting etc)
#184 Bright mode and dark mode toggling

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Select UI skins etc and implement button skins, night(Sep. 5th)
- [ ]  (Sep. 5th)
- [ ] Step 3 (Sep. 7th)
 
**Completion Deadline:** Aug. 23

e.g.
- [ ] Initial design of `Armour` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
