### ISSUE TITLE
Login/Register Menu

### ISSUE THREAD

**Issue by Slothlesss** [UQcsse3200/2024-studio-2#282]
# **Description**
**Task:** Login/Register Menu UI.
**Feature:** Start Screen & Menu Development (#158)
 
The Login/Register Menu provides users with an interface to login to an existing account or create a new one. It currently doesn't have any functionality yet, but user can input text into username and password field.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create Login Menu (Sep. 4)
- [x] Create Register Menu (Sep. 5)
- [x] Create button to swap button Login and Register Menu (Sep. 5)
- [x] Fixing bugs. (Sep. 11)
 
**Completion Deadline:** Sep. 5
 
# **Member**
- Minh Long Vu (@Slothlesss)
