### ISSUE TITLE
[Team 2] Add a bear enemy NPC

### ISSUE THREAD

**Issue by JackMccabe2** [UQcsse3200/2024-studio-2#283]
# **Description**
**Task:** Implementing a Bear enemy

Adding a bear enemy to the game. Will be the strongest enemy of the forest biome. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Find Appropriate PNG and write atlas file (Sep. 9)
- [x] Implement a visible entity, with ability to chase (Sep. 10)
- [x] Implement animations, different animations for chasing and floating (Sep. 11)
- [x] Integration of animation and texture into the game (Sep. 11)
- [ ] Testing and adjustments (Sep. 11)
 
**Completion Deadline:** Sep. 11
 
# **Documentation**
[Bear Enemy NPC](https://github.com/UQcsse3200/2024-studio-2/wiki/Bear-(Enemy-NPC))
 
# **Member**
- Jack (@JackMccabe2 ) (Jack McCabe)
