### ISSUE TITLE
Saving Player Data

### ISSUE THREAD

**Issue by lellis0406** [UQcsse3200/2024-studio-2#286]
# **Description**
**Task:** Implement Basic Saving/Loading for Player Attributes
**Feature:** #165 

Implementing a basic data structure to contain player data, as well as saving and loading this player data.

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Basic Data Struct (11 Sep)
- [x] Save Data (11 Sep)
- [x] Load Data and Bypass Selection Screen on Load (11 Sep)
- [x] Expand Data Struct
 
**Completion Deadline:** (17 October)
 
# **Documentation**
- [Game-State-Saves wiki](https://github.com/UQcsse3200/2024-studio-2/wiki/Game-State-Saves)
 
# **Member**
- Lachlan Ellis (@lellis0406)

**Comment by lellis0406** [comment]
done for real this time
