### ISSUE TITLE
[Team7] Birdie Dash Mini-Game

### ISSUE THREAD

**Issue by 24msingh24** [UQcsse3200/2024-studio-2#287]
# **Description**
We are the mini-games team, tasked with implementing  Birdy Dash Game in Sprint 2. This mini game is associated with the magpie NPC.

Sprint 2 will focus on implementing a new minigame Birdy Dash. We will also work to implement pausing and resizing as well as generalise code used in the snake game. The score will be calculated based on the number of coins collected by the bird. In the game, the bird will have to fly avoiding obsticles and collecting coins. The game will end once the bird has fallen off the back or below the screen.

Improvements and generalisation
- [x] Pausing, improve key presses, implementation of preserving screen (#224)
- [x] Generalise end game screen (#180)
- [x] Resizing to the screen size (#204)
- [x] Implementing cameras (#167)
- [x] Performing JUnit Tests (#193)

Birdy Dash Basics
- [x] Screen rendering for Birdy Dash (#196 )
- [x] Bird Implementation (#250 )
- [x] Bird and game physics: including speed(#250 )
- [x] Obstacles Implementation, including dynamic obstacles:
  - [x] Coins (#249)
  - [x] Pipes (#247)
  - [x] Spikes (#248)
- [x] Collision detection (#246)
- [x] Boundary and game termination (including calculating score) (#195)
- [x] Birdie Dash score board (#272)
- [x] End Game Screen (#273)
- [x] JUnit Tests (#202)
- [x] Bugfixes (#305)

Game Integration
- [x] Integration of Snake into the main game. Associated with snake NPC (#181)
- [x] Integration of Birdy Dash into the main game. Associated with bird NPC (#182)

# **Milestones**
- [x] Improvements and generalisation (Wednesday 4th September)
- [x]  Birdy Dash Basics (Sunday 8th September)
- [x] Integration of Snake into the main game. Associated with snake NPC  (Tuesday 10th September)
- [x] Integration of Birdy Dash into the main game. Associated with a bird NPC  (Tuesday 10th September)
- [x] Appropriate Testing and Documentation (Tuesday 10th September)

- Birdy Dash

![image](https://github.com/user-attachments/assets/c51502ce-cd77-4c97-bcb7-671c78e40db2)

# **Members**
James King
@[jakingy](https://github.com/jakingy)
jakingy

Nathan Chung
@[0NATE4](https://github.com/0NATE4)
0NATE4

Manandeep Singh
@[24msingh24](https://github.com/24msingh24)
24msingh24

Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas

Rajanya Paul Choudhury
@[rp3002](https://github.com/rp3002)
rp3002
