### ISSUE TITLE
Implement settings menu in pause menu

### ISSUE THREAD

**Issue by jt-09** [UQcsse3200/2024-studio-2#290]
# **Description**
**Task:**  Implement Settings Menu in Pause Menu
**Feature:** [Start screen and menu development](#158 )

This task involves integrating a functional settings menu into the existing pause menu. The settings menu will be displayed when the player presses the settings button on the pause screen. It will use SettingsMenuDisplay to allow the player to modify settings such as audio, screen resolution, and game performance (e.g. FPS limit). The settings will be applied in real time or when the player clicks on the "Apply" button. Additionally, the menu should respond correctly to being closed and reopened, and should transition smoothly between the pause and settings screens.
 
## **Example (optional)**
- **Settings Usage**: When the player pauses the game and clicks "Settings", the settings menu appears, allowing the player to change volume, screen resolution, and other options. These changes can be saved by pressing the "Apply" button or discarded by pressing the "Close" button to return to the pause menu. 

# **Dependencies**
 Audio functionality from settings menu #183 
Updated settings menu #281 

# **Milestones**
List of steps that need to be completed for this task.
- [x]  Create and solidify design for Settings Overlay (Sept. 7th)
- [x] Implement settings overlay (Sept. 10th)
- [x] Integrate settings overlay with pause overlay (and pause menu) (Sept. 11th)
 
**Completion Deadline:** Sept. 11th

# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2024-studio-2/wiki/Settings)
 
# **Member**
- Jay Thakkar(@jt-09 )

**Comment by jt-09** [comment]
Feature ticket closed, task done!
