### ISSUE TITLE
[Team 9] Introduction Story

### ISSUE THREAD

**Issue by reonse** [UQcsse3200/2024-studio-2#299]
# **Description**
**Task:** Story Introduction(#299).
**Feature:** (#155)

This task creates a story screen which will exist in between the animal selection screen and loading screen. The story contains several slides which can be navigated through using next and back buttons. Can be found in the intro-story branch.
 
## **Example (optional)**
- **Part**: Depending on the task, you may want to provide some examples of how it would play out in the game. See next point for example...

# **Dependencies**
- [x] Start Menu Team 6 (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement code so that the selection screen can transition to story screen, then transition to loading screen (Sep. 11)
- [x] Format the display so that the buttons and dialogue are placed correctly (Sep. 11)
- [x] Implement functionality for buttons (Sep. 11)
- [x] Test (Sep. 12)
 
**Completion Deadline:** Sep. 12
 
# **Documentation**
- [Story Line](https://github.com/UQcsse3200/2024-studio-2/wiki/Story-Line)
 
# **Member**
- Jose Leoncio (@reonse)
