### ISSUE TITLE
[Team 3] Items/Inventory 

### ISSUE THREAD

**Issue by s-shalomi** [UQcsse3200/2024-studio-2#3]
# **Description**
This feature introduces a system for players to collect and manage various items throughout the game. The inventory will be available through an in-game menu, where players can view, organize, select and interact with items. It is essential for adding depth to gameplay by providing players with the ability to interact meaningfully with the world by gathering and using resources to enhance gameplay.

## SubFeature/component
- Item Abstract Class (#31)
- Resources/Potions/Artefacts(#24 )
- Inventory Animal & Item Storage
- Inventory Interaction (Interface)
- Inventory UI View
- Scroll 
- Weapons (#30)

## **Examples**
- Pokemon style animal inventory, a team of 6 with no box storage prompting the user to switch one of the monsters for the new one. 
- Bag style of items, can store up to 10 items ensuring that the player uses the items

# **Dependencies**

Animal inventory depends on Animal Player team (#4).

# **Milestones**
- [x] Develop Inventory Structure (Aug. 20)
- [x]  Create Item abstract structure (Aug 20)
- [x] Have basic inventory UI (Aug. 23)
- [x] Create Resource/Potion structure (Aug 23)
- [x] Develop function UI for visualisation of items in inventory (Aug 24)
- [x] Develop function UI for visualisation of items in map (Aug 24)
- [x] Be to pick up/hold items from map into inventory (Aug 25)
- [x] Be able to use items from the inventory (Aug 27)
- [x] Complete Inventory (Aug 27)
- [ ] Merge into Main (Aug 27)

**Completion Deadline:** Aug. 28

# **Documentation**
- [Inventory Wiki Page](https://github.com/UQcsse3200/2024-studio-2/wiki/Inventory)
- [Items Wiki Page](https://github.com/UQcsse3200/2024-studio-2/wiki/Items)

# **Members**
- Senuri Panadura Arachchige (s-shalomi) 
- Thomas Preston (tompreston1)
- Lewis Hickson (lhick2108)
- Mittun Sudhahar (mitsudz)
- Phong Nguyen (beannie)
