### ISSUE TITLE
Weapons

### ISSUE THREAD

**Issue by s-shalomi** [UQcsse3200/2024-studio-2#30]
# **Description**
**Task:** Create class for infinite use items (#3).
**Feature:** Items and Inventory (#2)

Create a class for infinite use items (InfiniteUse), a subclass of AbstractItem. Infinite use items can be used multiple times without depletion. They include weapons and story key items, which are essential for gameplay progression.

# **Dependencies**
- [ ] Completion of AbstractItem class (#19 )
- [ ] Create specific story key elements (Discuss with quest and progression team)
 
# **Milestones**
- [ ] Initial design (Aug. 18)
- [ ] Unit tests implemented and initial documentation on wiki (Aug. 20)
- [ ] Class implemented and tested (Aug. 24)
- [ ] Documentation created and updated on wiki (Aug. 27)
 
**Completion Deadline:** Aug. 29

# **Documentation**
TBC
 
# **Member**
- Senuri Panadura Arachchige (s-shalomi)
