### ISSUE TITLE
[Team 1] Combat Quick-Time Events

### ISSUE THREAD

**Issue by KungKemi** [UQcsse3200/2024-studio-2#304]
# **Description**
**Task:** Combat Quick-Time Events.
**Feature:** #165

Adds quick-time events to the combat system, which is a core part of the player's turn when attacking a sleeping enemy.

As the combat-system isn't expected to be finalized enough for direct integration during Sprint 2, a proof-of-concept will be developed and the logic combined with combat system in Sprint 3.

# **Dependencies**

- [ ] Dependency 1:  the combat system developed by Team 10

# **Milestones**
- [x] Step 1 (Sep. 3) Begin work on combat wiki
- [x] Step 2 (Sep. 7) Finalise the combat wiki
- [x] Step 3 (Sep. 10) Implement screen for testing feature
- [x] Step 4 (Sep. 11) Implement core quick-time events functionality
- [x] Step 5 (Sep. 11) Unit testing
 
**Completion Deadline:** Sep. 11

# **Documentation**
- [Combat System](https://github.com/UQcsse3200/2024-studio-2/wiki/Combat-System#63-player-attacks-sleeping-enemy)
 
# **Member**
- Alex Johnson (@KungKemi) (Alex)
