### ISSUE TITLE
Minigame Bugfixes

### ISSUE THREAD

**Issue by jakingy** [UQcsse3200/2024-studio-2#305]
# **Description**
**Task:** Minigame Bugfixes (#305)
**Feature:** Mini Games (#287)

This task incorporates several bugfixes to mini-games. This includes preventing the Bird from clipping into Pipes, implementing the correct functionality of the escape key and exit buttons, improved Bird Physics and writing broken/missing JUnit tests.

# **Dependencies**
- [x] Snake game complete
- [x] Birdie Dash game complete

# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix Bird clipping into Pipe (6th September)
- [x] Fix escape key to trigger pause menu in Birdie Dash (5th September)
- [x] Fix exit button in both minigames so that it works without the game being paused (6th September)
- [x] Write missing JUnit tests for the Coin/Bird class (6th September)
- [x] Improve Bird Physics (7th September)
 
**Completion Deadline:** 7th September
 
# **Documentation**
- [Birdie Dash Mini-game](https://github.com/UQcsse3200/2024-studio-2/wiki/BirdieDash-MiniGame)
- [Snake Mini-game](https://github.com/UQcsse3200/2024-studio-2/wiki/Snake-Mini%E2%80%90Game)
- [JavaDoc](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/components/minigame/snake/Snake.html)
- ...
 
# **Member**
- James (@jakingy)
