### ISSUE TITLE
5-Logbook

### ISSUE THREAD

**Issue by theboah** [UQcsse3200/2024-studio-2#314]
# **Description**
A display of all achievements achieved by a player over all plays of the game.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Initial logbook design (Aug. 20)
- [x] Achievements correctly showing basic information on logbook screen
- [x] Tab screen structure and interactive display elements.
- [x] Achievements showing detailed information on logbook screen
- [x] New item achievements
- [x] New enemy achievements
- [x] New basic achievement
- [x] New mini game achievements
- [x] New acheivement sprites for non-obvious sprite achievements
- [x] Complete all functionality
- [x] Complete basic wiki
- [x] Complete tests
- [x] Complete javadocs
**Completion Deadline:** Aug. 12

# **Documentation**
- [Logbook Achievements](https://github.com/UQcsse3200/2024-studio-2/wiki/Logbook---Achievements)

# **Members**
- Noah Stevens (@theboah) (@noahxl234) theboah
