### ISSUE TITLE
Handle Experience UI

### ISSUE THREAD

**Issue by reemmi** [UQcsse3200/2024-studio-2#32]
# **Description**
**Task:**  Experience UI Integration
**Feature:** Quests and Progression (#13) 

This task involves implementing the Experience UI for the player. The UI will display the player's current experience points (XP), the progress towards the next level, and provide feedback on levelling up. This also includes integrating the experience UI with the player team for storage and usage, ensuring that XP is correctly accumulated, displayed, and utilised in the game. Additionally, it involves integrating the experience system with the combat team to adjust XP gains based on combat outcomes. 

# **Dependencies**

- [ ] Label and experience indicators need to be generated 
- [ ] Combat System needs to be implemented (discuss with combat team)
- [ ] Player XP system needs to be implemented (discuss with player team) 

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Initial UI design of experience created and documented on wiki (Aug. 19).
- [ ] Integration with Player Team (Aug 20)
- [ ] Combat Integration (Aug 24) 
- [ ] Documentation Update (Aug 27) 
 
**Completion Deadline:** Aug. 29

 
# **Documentation**
TBD
 
# **Member**
- Reemzheem Hossain (@reemmi)
