### ISSUE TITLE
Friendly NPC's Quest Integration 

### ISSUE THREAD

**Issue by reemmi** [UQcsse3200/2024-studio-2#321]
# **Description**
**Task:** [NPC Quest Integration](#3).
**Feature:** [[Team 4] Friendly NPC Interaction Update and Extensions](#326)

This task involves integrating NPCs into the quest system so that each NPC provides context-specific dialogue and guidance to help players navigate and complete levels or kingdoms. The NPCs will deliver fixed hints at key moments during the quest, offering guidance on objectives and next steps. Each NPC's dialogue will be carefully scripted to align with the quest's progression. 
 
# **Dependencies**
- [x] QuestManager (#xx)
- [x]  FNPCs which provide hints and the dialogue box are ready for production. 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Finalise and document NPC dialogue scripts and hints in the correct format. (Sep. 30)
- [x] Implement dialogue triggers for each NPC based on quest progression. (Sep. 30)
- [x] Integrate quest dialogue with Friendly NPC. (Sep. 30)
- [x] Conduct thorough testing. (Sep. 30)
- [x] Incorporrate loading and saving (Sep 30)
- [ ] Update documentation (Sep. 30)
 
**Completion Deadline:** Oct 1

# **Documentation**
- [Quests](https://github.com/UQcsse3200/2024-studio-2/wiki/Quests)
- [Friendly NPC's](https://github.com/UQcsse3200/2024-studio-2/wiki/Friendly-NPCs)
 
# **Member**
- Reemzheem (@reemmi) 
- Bailey (@BaileyS03)
