### ISSUE TITLE
[Team 3] Item/Inventory Sprint 3 features

### ISSUE THREAD

**Issue by PHONGNGYUEN1** [UQcsse3200/2024-studio-2#322]
# **Description**
This feature includes an improved system for the players to interact with the inventory with a filtering system and updating the inventory after items are used. Additional features such as allowing users to interact with the inventory mid fight will be introduced.

## SubFeature/component 
- #343 
- #215  
- #373
- #216 
- #357
- #398 
- #451 
- #356 
- #428 
- #447 

## **Examples (optional)**
- **Invtory in Combat**: Players can access inventory in combat to use items. Using items in combat will be considered a combat move
- **Updated logic in timedUsedItems**: if a defence potion were used outside of combat, it would prevent and notify the user that it can only be accessible to combat. When used in combat the effects will last until combat ends then it will revert to its original stats when returning to the main game.
- **Fog gates**: To cover unlocked maps the fog tiling will act as the gate until player has passed the requirements to access the other areas of the map 

# **Dependencies**

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Change tiemdusedItemlogic to turnbase (Sep. 20)
- [x] Toggle inventory in Combat (Sep. 28)
- [x] Make use item a combat move (Sep. 28)
- [x] Implement prevention of items being used in certain environments (Sep. 20)
- [x] Implement Fog gate tiling in maps (Sep. 27)
- [x] Fix bug with physics destroy body (Oct, 1)
- [x] Apply sorting functionality to inventory (Sep. 25)
- [x] Implement Drag and drop functionality in inventory (Sep. 26)

**Completion Deadline:** Oct. 2

# **Documentation**
- [Items](Items)
- [CombatActions](CombatActions)
- [CombatScreen](CombatScreen)

# **Members**
- Name (Github) (Discord)
- Phong Nguyen (@PHONGNGYUEN1) (@beannie)
- Mittun Sudhahar (@mitsudz ) (@mitsudz)

**Comment by PHONGNGYUEN1** [comment]
Sprint 3 and feature ticket finished
