### ISSUE TITLE
[Team 5] Quests & Saves

### ISSUE THREAD

**Issue by MargoCode** [UQcsse3200/2024-studio-2#323]
# **Description**
In the upcoming sprint, our team will work on fully integrating quests into the game, including main and side quests for each biome. This will enhance gameplay by adding an extra layer of depth, as players will experience a more immersive and diverse range of challenges. Quests will be interconnected with other gameplay elements such as NPC interactions, enemy encounters, and minigames, creating a cohesive and dynamic environment. Additionally, we will integrate the saving and loading system across all teams, ensuring that player progress is consistently tracked and maintained. Minor bug fixes and display issue corrections will also be addressed to improve the overall user experience. 

# **Dependencies**

[NPC Quest Integration](https://github.com/UQcsse3200/2024-studio-2/issues/321) #321
[Save Integration](https://github.com/UQcsse3200/2024-studio-2/issues/115) #115

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Fix item collection test integration with saved quests (Sept. 15)
- [x] Create design for main quests for the water and sky biomes (Sept. 16)
- [x] Integrate quest dialogue with friendly NPC team (Sept. 22)
- [x] Setup NPC dialogue quest listeners (Sept. 27)
- [x] Talk to items and map team to spawn quest items (Sept 28)
- [x] Setup main biome quests (Sept 28) 
- [x] Setup side biome quests (Sept 29)
- [x] Get saving and loading implemented with other teams (Oct 1st)
- [x] Get documentation completed (Oct 1st)

**Completion Deadline:** Oct 3rd

# **Documentation**
- [Quests Description] (https://github.com/UQcsse3200/2024-studio-2/wiki/Quests)
- [Overlays Description] (https://github.com/UQcsse3200/2024-studio-2/wiki/Overlays)
- [Game State Saves] (https://github.com/UQcsse3200/2024-studio-2/wiki/Game-State-Saves)
- [Event Service] (https://github.com/UQcsse3200/2024-studio-2/wiki/Eventservice)

# **Members**
- Reemzheem Hossain (@reemmi) 
- Noah Stevens (@theboah)
- Lachlan (@lellis0406)
- Jaden (@jaden-z-fng)
- Maree (@MargoCode)
