### ISSUE TITLE
[Team 4] Friendly NPC Interaction Update and Extensions

### ISSUE THREAD

**Issue by Jul-Wong** [UQcsse3200/2024-studio-2#326]
# **Description**
In this sprint, our team will work on fully implementing the updated hint system to all friendly NPCs. We will also introduce the entity conversion of enemy NPCs to friendly NPCs which will be implemented properly as it could not be completed due to dependencies. The dialogue box will also be looked at to fix the bug when resizing during the game, and more visually pleasing options for the dialogue options. Additionally, another new feature of dropping items after talking to some entities will be introduced

## SubFeatures
- Implement working entityConverter with working functionality after dependencies
- Combine all friendly NPC atlas files into one for faster loading times
- Introduce new NPCs when required
- Implement hint system for all existing NPCs and future-created
- Fix dialogue box issue with resizing
- Change how chat options are presented to be more visually pleasing and take up less clutter
- Outline NPC that is player is interacting with.
- Assign priorities for each type of the dialogues to decide which one to be prioritised to be shown.
- Drop Sushi when finishing dialogue with a fish 60% of the time and a Milk Bucket with a cow 100% of the time

# **Dependencies**
- Team 10 Combat for entity conversion 
- Team 5 for Quest Manager Implementation

# **Milestones**
- [x] Implemented entity conversion
- [x] NPC Back End Updates
- [x] Dialogue Box Bug Fix (#336)
- [x] Outline NPC that the Player is Interacting with (#397)
- [x] Atlas' Optimisations (#396)
- [x] Integration with QuestManger (Hint System) (#321)
- [x] Assign priorities for the dialogues
- [x] Introduce Sushi and Milk Bucket Items (#443)
- [x] Update Testing (#457)

**Completion Deadline:** Oct 4

# **Documentation**
- [Food Items](https://github.com/UQcsse3200/2024-studio-2/wiki/Food-Items)
- [Dialogue Box Resizing and Input](https://github.com/UQcsse3200/2024-studio-2/wiki/Dialogue-Box)
- [Keyboard Dialogue Box Input Component Testing](https://github.com/UQcsse3200/2024-studio-2/wiki/Keyboard-Dialogue-Box-Input-Component-Testing-Plan)

# **Members**
- Julian Wong (@Jul-Wong)
- Bailey Stoodley (@BaileyS03)
- Shubh Gupta (@shubhgupta2510)
- Nahin Khan (@nreyana)
- Hyunmin Cho (@eftg1000)
