### ISSUE TITLE
[Team 2] Special Interaction for Bear Enemy NPCs

### ISSUE THREAD

**Issue by nownver** [UQcsse3200/2024-studio-2#327]
# **Description**
**Task:** [Special Interaction for Bear Enemy NPCs](https://github.com/UQcsse3200/2024-studio-2/issues/327 )
**Feature:** [Enemy NPCs Special Interaction Feature](https://github.com/UQcsse3200/2024-studio-2/issues/324 )

Implement a special interaction for Bear enemy NPCs that will prevent them from attacking if the player remains stationary within a certain proximity. This feature aims to add a unique behavioral trait to Bear NPCs, influencing how player approach encounters with them.

# **Dependencies**

- (#283 )
- (#179 )

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Define the logic for detecting if the player is stationary. (Sep. 14)
- [x] Develop and integrate the logic into the bear Enemy NPC behavior. (Sep. 15)
- [x] Integration of animation and texture into the game (Sep. 16)
- [x] Testing and adjustments (Sep. 17)

**Completion Deadline:** Sep. 17
 
# **Documentation**
**TODO**
 
# **Member**
- Jade (@nownver) (Urawee Thani)
