### ISSUE TITLE
[Team 2] Add a BigSawfish Enemy NPC

### ISSUE THREAD

**Issue by nownver** [UQcsse3200/2024-studio-2#328]
# **Description**
**Task:** [Implementing a Piranha enemy NPCs](https://github.com/UQcsse3200/2024-studio-2/issues/328 )
**Feature:** [Enemy NPCs Special Interaction Feature](https://github.com/UQcsse3200/2024-studio-2/issues/324 )

Introduce a new enemy NPC, the Piranha, to the underwater area of the game. This task involves designing the Big sawfish, implementing its behavior and special interaction before enter combat, and integrating it into the underwater environment game area.

# **Dependencies**
- (#179 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Find Appropriate PNG and write atlas file (Sep. 15)
- [x] Implement a visible entity, with ability to chase (Sep. 15)
- [x] Implement animations, different animations for chasing and floating (Sep. 18)
- [x] Integration of animation and texture into the game (Sep. 19)
- [x] Testing and adjustments (Sep. 20)
 
**Completion Deadline:** Sep. 20
 
# **Documentation**
[**Big sawfish Enemy NPC**](https://github.com/UQcsse3200/2024-studio-2/wiki/Big-sawfish-(Enemy-NPC))
 
# **Member**
- Jade (@nownver) (Urawee Thani)
