### ISSUE TITLE
[Team 9] Special Interaction for Bosses

### ISSUE THREAD

**Issue by phurinjeffy** [UQcsse3200/2024-studio-2#329]
# **Description**
**Task:** [Special Interaction for Bosses](../issues/329)
**Feature:** [[Team 9] Boss](../issues/325)

Implement a special interaction for Boss enemy type NPCs, which aims to add a unique behavioural trait to the Bosses, influencing how player approach encounters with them outside of combat.

For Land Area boss (Kanga), the special interaction will be for the Kanga to spawn little joey enemy mobs, which will rush towards you and initiate combat.

For Water Area boss (Leviathan), the special interaction will be for the Leviathan, when outside of chasing, to shoot out water stream towards the player which causes damage.

For Air Area boss (Griffin), the special interaction will be for the Griffin to run away from player (opposite of chase), and a gust of wind follows behind damaging the player if hit.

# **Dependencies**
- #330
- #331
- #332

# **Milestones**
### Land Area
- [x] Design special interaction fo Kanga boss
- [x] Implement special interaction for Kanga boss
### Water Area
- [x] Design special interaction for Leviathan boss
- [x] Implement special interaction for Leviathan boss
### Air Area
- [x] Design special interaction for Griffin boss
- [x] Implement special interaction for Griffin boss
### Tests
- [x] Testing and documenting (Oct. 4)
 
**Completion Deadline:** Oct. 4
 
# **Documentation**
- [Special Interaction for Land Boss](../wiki/Special-Interaction-for-Land-Boss)
- [Special Interaction for Water Boss](../wiki/Special-Interaction-for-Water-Boss)
- [Special Interaction for Air Boss](../wiki/Special-Interaction-for-Air-Boss)
 
# **Member**
- Phurin Vanasrivilai (phurinjeffy)
