### ISSUE TITLE
[Team 9] Boss Animations - LAND

### ISSUE THREAD

**Issue by phurinjeffy** [UQcsse3200/2024-studio-2#330]
# **Description**
**Task:** [Boss Animations - LAND](../issues/330)
**Feature:** [[Team 9] Boss](../issues/325)

Design and implement the animations for the LAND boss (Kanga). 
Create in BossFactory class the methods used for creating the boss entities and also spawning logic.

# **Milestones**
### Animations
- [x] Design animation for LAND area boss (Kanga)
- [x] Implement animation for LAND area boss (Kanga)
### Entity
- [x] Create methods in BossFactory to spawn the boss entity.
- [x] Add appropriate trigger/listener to spawn the boss in game.
### Tests
- [x] Testing and documenting (Oct. 4)
 
**Completion Deadline:** Oct. 4
 
# **Documentation**
- [Animations for Land Boss](../wiki/Animations-for-Land-Boss)
 
# **Member**
- Jiatong Wang (ArthurW4130)
- Phurin Vanasrivilai (phurinjeffy)
