### ISSUE TITLE
[Team 9] Boss Animations - WATER

### ISSUE THREAD

**Issue by phurinjeffy** [UQcsse3200/2024-studio-2#331]
# **Description**
**Task:** [Boss Animations - WATER](../issues/331)
**Feature:** [[Team 9] Boss](../issues/325)

Design and implement the animations for the WATER boss (Leviathan).
Create in BossFactory class the methods used for creating the boss entities and also spawning logic.

# **Milestones**
### Water Area
- [x] Design animation for WATER area boss (Leviathan)
- [x] Implement animation for WATER area boss (Leviathan)
### Entity
- [x] Create methods in BossFactory to spawn the boss entity.
- [x] Add appropriate trigger/listener to spawn the boss in game.
### Tests
- [x] Testing and documenting (Oct. 4)
 
**Completion Deadline:** Oct. 4
 
# **Documentation**
- [Animations for Water Boss](../wiki/Animations-for-Water-Boss)
 
# **Member**
- Ajay Datt (Ajay-Datt)
- Phurin Vanasrivilai (phurinjeffy)
