### ISSUE TITLE
[Team 9] Boss Animations - AIR

### ISSUE THREAD

**Issue by phurinjeffy** [UQcsse3200/2024-studio-2#332]
# **Description**
**Task:** [Boss Animations - AIR](../issues/332)
**Feature:** [[Team 9] Boss](../issues/325)

Design and implement the animations for the AIR boss (Griffin).
Create in BossFactory class the methods used for creating the boss entities and also spawning logic.

# **Milestones**
### Air Area
- [x] Design animation for AIR area boss (Griffin)
- [x] Implement animation for AIR area boss (Griffin)
### Entity
- [x] Create methods in BossFactory to spawn the boss entity.
- [x] Add appropriate trigger/listener to spawn the boss in game.
### Tests
- [x] Testing and documenting (Oct. 4)
 
**Completion Deadline:** Oct. 4
 
# **Documentation**
- [Animations for Air Boss](../wiki/Animations-for-Air-Boss)
 
# **Member**
- Jose Leoncio (reonse)
- Phurin Vanasrivilai (phurinjeffy)
