### ISSUE TITLE
[Team 7] Underwater Maze Mini-Game

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#333]
# **Description**
This is a feature ticket for the last mini-game the underwater maze. This mini-game is for the underwater kingdom. A big tide has come through and spread out all the fish eggs and the fish ahs become lost. You must help the fish collect all the fish eggs and navigate its way back home. But it is dark and you must make sure not to run into any sharks. Score will be determined based on the number of fish eggs collected. The player will have to navigate a fish through a maze with limited visibility trying to collect all the fish eggs while avoiding enemy NPCs.

The angular fish NPC will be chasing the player throughout the games duration. If the player runs into the angular fish. they will take some damage to their health. There is also 2 variations of jellyfish wondering thoughout the maze, If hte player toutches a jelly fish they will also take damage. FInally there is also an Eel, the eel is chasing the player, the player will not take damage from the Eel but instead this will create a stunn effect which will light up the entire maze. 

The mini-game must be completed befor the player can enter a boss fight. The minigame enhances the game as it gives the player something fun to do. The implementation of a medal system and rewards means that the user has an incentive to play the mini-game. 

## SubFeature/component (optional)
Maze
- [x] Maze design and rendering (#378)
- [x] Add to fish npc (#377)
- [x] sight radius and shader (#418)

NPC's
- [x] Angular fish (#413)
- [x] Player (#419)
- [x] maze collision detection (#417)
- [x] Health (#416)
- [x] Fish eggs (#368)
- [x] Path finidng (#414)
- [x] Eels (#415)
- [x] Jelly fish (#411)

Game
- [x] Score (#439)
- [x] Game termination (#442)
- [x] High score/ medal saving (#405)
- [x] JUnit testing (#371)
- [x] Mini-Game Sound Effects and Background Music #492
- [x] Birdie Dash Mini-Game Rendering and Background Improvements #494
- [x] Mini-Game Maze Dynamic Difficulty Increase #497

# **Dependencies**
- Fish npc #253

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Maze rendering with fish movement (Sept. 16)
- [x] Vision, all entities, scoreboard, game termination and end game screen, player (Sept. 26)
- [x] Score, end game screen fixes, highscore and medal saving (Oct. 1)

**Completion Deadline:** Oct. 1

# **Extras (optional)**

![image](https://github.com/user-attachments/assets/adf21ed7-bb6d-472a-9473-79c630877f18)

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)

# **Members**
James King
@[jakingy](https://github.com/jakingy)
jakingy

Nathan Chung
@[0NATE4](https://github.com/0NATE4)
0NATE4

Manandeep Singh
@[24msingh24](https://github.com/24msingh24)
24msingh24

Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas

Rajanya Paul Choudhury
@[rp3002](https://github.com/rp3002)
rp3002
