### ISSUE TITLE
[Team 10] Combat Enhancements: UI, Animations, Items, and Multi-Attack

### ISSUE THREAD

**Issue by owenrharding** [UQcsse3200/2024-studio-2#334]
# **Description**
Our team will enhance the combat system by adding dialog boxes that describe actions during combat and pop-up descriptions when hovering over buttons. We'll collaborate with Team 3 to integrate inventory and with Team 1 to implement multi-attack functionality. We'll also add animations for attacking, guarding, sleeping, and idle states for both players and enemies. Additionally, we'll explore adding audio for button presses and keybinds for attacks if we get time. These updates will improve clarity, player feedback, and overall immersion in the combat experience.

# **Dependencies**
- [x] Multi-attack functionality for integration onto combat screen (#304)
- [x] Items & inventory functionality for integration onto combat screen (#157)

# **Milestones**
- [x] Combat Animations (Sep. 30) 
    - #340 
    - Combat Move Animations (#366)
- [x] Dialogue Boxes Detailing Combat (#338)
- [x] Dialogue Boxes Detailing Results (Post-Combat) (#389)
- [x] Button hover pop-ups (#367)
- [x] Button Hiding & Showing (#339)
- [ ] Multi-attack integration (#349)
- [x] Items & inventory integration (#343)
- [x] Combat logic to handle special move status effects (#395)

**Completion Deadline:** Oct. 3

# **Extras**
- [ ] Audio & sounds for different moves/button clicks etc.
- [ ] Keybinds for buttons/features on the screen

# **Documentation**
- [CombatInventoryDisplay](../wiki/CombatInventoryDisplay) 
- [CombatAnimationDisplay](../wiki/Combat-Animations) 

# **Members**
- Owen Harding (@owenrharding on GitHub) (owen8232 on Discord)
- Jonah Ting (@Jaycoba1 on GitHub) (Jaycoba1 on Discord)
- Yessica Samtani (@yessica-s on GitHub) (yessica3301 on Discord)
- Peeranat Leelawattanapanit (@paulpleela on GitHub) (pa._.l on Discord)
- Sneha Zazen Theruvile Sajan (@sneha-zazen on GitHub) (zaza7_13 on Discord)
- Christian Almario (@ChristianMario4 on Github) (CAllMario101 on Discord)
