### ISSUE TITLE
[Team 4] DialogueBox Bug Fixes

### ISSUE THREAD

**Issue by BaileyS03** [UQcsse3200/2024-studio-2#336]
# **Description**
**Task:** DialogueBox Bug Fixes.
**Feature:** [Team 4] Friendly NPC Interaction Update and Extensions #326

This task ticket entails fixing some bugs identified by the studio including issues with game ticks and displaying the game, resizing of the dialogue box, and other issues that peers may present. 

# **Dependencies**
There are no dependencies as these are bug fixes. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix issue surrounding dialogue box disappearing & not returning on a specific tick (Sep 14)
- [x] Fix resizing (Sep 14)
- [x] Document testing for resizing (Sep 14)
- [ ] Added key bindings for left and right arrow for the Dialogue Box (Sep 14)
- [ ] Testing for ket bindings regarding the above (Sep 14)
 
**Completion Deadline:** September. 20
 
# **Documentation**
- [DialogueBoxTesting](../wiki/Dialogue-Box-Service-Testing)
 
# **Member**
- e.g. Bailey (@BaileyS03) (Bailey Stoodley)
