### ISSUE TITLE
[Team 10] Implement Displaying of Queued Actions in Combat Screen

### ISSUE THREAD

**Issue by ChristianMario4** [UQcsse3200/2024-studio-2#338]
# **Description**
**Task:** [Implement Displaying of Queued Actions in Combat Screen].
**Feature:** [Combat Enhancements: UI, Animations, Items, and Multi-Attack](#334)

During combat, a DialogBox will appear on screen after the player has selected a move. This DialogBox describes the actions that have been made during this turn of combat by both the player and enemy. It will make use of the ChatEntityService, This DialogBox will appear at the bottom of the screen, replacing where the buttons used to be.

## **Example**
- When a player selects a move, after all the combat logic has been completed and the appropriate stats have been changed, the buttons on the screen will temporarily be replaced by a DialogueBox displaying the moves that have been made by both the player and enemy, and their relative status changes. If a multi-hit attack is involved, it will list out the number of attacks made. If a critical attack was involved where one entity is sleeping and another attacks, it will also be displayed.

# **Dependencies**
- [x]  Combat Logic Framework (#171)
- [ ] Item Integration into Combat Screen (#343)
- [ ] Multi-Attack Integration into Combat Screen (#349)
- [x] Implementing Temporary Removal of Combat Buttons (#339)

 
# **Milestones**
- [x] Learn Implementation of DialogueBox Currently in Game (Sep. 16)
- [x] Learn Implementation of CombatLogicFramework and How to Extract This Info (Sep 18.)
- [x] Get a DialogueBox (with next and skip buttons) to Appear in the Combat Screen (Sep 19.)
- [x] Get Actions to Be Listed On DialogBox Combat Screen (Sep 20.)
- [x] Integrate Button Removal with the Appearance of the Combat Buttons (Sep 24.)
- [ ] Complete Testing (Visual and Unit) for Combat DialogueBox (Sep 25.)
- [ ] Complete Wiki for Combat DialogueBox (Sep 27.)
 
**Completion Deadline:** Sep. 27

 
# **Documentation**
- [Displaying Combat Actions in DialogueBox on Combat Screen](https://github.com/UQcsse3200/2024-studio-2/wiki/Combat-Action-Display)
 
# **Member**
- Christian Almario (@ChristianMario4 on Github) (CAllMario101 on Discord)
