### ISSUE TITLE
[Team 10] Implement Removal and Re-Appearance of Combat Buttons in Combat Screen

### ISSUE THREAD

**Issue by ChristianMario4** [UQcsse3200/2024-studio-2#339]
# **Description**
**Task:** [Implement Removal and Re-Appearance of Combat Buttons in Combat Screen].
**Feature:** [Combat Enhancements: UI, Animations, Items, and Multi-Attack](#334)

When the DialogueBox describing queued actions and associated effects appears on the screen, the Combat buttons on the screen currently should disappear, and once the DialogueBox appears again, reappears. 
 
## **Example**
- **Player Attacks** - When the player clicks attacks, the player and enemy stats will update. This is followed by the buttons disappearing, then the appearance of the dialogue box, then after all the text is complete, the Dialogue Box disappears and the combat buttons reappear.

# **Dependencies**
- [x] Implementing Displaying of Queued Items on the Combat Screen (#338)
- [x] Implementing Action Buttons in Combat Screen (#174) 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Understand Current Implementation of Buttons (Sep 18.)
- [x] Implement Removal of Buttons from Screen (Sep 19)
- [x] Integrate Button Removal with the Appearance of the Combat Buttons (Sep 24.)
- [x]  Complete Testing (Visual and Unit) for Combat DialogueBox (Sep 25.)
- [x] Complete Wiki for Combat DialogueBox (Sep 27.)
 
**Completion Deadline:** Sep 27.
 
# **Documentation**
- [Displaying Combat Actions in DialogueBox on Combat Screen](https://github.com/UQcsse3200/2024-studio-2/wiki/Combat-Action-Display)
 
# **Member**
- Christian Almario (@ChristianMario4 on Github) (CAllMario101 on Discord)
