### ISSUE TITLE
Dynamic Player Camera

### ISSUE THREAD

**Issue by KungKemi** [UQcsse3200/2024-studio-2#34]
# **Description**
**Task:** Dynamic Player Cam.
**Feature:** #4

Currently the game camera only focuses on a single area of the map and doesn't update when the player moves around. This is a problem as it is expected that the map will be too large to completely display on the screen at one time. To remedy this, the game camera will be modified so that it follows the player as they move around the world. In doing so, the visible areas of the map will be updated depending on which direction the player moves in. The player should be focused in the center of the screen at all times except maybe when the player reaches the boundary of the map. (This will depend on whether or not the size of the playable area is smaller than the size of the rendered map.)

As part of this feature, there should be added functionality to enable zooming the camera in and out so that less or more of the map area is shown on the screen, respectively. The zoom can be toggled by using the scroll wheel on the mouse.
 
## **Example**
- **Vampire Survivors**: this game provides a good example of how the player camera will behave (see [here](https://store.steampowered.com/app/1794680/Vampire_Survivors/)).

# **Dependencies**

- Dependency 1: depending on how the map #8 is designed, the camera may have to behave differently when the player gets close to the map border.

# **Milestones**

- [ ] Camera follows the player character around the map (Aug. 19)
- [ ] Camera stops when the player reaches the map border (Aug. 20)
- [ ] Camera can be zoomed in or out (Aug. 20)
 
**Completion Deadline:** Aug. 20
 
# **Documentation**
To be completed
 
# **Member**
- Alex Johnson (@KungKemi) (Discord Handle: KungKemi)
