### ISSUE TITLE
[Team 10] Enemy Animations in the Combat Screen

### ISSUE THREAD

**Issue by paulpleela** [UQcsse3200/2024-studio-2#340]
# **Description**
**Task:** [Enemy Animations in the Combat Screen](../issues/340)
**Feature:** [Combat Enhancements: UI, Animations, Items, and Multi-Attack](../issues/334)

Implementing character animations for Enemy entities in the Combat Screen. This includes Enemy Idle animations (the same as idle animations in the Main Game Screen), and a Move animation (such as a jump) that will be displayed when the Enemy performs one of the combat moves (i.e. during combat Attack, Guard, Sleep, or Special animations).
 
# **Dependencies**
- **Idle animation sprites for Enemy NPCs from the Main Game Screen**
    - #83 
    - #283 
    - #328 
    - _Other Enemy NPCs can be added progressively to the Combat Screen_

# **Milestones**
- [x] Create a separate animation controller for entities in the Combat Screen (Sep. 26)
- [x] Create a separate entity factory for displayed entities in the Combat Screen (Sep. 27) 
- [x] Add logic to allow different animal combat animations to be triggered from the Combat Manager (Sep. 29)
- [x] Find/create appropriate sprites _(or use one provided by the Enemy Team)_ for Idle and Move animations that follow the style of the current Chicken NPC. (Sep. 30)
- [x] Update atlas file of the Chicken to include `combat_idle` and `combat_move`. (Sep. 30)
- [x] Add the animations to the `AnimationRenderComponent` of the combat Chicken. (Sep. 30)
- [x] Add animations for other Enemy NPCs in Combat Screen, as they are progressively added to Main Game Screen (Oct. 2)
    - [x] Frog
    - [x] Monkey
    - [x] Bear
    - [x] Bee
    - [x] Big Sawfish
    - [x] Eel
    - [x] Macaw
    - [x] Pigeon
- [x] Adjustments and testing. (Oct. 2)
 
**Completion Deadline:** Oct. 2

# **Documentation**
[Enemy NPCs](../wiki/Enemy-NPC's)
[Entity Animations](../wiki/Animations)
 
# **Member**
- Peeranat Leelawattanapanit (@paulpleela on GitHub) (pa._.l on Discord)
- Urawee Thani (@nownver on GitHub) (happy_tt on Discord)
- Jonah Ting (@Jaycoba1 on GitHub) (Jaycoba1 on Discord)
