### ISSUE TITLE
[Team 9 & 10] Boss Animations in the Combat Screen

### ISSUE THREAD

**Issue by paulpleela** [UQcsse3200/2024-studio-2#342]
# **Description**
**Task:** [Boss Animations in the Combat Screen](../issues/342)
**Feature:** [Combat Enhancements: UI, Animations, Items, and Multi-Attack](../issues/334)

Implementing character animations for Boss entities in the Combat Screen. This includes Boss Idle animations (the same as idle animations in the Main Game Screen), and a Move animation (such as a jump) that will be displayed when the Boss performs one of the combat moves (i.e. during combat Attack, Guard, Sleep, or Special animations).
 
# **Dependencies**
- [x] **Idle animation sprites for Boss NPCs from the Main Game Screen**
   - [x] #330 
   - [x] #331 
   - [x] #332 
- [x] Triggering combat animations from the Combat Manager. Implemented `CombatAnimalFactory`, `CombatAnimationController` (#340) 

# **Milestones**
- [x] Find/create appropriate sprites _(or use one provided by the Final Boss Team)_ for Idle and Move animations that follow the style of the Kanga's (Land Boss) animations. (Sep. 30)
- [x] Update atlas file of Kanga Boss to include `combat_idle` and `combat_move`. (Oct. 1)
- [x] Add the animations to the `AnimationRenderComponent` of the combat Kanga Boss. (Oct. 1)
- [x] Add animations for other Bosses in Combat Screen, as they are progressively added to Main Game Screen. (Oct. 2)
    - [x] Water Boss
    - [x] Air Boss
- [x] Adjustments and testing. (Oct. 3)
 
**Completion Deadline:** Oct. 3

# **Documentation**
[Animations for Land Boss](../wiki/Animations-for-Land-Boss)
[Animations for Water Boss](../wiki/Animations-for-Water-Boss)
[Animations for Air Boss](../wiki/Animations-for-Air-Boss)
[Entity Animations](../wiki/Animations)
 
# **Member**
- Peeranat Leelawattanapanit (@paulpleela on GitHub) (pa._.l on Discord)
- Phurin Vanasrivilai (@phurinjeffy on GitHub) (jeff. on Discord)
