### ISSUE TITLE
Allow Inventory Access During Combat

### ISSUE THREAD

**Issue by PHONGNGYUEN1** [UQcsse3200/2024-studio-2#343]
# **Description**
**Task:** [Allow Inventory Access During Combat](#3).
**Feature:** (#322 )

During Combats, players can access inventory to use items to increase their health, and hunger or improve their combat stats to assist them in their fight. This idea is only useful to the player's chances of winning if the player has collected the necessary items before entering combat.
 
## **Example (optional)**
- **Health Increase**: The player's health is low and needs to be healed instantly before the enemy can deplete their health completely. If the player has existing items to increase their health they can use it and will be able to defeat the enemy.

# **Dependencies**
- 

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Connect Inventory display to combat item button (Aug. 24)
- [ ] Create a task to handle game pause when inventory is opened in combat (Aug. 25)
- [ ] only allow defence and attack potions to be used during combat not on map
- [ ] Update dialogue for items that cannot be used in certain game areas
- [ ] Item used in combat is considered a turn
 
# **Documentation**
- TO DO

 
# **Member**
- Name Phong Nguyen (@PHONGNGYUEN1) (beannie)
- Thomas Preston (@tompreston1) `tom152738379`
