### ISSUE TITLE
[Team 10] Inventory & Items in Combat

### ISSUE THREAD

**Issue by owenrharding** [UQcsse3200/2024-studio-2#344]
# **Description**
**Associated Feature:** [Combat Enhancements: UI, Animations, Items, and Multi-Attack](#334)

Integrate inventory into combat screen so that items can be used during combat. Item use will be different in combat than in the overworld, where only one item can be used per turn, and the item use is delayed (not immediate) as sequenced by the combat manager. The overlay will be triggered by a button press, allowing the player to see and use available items. The goal is to enhance player interaction by providing a seamless item-use experience during battles.

# **Dependencies**
- [x] Items & inventory functionality (already completed) (#3)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Correctly initialise overlay in combat screen (either use the same one from main game or create a copy) (Sep 18)
- [x] Link overlay appearing/hiding to 'items' button (Sep 21)
- [x] Develop logic so that only one item can be used per turn (Sep 22)
- [x] Integrate items use into combat manager & sequencing (Sep 23)
- [ ] Develop unit testing on item use in combat (Sep 26)
- [ ] Develop UI to indicate items use (Sep 29)
- [ ] Complete visual testing on inventory & items use (Sep 30)
- [ ] Document inventory & items in combat on wiki (Oct 1)
 
**Completion Deadline:** Oct 2
 
# **Documentation**
 
# **Member**
- Owen Harding (@owenrharding on GitHub) (owen8232 on Discord)
