### ISSUE TITLE
Adding interactive animal to main menu screen

### ISSUE THREAD

**Issue by ishusharma13** [UQcsse3200/2024-studio-2#346]
# **Description**
**Task:** Interactive animal to main menu screen 
**Feature:** Interactive main menu

Interactive animal character, such as an owl, that players can click on. When clicked, the animal will generate and display a random fun fact on the screen, adding an element of surprise and curiosity. At the same time, a sound will play, enhancing the experience and making the interaction more engaging. This feature will make the menu more dynamic and add a fun, interactive touch that players will enjoy exploring.
 
## **Example (optional)**
- If you click on the owl it will generate random facts about animals in the game and create a sound.

# **Dependencies**

- [x] The animal needs to align with the screen UI

 
# **Milestones**
- [x]  Design and Place the Animal (Sept 20)
- [x] Creating a array of random facts (Sept 23)
- [x] Creating sound for the animal (Sept 26)
- [x] Displaying the facts (Sept 27)
- [ ] Documentation (Sept 30)
 
# **Documentation**
 To be uploaded

# **Member**
- Ishu (@ishusharma13 ) (discord-@ishusharrma)
