### ISSUE TITLE
Create Indication for Temporary Items in use

### ISSUE THREAD

**Issue by PHONGNGYUEN1** [UQcsse3200/2024-studio-2#348]
# **Description**
**Task:** [Create Indication for Temporary Items in use].
**Feature:** [#322]

When a player uses an item there will be an indication of the item being used through a mini-box display which will show the items in use. The item in the box will disappear once item is finished its duration.
 
## **Example (optional)**
- **Using Speed Potion**: The player decides to use the speed potion once the speed potion is in use they speed potion item will appear in the small box indicating it is in use. After two minutes game time has passed the item will disappear from the box indicating the effect is finished.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] create box (Sep 16)
- [ ] connect box to items in use (create handler or add on to useitemtask) (Sep 17)
- [ ] remove item once finished (Sep 18)
 
**Completion Deadline:** Sep 20.

# **Documentation**
- TO DO
 
# **Member**
- Phong Nguyen (@PHONGNGYUEN1 ) (beannie)
