### ISSUE TITLE
[Team 10] Integrate Quick-Time-Events to Combat moves 

### ISSUE THREAD

**Issue by sneha-zazen** [UQcsse3200/2024-studio-2#349]
# **Description**
**Task:** [Integrate Quick-Time-Events to Combat moves ](#3).
**Feature:** [Combat Enhancements: UI, Animations, Items, and Multi-Attack](#334)

When the player clicks on 'Attack' while the enemy is sleeping, a series of quick-time events are triggered. These quick-time events score will determine the number of hits the player can land on the sleeping enemy. The success of the quick-time events is based on the player pressing the correct key within a specific time frame. Each successful keypress increases the number of attacks, with a maximum of 4 hits. The damage for each hit follows the standard attack formula.

# **Dependencies**

- [x] Quick-time event framework implementation (#303)
- [x] Implementation of sleep and attack in combat system (#188 )
- [x] Balancing damage formula for multi-hits during Sleep (#171)

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add logic to check if the enemy is sleeping when the player initiates an attack (Sep. 16).
- [x] Extend quick-time event logic to handle different key presses (Sep. 17)
- [x] Trigger QTE system when the player attacks a sleeping enemy, ensuring the correct sequence starts (Sep. 17).
- [ ] Fetch the score from the QTE and calculate the number of successful hits (Sep. 17).
- [ ] Pass the number of hits to the AttackMove (Sep. 17).
- [x] Improve animation for quick-time events (Sep. 19)
- [ ] Final testing and bug fixing to ensure proper integration with combat moves and enemy AI (Sep. 20).
 
**Completion Deadline:**  (Sep. 28).

# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2024-studio-2/wiki/Combat-System)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Sneha Zazen (@sneha-zazen )
- Alex Johnson (@KungKemi )

**Comment by sneha-zazen** [comment]
https://github.com/UQcsse3200/2024-studio-2/wiki/Quick-Time-Event-User-Tests
