### ISSUE TITLE
Update items spawning on map

### ISSUE THREAD

**Issue by PHONGNGYUEN1** [UQcsse3200/2024-studio-2#350]
# **Description**
**Task:** [Update items spawning on map](#3).
**Feature:** [#322 ]

Update how the items will be implemented including removing the physical component of the items and changing the item placement statically instead of randomly 

# **Milestones**
List of steps that need to be completed for this task.
- [ ] TODO
 
**Completion Deadline:** Sep. 18

e.g.
- [ ] Initial design of `Armour` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- TO DO 
-
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
