### ISSUE TITLE
[Team 10] QuickTimeEvent score is effective on Attack in combat 

### ISSUE THREAD

**Issue by sneha-zazen** [UQcsse3200/2024-studio-2#351]
# **Description**  
**Task:** Update QuickTimeEventTest() 
**Feature:** [Team 10] - Combat Enhancements: UI, Animations, Items, and Multi-Attack (#334)

Restructured Combat manager to call getPlayerMultiHit() and pass in the score to combat move to make quicktime events fully functional.
and remove start/ exit button for smoother interaction with combat and fit into combat ui.

---

# **Dependencies**  

- [x]  Restructured Quick Time Events to Facilitate Functioning In Combat (#544)
---

# **Milestones**  
- [x]  Modify quick time events to include combat screen initialization and pass in the score 
- [ ]  Create tests for QTE state storage (entities, services, previous screen state).
- [x]  Implement tests for pausing and resuming the combat screen during QTEs
- [x]  Develop tests for the onExit function in QTEs to verify proper combat screen restoration.
- [ ]  Update existing tests to account for new QTE behavior in combat.
- [ ]  Add integration tests to ensure QTEs interact correctly with combat mechanics.

---

# **Documentation**  
- [Quick time events](https://github.com/UQcsse3200/2024-studio-2/wiki/Quick-Time-Events)

# **Member**  
- Sneha Zazen (sneha-zazen on GitHub) (zaza7_13 on Discord)
