### ISSUE TITLE
Adding subscript showing quantity

### ISSUE THREAD

**Issue by Pratulw5** [UQcsse3200/2024-studio-2#356]
# **Description**
**Task:** Adding subscript showing quantity
**Feature:** #322
The item subscript shows the number of items left in the inventory and changes the as the player interacts with the items

# **Dependencies**
none

# **Milestones**
List of steps that need to be completed for this task.
- [x] Displaying the subscript to the items(Sept. 15)
- [x] implementing it with the actual number of items(Sept. 15)
- [x] Visual Testing (Sept.16)
- [x] Pull request to team 3 main branch(Sept. 20)
 
**Completion Deadline:** Aug. 20

# **Documentation**
 TBD
 
# **Member**
- Pratul (PratulW5) `cactusjuice`
