### ISSUE TITLE
Implement New Health Bar for Main Game Screen

### ISSUE THREAD

**Issue by ChristianMario4** [UQcsse3200/2024-studio-2#36]
# **Description**
**Task:** [Implement New Health Bar for Main Game Screen] .
**Feature:** #10 

The previous health bar provided in the initial codebase will be replaced with a more appropriate health bar that suits the overall game aesthetic better. New textures, sprites, and pixel art will be designed and applied within the _____ of the Codebase. This implementation should reflect any of the actions completed by other teams that could increase or decrease the health of the main character (combat, item consumption, level up etc.).
 
## **Example**
- Upon the character losing health in battle, or gaining health through levelling up or consuming items, the health bar will dynamically update its appearance to appropriately reflect this. 

# **Dependencies**
- [x] Dependent on the Damage Implementation by Combat Team/ Enemy Team
- [x] Dependent on the Consumable Implementation by Item/Inventory Team 
- [x] Dependent on the Main Player Implementation by Animal (Player) Team 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Complete the New Pixel Design for the Health Bar (Aug. 16)
- [x] Learn the Implementations within the Codebase Related to the Health Bar (Aug. 20)
- [x] Create the Sprite Required for the Health Bar to Dynamically Update (Aug. 23)
- [x] Create and Verify Tests to Ensure Correct Functionality for Health Bar (Aug. 23)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- TBC
 
# **Member**
- Christian Almario (@ChristianMario4 ) (CAllMario101)

**Comment by ChristianMario4** [comment]
Feature implemented and pushed to main.
