### ISSUE TITLE
Night mode shaders in game

### ISSUE THREAD

**Issue by jt-09** [UQcsse3200/2024-studio-2#360]
# **Description**
**Task:** Night mode shaders
**Feature:** [Overall game features](#335 )

The task involves implementing a night mode shader for the game, which dynamically adjusts the lighting and color palette to simulate nighttime environments. This shader will dim the screen and adjust colors to cooler, darker tones. The option might be toggleable (turn on or off) or dependent on the in-game time.
## **Example (optional)**

- Night Mode Impact: Players will experience a darker game environment when chosen, making it easier on the eyes and less strenuous. This mode is also consistent with the night mode version of the main menu

# **Dependencies**
Tiles design to apply shaders on #352 
# **Milestones**
List of steps that need to be completed for this task.
- [x]  Initial shader design and planning (Sept. 17th) 
- [x] Research into GDX's basic night mode shader (Sept. 22nd) 
- [x] Implementation of shader in-game (Sept 30th) 
- [x] Testing and functionality checks (Oct 2nd) 
 
**Completion Deadline:** Oct 2nd

 
# **Documentation**
- To be updated
 
# **Member**
- (@jt-09 ) (Jay Thakkar)
- (@jakingy) 
- (@TarushiG)
