### ISSUE TITLE
Login/Register Functionality

### ISSUE THREAD

**Issue by Slothlesss** [UQcsse3200/2024-studio-2#361]
# **Description**
**Task:** Login/Register Functionality.
**Feature:** Overall Game Features #335
 
The Login/Register Menu provides users with an interface to login to an existing account or create a new one. It will use the PlayFab - an backend service to save your account information.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Import PlayFab SDK to Java. (Sep. 17)
- [x] Create Register Functionality. (Sep. 18)
- [x] Create Login Functionality. (Sep. 19)
- [x] Fixing bugs and testing with other computers. (Sep. 19)
 
**Completion Deadline:** Sep. 19
 
# **Member**
- Minh Long Vu (@Slothlesss)
