### ISSUE TITLE
[Team 1] Enemy Turn-Based Combat AI

### ISSUE THREAD

**Issue by KungKemi** [UQcsse3200/2024-studio-2#363]
# **Description**
Enemy AI will need to be implemented for turn-based combat. It should be more intelligent than simply "choose a random move", and should cover things like:

1. _What move is the player likely (or unlikely) to choose this turn?_ For example, if the player is low on stamina they are likely to sleep meaning that enemy should attack

2. _When is it best to use sleep?_ The enemy should use sleep when it is low on health/stamina, but ideally should wait until the player is low on stamina (won't deal much damage) or likely to use a non-attacking move

3. _What move is best to choose for enemies current stamina?_  For high stamina choose attack, but for low stamina choose sleep or guard

4. _When should an enemy/boss use their special?_ Using a special requires setting it up with a combo move so the enemy will need to decide whether it is more advantageous to do it early in the match or later.

# **Dependencies**

- [ ] https://github.com/UQcsse3200/2024-studio-2/issues/171
- [ ] https://github.com/UQcsse3200/2024-studio-2/issues/188
- [ ] https://github.com/UQcsse3200/2024-studio-2/issues/354

# **Milestones**
List of steps that need to be completed for this task.

- [ ] Simple random move AI (Sep. 12)
- [ ] Implement logic for choosing attack, guard or sleep based on stamina and health (Sep. 17)
- [ ] Implement logic for predicting player moves and acting accordingly (Sep. 20)
- [ ] Implement logic for setting up and using special moves (Sep. 23)
- [ ] Testing and refinement (Sep. 24)

**Completion Deadline:** Sep. 25

# **Documentation**
- [Combat system wiki](https://github.com/UQcsse3200/2024-studio-2/wiki/Combat-System)

# **Members**
- Alex Johnson (@KungKemi) (Alex)
