### ISSUE TITLE
Extend Player Camera

### ISSUE THREAD

**Issue by KungKemi** [UQcsse3200/2024-studio-2#364]
# **Description**
**Task:** Extends the Player Camera to Handle Map Boundaries.
**Feature:** #345

The player camera that was implemented in Sprint 1 currently follows the player and provides zoom functionality. When the player moves, it is always positioned in the center of the screen. This is good for an infinite or large map but becomes problematic when the player reaches the edge of the map as non-map areas become visible. To remedy this, the camera will be programmed to temporarily detach from the player when they get close to the map border such that only map areas are visible and reattach correctly whenever the player moves away.

# **Dependencies**

- [ ] https://github.com/UQcsse3200/2024-studio-2/issues/34

# **Milestones**

- [ ] Camera detaches from player when they reach world border (Sep. 21)
- [ ] Camera reattaches to player when they move away (Sep. 22)
- [ ] Testing and Evaluation (Sep. 24)
 
**Completion Deadline:** Sep. 24

# **Documentation**
- [Dynamic Player Camera](https://github.com/UQcsse3200/2024-studio-2/wiki/Player-Camera)
 
# **Member**
- Alex Johnson (@KungKemi) (Alex)
