### ISSUE TITLE
[Team 10] General Combat Animations

### ISSUE THREAD

**Issue by yessica-s** [UQcsse3200/2024-studio-2#366]
# **Description**
**Task:** General Combat Animations
**Feature:** Combat Enhancements: UI, Animations, Items, and Multi-Attack (#334)

This task will involve creating animations for all buttons and actions involved in combat so that each user action during combat is met with visual stimuli. This will invovle working on enemy, player, and boss animations as dependencies aside from any general animations. 

# **Dependencies**

- [ ] Boss Animations in Combat Screen (#342)
- [ ] Player Animations in the Combat Screen (#341)
- [ ] Enemy Animations in Combat Screen (#340)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add attacking animations for players (Sept 20.)
- [x] Add attacking animations for enemies (Sept 27.)
- [x] Add sleeping animations, if decided with team (Sept 4.)
- [x] Add guarding animations, if decided with team (Sept 4.)
 
**Completion Deadline:** Sept 4.
 
# **Documentation**

 
# **Member**
- Yessica (@yessica-s)
