### ISSUE TITLE
[Team 10] Move Description in Combat Screen when hovering over Button

### ISSUE THREAD

**Issue by Jaycoba1** [UQcsse3200/2024-studio-2#367]
# **Description**
**Task:** [Task Name](#3).
**Feature:** #334

A pop up designed to provide the user with information of what a move does when hovering their cursor over a button in the combat screen.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Get a response when hovering over buttons (18/09)
- [x] Figure out what the pop up window should look like (19/09)
- [x] Have the pop up box appear via cursor hovering over (02/10)
 
**Completion Deadline:** Oct. 3rd
 
# **Documentation**
- Documentation on how to change text contained within the pop up
 
# **Member**
- Jonah Ting (@Jaycoba1 on github) (Jaycoba1 on discord)
