### ISSUE TITLE
Mini-game Maze Fish Eggs

### ISSUE THREAD

**Issue by rp3002** [UQcsse3200/2024-studio-2#368]
# **Description**
**Task:** [Mini-game Maze Fish Eggs](#368)
**Feature:** [UnderWater Maze Mini-game](#333)

The player will navigate through an underwater maze after a large tide separates Nemo from the fish eggs. The player must find as many lost fish eggs as possible to secure better medals. The main objective is to collect fish eggs and safely navigate back home.

# **Dependencies**
- [x] Maze Design #378
- [x] Collision Detection #417
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Icon and Rendering (Sept. 25)
- [x] Lighting radius and colour (Sept. 25)
- [x] Implement fish eggs (Sep. 25)
- [x] HitBox (Sept 26)
- [x] Testing (Sept 26)

**Completion Deadline:** Sep. 28
 
# **Documentation**
- [Main description of feature](xx)
- [JavaDoc](xx)
 
# **Member**
- Rajanya Paul Choudhury(@rp3002)
- James King (@jakingy)
