### ISSUE TITLE
Story Line [Stage 2]

### ISSUE THREAD

**Issue by jtayl647** [UQcsse3200/2024-studio-2#369]
# **Description**
**Task:** Story Line [Stage 2] (#369).
**Feature:** Overall Game Features (#335)

The task is to implement the next part of the story. The 'Crocodile' must have a linked story line with the dog and continue with sim liar UI. This task is only the UI and the implementation is seperate. A wiki page is required to document important details. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create crocodile story and post to wiki (Sep. 17)
- [ ] Create initial story board for implementation (Sep. 20)
- [ ] Create final story board (Sep. 25)
 
# **Documentation**
- [Story Line [Stage 2]](https://github.com/UQcsse3200/2024-studio-2/wiki/Story-Line-%5BCrocodile's%5D)
 
# **Member**
- Jaimee Taylor (@jtayl647)
