### ISSUE TITLE
Story Line Implementation

### ISSUE THREAD

**Issue by jtayl647** [UQcsse3200/2024-studio-2#370]
# **Description**
**Task:** [Story Line Implementation of UI](#3)
**Feature:** [Overall Game Features](#335)

This is a collaboration task undertaken by Team 6 and Team 1. Team 6 is providing Story Line aspects for Team 1 to implement. Other aspects may be worked on together. Create the integration of Stage 2 story into the game seamlessly and provide a backstory for the next animal. 

# **Example**

Part: When the player selects the crocodile in the game, a pop-up or dialogue box should appear with the crocodile's story.
Crocodile Story Benefits: The crocodile's unique story will be presented to enhance player engagement and provide relevant context about the crocodile character.

# **Dependencies**
- [ ] Story Line [Stage 2] - UI for the Story Boards (#369)

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Story UI (Sep. 23)
- [x] Create screens to display story (Sep. 25)
- [x] Test ensure sizing formatting (Sep. 26)
- [x] Dialogue for each screen (Sep. 29)
- [ ] Testing for screens (Sep. 30)
 
# **Documentation**
[Story Line [Stage 2]](https://github.com/UQcsse3200/2024-studio-2/wiki/Story-Line-%5BCrocodile's%5D)
 
# **Member**
- Jaimee Taylor (@jtayl647)
- Shaivika Anand (@shaivikaaaa )

**Comment by jtayl647** [comment]
I changed the ticket was a typo
