### ISSUE TITLE
Sorting inventory by item name 

### ISSUE THREAD

**Issue by Pratulw5** [UQcsse3200/2024-studio-2#373]
# **Description**
Sorting will be done according to the item name,

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Implement sort feature on the hotbar and inventory items(Sep. 16)
- [ ] Visual Tesing  (Sep. 16)
- [ ] Pull request with team 3 main branch (Sep 16)

**Completion Deadline:** Aug. 16

# **Documentation**
-TBD

# **Members**
Mittun Sudhahar (@mitsudz) `mitsudz`
