### ISSUE TITLE
[Team 9] End Game Statistics

### ISSUE THREAD

**Issue by callumreillyy** [UQcsse3200/2024-studio-2#374]
# **Description**
**Task:** [End Game Statistics](../issues/374)
**Feature:** [[Team 9] Boss](../issues/325)

Implement end game statistics. These will include categories: items, enemies, player and locations. Each category will have specific tracking implementations.

# **Dependencies**
- #375
- #345 
- #324 
- #373

# **Milestones**
### Item Stats
- [x] Create end game item stats for game
- [x] Track and implement item stats.
- [x] Create subtags for items
### Enemy Stats
- [x] Create end game enemy stats for game
- [x] Track and implement enemy stats.
- [x] Create subtags for items
### Player Stats
- [x] Create end game player stats for game
- [x] Track and implement player stats.
- [x] Create subtags for items
### Tests
- [x] Testing and documenting (Oct. 4)
 
**Completion Deadline:** Oct. 4
 
# **Documentation**
- [End Game Item Stats](../wiki/End-Game-Item-Stats)
- [End Game Enemy Stats](../wiki/End-Game-Enemy-Stats))
- [End Game Player Stats](../wiki//End-Game-Player-Stats))
 
# **Member**
- Callum Reilly (callumreillyy)
