### ISSUE TITLE
[Team 9] End Game Statistics UI

### ISSUE THREAD

**Issue by callumreillyy** [UQcsse3200/2024-studio-2#375]
# **Description**
**Task:** [End Game Statistics](../issues/374)
**Feature:** [[Team 9] Boss](../issues/325)

Create display UI for endgame statistics categories: items, enemy and player. UI will be displayed at the end of the game following the final cutscene.

# **Dependencies**
- [Team 5] Save Handler (functionality on change of player char during play through).

# **Milestones**
### Select Player Character
- [x] Store and display each playable characters stats (dog, croc, bird).
- [x] Create UI for selecting character stats you want to view.
### Stats UI
- [x] Create UI for displaying stats.
- [x] Display selected character in background (faded).
- [x] Implement UI for each stat category.
### Tests
- [x] Testing and documenting (Oct. 4)
 
**Completion Deadline:** Oct. 4
 
# **Documentation**
- [End Game Stats](../wiki/End-Game-Stats)
 
# **Member**
- Callum Reilly (callumreillyy)
