### ISSUE TITLE
Integration of Underwater Maze Mini-Game with Fish NPC

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#377]
# **Description**
**Task:** [Integration of Underwater Maze Mini-Game with Fish NPC](#377).
**Feature:** [Underwater Maze Mini-Game](#333)

Integrate underwater maze mini-game into the main game. This will be from interaction with a fish npc.
 
## **Example**
- The player will approach the fish character and be able to read the story line from the dialogue box. They will then have the option to play and boot up the underwater maze mini-game.

# **Dependencies**
- [x] Creation of fish npc(#253)
- [x]  Dialogue box for npc characters (#101)
 
# **Milestones**
- [x] Change fish dialogue Sept 10
- [x] Implement play game button Sept 10
- [x] Boot up game Sept 10
- [x] Complete Documentation Sept 10
- [x] Complete Relevant Testing Sept 10
 
**Completion Deadline:** Sept. 10
 
# **Documentation**
- [Mini‐Game Integration](https://github.com/UQcsse3200/2024-studio-2/wiki/Mini%E2%80%90Game-Integration)
- [JavaDoc Dialogue Box](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/ui/DialogueBox.html)
 
# **Member**
Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas
