### ISSUE TITLE
Underwater Maze Design

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#378]
# **Description**
**Task:** [Underwater Maze Design](#378).
**Feature:** [Underwater Maze Mini-Game](#333) 

Desing the maze for the underwater maze mini-game.

# **Dependencies**
No dependencies

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Generate a maze (Sep. 17)
- [ ] Randomise maze generation (Sep. 17)
- [ ] Implement Light radius (Sep. 17)
 
**Completion Deadline:** Sep. 17
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
