### ISSUE TITLE
Playable Animals Logic

### ISSUE THREAD

**Issue by KungKemi** [UQcsse3200/2024-studio-2#38]
# **Description**
**Task:** Implement the logic for the playable animal characters.
**Feature:** #4 

A playable animal character is distinguished from each other by visual elements such as the player sprite and animations, but also it's stats and attributes, such as movement speed, health and attack. The purpose of this task is to programmatically link a player character's underlying stats to interactions visible in the game world.
 
## **Examples**
- **Movement speed**: an animal character with a higher movement speed will move faster
- **Health**: when the player is attacked, the health bar decreases
- **Attack strength**: the player is capable of attacking enemies and will deal a different amount of damage depending on their strength

# **Dependencies**

- Dependency 1: this task will depend on the front-end development of the playable animals, requiring knowledge of what stats will be implemented
 
# **Milestones**
- [ ] Implement movement speed (tbd)
- [ ] Implement attacking enemies and receiving damage (tbd)
- [ ] Implement any other stats (tbd)
- [ ] Testing (tbd)
 
**Completion Deadline:** tbd
 
# **Documentation**
- To be completed
 
# **Member**
- Alex Johnson (@KungKemi) (Discord Handle: KungKemi)
