### ISSUE TITLE
Implementing Post-Combat Dialogue Before Leaving Combat Screen

### ISSUE THREAD

**Issue by ChristianMario4** [UQcsse3200/2024-studio-2#389]
# **Description**
**Task:** [Implementing Post-Combat Dialogue Before Leaving Combat Screen].
**Feature:** [[Team 10] Combat Enhancements: UI, Animations, Items, and Multi-Attack](#334)

After either the player or the enemy has lost all of their HP, before the combat ends, and the CombatScreen is left, dialogue explaining and detailing this interaction will be displayed. This task involves preventing the screens from changing until all the dialogue has been presented and read, and implementing the appropriate functionality to display the correct code.
 
## **Example**
- **Player Beats Animal**: When the player beats the enemy, the combat buttons will disappear, and dialogue boxes detailing which entity lost all of its HP, how much experience was gained (or stats lost if player loses) and a fun little message at the end.

# **Dependencies**
- [ ] Dialogue Boxes Detailing Combat (#338)
- [ ] Button Hiding and Showing (#339)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Learn where End of Combat Functionality is Handled (Sep. 19)
- [ ] Implement Dialogue Boxes to Appear at End of Combat (Sep. 19)
- [ ] Implement End of Combat Prevention (Sep. 19)
- [ ] Complete Testing (Visual and Unit) (Sep. 25)
- [ ] Complete Wiki for Combat DialogueBox (Sep. 27) 
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Combat Action Display](https://github.com/UQcsse3200/2024-studio-2/wiki/Combat-Action-Display)
 
# **Member**
- Christian Almario (@ChristianMario4 on Github) (CAllMario101 on Discord)
