### ISSUE TITLE
Start Screen Visuals

### ISSUE THREAD

**Issue by jtayl647** [UQcsse3200/2024-studio-2#39]
# **Description**
**Task:** Start Screen Visuals [Team 6] (#40).
**Feature:** Start Screen/Settings Menu (#12)

Design and implement the start screen visuals for "Attack on Animals." This task includes updating the colours of the buttons to differentiate from the background. Designing the game title to match theme of ground and start screen. Setting the background colour and design, making moving components to make the game feel less static. Eventually integrate gradient colour and curve buttons to make features pop. 

# **Dependencies**
- NULL
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add title, allocate space for design (Aug. 16)
- [x] Choose and test colours, backgrounds and designd (Aug. 17)
- [x]  Finalise desgin(Aug. 24)
- [x] Touch ups on buttons and colour features (Aug. 26)
 
**Completion Deadline:** Aug. 26
- [x] allocate space (Aug. 16)
- [x] initial design (Aug. 22)
- [x] final design (Aug. 26)
- [x] completed designed screen (Aug. 27)
 
# **Documentation**
To be completed
 
# **Member**
- Jaimee (jtayl647) (Jaimee Taylor)
