### ISSUE TITLE
Friendly NPC Atlas and Art Update 

### ISSUE THREAD

**Issue by nreyana** [UQcsse3200/2024-studio-2#390]
# **Description**
The task is to combine all friendly NPC (Non-Player Character) atlas files into a single image to optimize loading times and improve game performance. Additionally, the Turtle, Lion, and Snake character artworks must be updated to align with the overall game aesthetics. An outline/glowing effect will also be added to the FNPC's to allow for visual identification during player-NPC interaction (i.e. the NPC the player is talking to will glow).

**Task:** Update Friendly NPC Atlas' 
**Feature:** [Issue #326](https://github.com/UQcsse3200/2024-studio-2/issues/326) 
 
# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create new Turtle, Lion and Snake artwork 17 Sep.
- [x] Combine all FNPCs into one PNG 17 Sep.
- [x] Add outline/glowing effect to the FNPC frames 19 Sep.
- [x] Update atlas code for each NPC 19 Sep.
- [ ] Update Art and atlas related documentation 21 Sep.
 
**Completion Deadline:** Aug. 21
 
# **Documentation**
TBD.
 
# **Member**
- Nahin Khan (@nreyana)

**Comment by BaileyS03** [comment]
Duplicated ticket
