### ISSUE TITLE
[Team 9] Special Move for Bosses

### ISSUE THREAD

**Issue by phurinjeffy** [UQcsse3200/2024-studio-2#394]
# **Description**
**Task:** [Special Move for Bosses](../issues/394)
**Feature:** [[Team 9] Boss](../issues/325)

Implement special move for the Boss of each area.

A special move may be used by an enemy in place of the other three combat moves. The effect of a special move is different for each enemy, but in general they belong to one of four categories:
- Status ailments: the enemy applies a negative status effect to the player
- Buffs: the enemy buffs one or more of it’s stats
- Debuffs: the enemy debuffs one or more of the player's stats
- Confusion: the enemy confuses the player causing them to sometimes use a random move

# **Dependencies**
- #395

# **Milestones**
### Land Area
- [x] Implement special move for LAND area boss (Kanga)
### Water Area
- [x] Implement special move for WATER area boss (Leviathan)
### Air Area
- [x] Implement special move for AIR area boss (Griffin)
### Tests
- [x] Testing and documenting (Oct. 4)
 
**Completion Deadline:** Oct. 4
 
# **Documentation**
- [Kangaroo Boss Special Move](../wiki/Kangaroo-Boss-Special-Move)
- [Water Boss Special Move](../wiki/Water-Boss-Special-Move)
- [Air Boss Special Move](../wiki/Air-Boss-Special-Move)
 
# **Member**
- Phurin Vanasrivilai (phurinjeffy)
