### ISSUE TITLE
Atlas' Optimisations

### ISSUE THREAD

**Issue by BaileyS03** [UQcsse3200/2024-studio-2#396]
# **Description**
**Task:** [Atlas' Optimisations](#396).
**Feature:** [[Team 4] Friendly NPC Interaction Update and Extensions](#326)

The task is to combine all friendly NPC (Non-Player Character) atlas files into a single image to optimize loading times and improve game performance. Additionally, the Turtle, Lion, and Snake character artworks must be updated to align with the overall game aesthetics. An outline/glowing effect will also be added to the FNPC's to allow for visual identification during player-NPC interaction (i.e. the NPC the player is talking to will glow).
 
# **Dependencies**
There are no dependencies as this is just updates and optimisations. 
 
# **Milestones**
- [x] Create new Turtle, Lion and Snake artwork (17 Sep).
- [x] Combine all FNPCs into one PNG (17 Sep).
- [x] Add outline/glowing effect to the FNPC frames (19 Sep).
- [x] Update atlas code for each NPC (19 Sep).
- [ ] Update Art and atlas related documentation (21 Sep).
 
**Completion Deadline:** Sep. 22

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Nahin (Reyana) (@nreyana )
