### ISSUE TITLE
Outline NPC that the Player is Interacting with

### ISSUE THREAD

**Issue by BaileyS03** [UQcsse3200/2024-studio-2#397]
# **Description**
**Task:** [Outline NPC that the Player is Interacting with](#397).
**Feature:** [[Team 4] Friendly NPC Interaction Update and Extensions](#326)

This task allows users of the game to see exactly what entity they will be talking to for dialogue through having a white outline around the specific entity. This has been requested due to the nature of randomly spawning entities and the possibility of talking to multiple of them at once. This increases clarity and the game experience.
 
# **Dependencies**
- [x] Dependency on Selected Atlas' for each FNPC (#396)
 
# **Milestones**
- [x] 'Selected' Atlas for each entity (Sep. 20)
- [x] Update Dialogue Box and Pause Task to update an Entity's atlas (Sep. 20)
- [x] Testing for selected feature (Sep. 24)
 
**Completion Deadline:** Sep. 24

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
TODO ADD TO THE WIKI UNDER DIALOGUE BOX

# **Member**
- Nahin (Reyana) (@nreyana)
- Bailey (@BaileyS03)
- Julian (@Jul-Wong)
