### ISSUE TITLE
Animal (Player) Feature 

### ISSUE THREAD

**Issue by shaivikaaaa** [UQcsse3200/2024-studio-2#4]
# **Description**
The game "Attack on Animals" begins with the player selecting a specific type of animal, each with unique stats and attributes. The primary objective is to enhance gameplay by introducing additional playable animals, each equipped with distinct traits and capabilities. These animals can store materials/food, or consume them to manage their hunger levels. The goal is to conquer various animal kingdoms, each with unique ecosystems and art styles, culminating in a final battle against the remaining human kingdom (to be decided).

## Components

1. **Player Selection Screen:** from the main menu, implement a selection menu showing players which animals they can choose from for their character #16 
2. **Player Stat Screen:** upon selecting an animal in the Player Selection Screen, a new screen appears which gives focus to the selected animal showing such things as a short description, stat points, abilities, etc.
3. **Player Stat Overlay:** add a small overlay to the game screen (e.g., in the top-left) which displays the player's sprite and stats, as well as other useful information.
4. **Playable Animals (Front-End):** design the playable animals (sprites, stats, movement animations, sounds, etc.)
5. **Playable Animals (Back-End):**  design the underlying logic for playable animals (e.g., how movement speed is reflected in-game, how player health changes in response to enemy attacks, etc.) #38
6. **Dynamic Camera:** program the camera to follow the player as they traverse the map. This could also include a feature which allows for the player to zoom in or out of the focused area #34

# **Dependencies**

Animal Selection Menu: This feature depends on the completion of the animal stat and attribute system (#xx).
RTS Combat System: This system relies on the implementation of the animal stats and crafted tools mechanics 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Write Task Tickets (Aug. 20)
- [ ] Implement the Animal character (Aug. 23)
- [ ] Implement animal stats (Aug. 26)
- [ ]  Unit Testing (Aug. 28)

**Completion Deadline:** Aug. 30

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
- Shaivika Anand (@shaivikaaaa) (Discord Handle: shaivikaaaa) 
- David Araba (@davidaraba ) (Discord Handle: 9jadavid)
- Kavya Sikka (@falgonn) (Discord Handle: Kavya)
- Alex Johnson (@KungKemi) (Discord Handle: KungKemi)
- Andre Bissell (@AndreBissell) (Discord Handle: dr.dre2725)
