### ISSUE TITLE
Mini Map Implementation

### ISSUE THREAD

**Issue by Slothlesss** [UQcsse3200/2024-studio-2#403]
# **Description**
**Task:** Mini Map Implementation.
**Feature:** 

Implement a mini map feature that displays the positions of entities (player, enemies and boss) in the game as dot points. The mini map will update in real-time when the entities move within the game world. 
 
# **Milestones**
- [x] Get all entities and transform it to dot points. (Sep. 20)
- [x] Updates dot points position by frames and transform it to mini map' position. (Sep. 21)
- [x] Fix bugs. (Sep. 22)
- [x] Create UI for mini map. (Sep. 23)

 
# **Member**
- Minh Long Vu (@Slothlesss)
