### ISSUE TITLE
Implement JellyFish

### ISSUE THREAD

**Issue by 0NATE4** [UQcsse3200/2024-studio-2#411]
# **Description**
**Task:** [Implement Jellyfish](#3).
**Feature:** [Underwater Maze Minigame](#2)

The Jellyfish is an npc that wanders around the maze. It does not actively seek the player. It will use the Wander Task to float around the maze.

# **Dependencies**
- [x] Maze Design #378
- [x] Collision Detection #417
  
# **Milestones**
List of steps that need to be completed for this task.
- [x] Icon and Rendering (Sep. 23)
- [x] Lighting radius and colour (Sept. 23)
- [x] Integration with wandering task  (Sept. 23)
- [x] Create Jellyfish animations (Sep 24)
- [x] Integrate combat (Sept. 24)
- [x] Adjust speed (Sept. 26)
- [x]  Tests  (Sept. 26)

 
**Completion Deadline:** Sep. 26

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
@[0NATE4](https://github.com/0NATE4)
0NATE4

@[jakingy](https://github.com/jakingy)
jakingy
