### ISSUE TITLE
Mini-game Maze Angular Fish

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#413]
# **Description**
**Task:** [Mini-game Maze Angular Fish](#413)
**Feature:** [Underwater Maze Mini-Game](#333)

Implement an angular fish enemy in the maze mini-game. The angular fish will chase down the player and attack (decrement the players health) if the fish touches the player.

# **Dependencies**
- [x] Path finding #414
- [x] Maze Design #378
- [x] Collision Detection #417
 
# **Milestones**
- [x] Icon and Rendering (Sept. 26)
- [x] Lighting radius and colour (Sept. 26)
- [x] Integration with path finding (Sept. 26)
- [x] Animation of angular fish (Sept. 26)
- [x] Integrate combat (Sept. 26)
- [x] Angular fish speed (Sept. 26)
- [x] Angular fish tests  (Sept. 26)
- [x] Hit Box (Sept. 26)
 
**Completion Deadline:** Sept. 26
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
James King
@[jakingy](https://github.com/jakingy)
jakingy

Nathan Chung
@[0NATE4](https://github.com/0NATE4)
0NATE4

Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas
