### ISSUE TITLE
Mini-game Maze Eel NPC and Stun Effect

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#415]
# **Description**
**Task:** [Mini-game Maze Eel NPC and Stun Effect](#415)
**Feature:** [Underwater Maze Mini-Game](#333)

Implements the Eel NPC into the Maze mini-game. The Eel NPC chases the playher but does not attck the player. Instead they have a special stun affect which lights up the maze and allows the player to see everything clearly for an instance.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Path finding #414
- [x] Maze Design #378
- [x] Collision Detection #417
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Icon and Rendering (Sept. 26)
- [x] Lighting radius and colour (Sept. 26)
- [x] Integration with path finding (Sept. 26)
- [x] Animation of eel (Sept. 26)
- [x] Stun affect (Sept. 26)
- [x] Hit Box (Sept. 26)
- [x] Eel tests  (Sept. 26)
 
**Completion Deadline:** Sept. 26
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
Manandeep Singh
@[24msingh24](https://github.com/24msingh24)
24msingh24

James King
@[jakingy](https://github.com/jakingy)
jakingy
