### ISSUE TITLE
Mini-game Maze Combat / Health

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#416]
# **Description**
**Task:** [Mini-game Maze Combat / Health](#416)
**Feature:** [Underwater Maze Mini-Game](#333)

The lose condition of the Maze mini-game is when the player has lost off of their health. Health is lost when the player runs into the Angular fish NPC and the JellyFIsh NPC.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Maze Design #378
- [x] Collision Detection #417
- [x] Angular fish #413
- [x] Jellyfish #411

# **Milestones**
List of steps that need to be completed for this task (Sept. 26)
- [x] Add attack and base health to NPC base config (Sept. 26)
- [x] Implement player Health (Sept. 26)
- [x] Implement heath decrease on collision (Sept. 26)
- [x] Show health stats on screen (Sept. 26) 
 
**Completion Deadline:** Sept. 26
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
James King
@[jakingy](https://github.com/jakingy)
jakingy

Nathan Chung
@[0NATE4](https://github.com/0NATE4)
0NATE4
