### ISSUE TITLE
Mini-game Maze Collision Detection

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#417]
# **Description**
**Task:** [Mini-game Maze Collision Detection](#417)
**Feature:** [Underwater Maze Mini-Game](#333)

This task focuses on implementing hit boxes for NPC's and detecting collisions between entities inlcuing walls and NPC's.

# **Dependencies**
- [x] Angular fish (#413)
- [x] Player (#419)
- [x] Fish eggs (#368)
- [x] Eels (#415)
- [x] Jelly fish (#411)
- [x] Maze Design #378
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement hitboxes (Sept. 26)
- [x] Assign physics layer  (Sept. 26)
- [x] Detect Wall collisions (Sept. 26)
- [x] Apply affect (stun for eel, score increase for fish egg etc) (Sept. 26)
 
**Completion Deadline:** Sept. 26
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
James King
@[jakingy](https://github.com/jakingy)
jakingy

Nathan Chung
@[0NATE4](https://github.com/0NATE4)
0NATE4
