### ISSUE TITLE
Mini-game Maze Fish Player

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#419]
# **Description**
**Task:** [Mini-game Maze Fish Playe](#419)
**Feature:** [Underwater Maze Mini-Game](#333)

This task implements the player entitiy to play the Maze mini-game. The player moves via the arrow kets and WASD keys. The player loses health if they run into jelly fish or angular fish. 

# **Dependencies**
- [x] Maze Design #378
- [x] Collision Detection #417
- [x] Mini-game Maze Combat / Health #416
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement player to move around (Sept. 22)
- [x] Give hixbox, physics and lighting radius (Sept. 24)
- [x] Add animation (Sept. 26)
- [x] Integrate Health (Sept. 26)
 
**Completion Deadline:** Sept. 26

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
James King
@[jakingy](https://github.com/jakingy)
jakingy

Manandeep Singh
@[24msingh24](https://github.com/24msingh24)
24msingh24
