### ISSUE TITLE
Mini-game Maze Score

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#439]
# **Description**
**Task:** [Mini-game Maze Score](#439)
**Feature:** [Underwater Maze Mini-Game](#333)

This task involves calculating the score for the Maze mini-game and displaying it on the screen. The score is the number of eggs that the player collects. A player collecting an egg is a colision of the player and egg hitbox. This should cause the fish egg to dissapear and the score to increase.

# **Dependencies**

- [x] Collision Detection #417
- [x] Health #416 
- [x] Fish Eggs #368
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add score to player through MazeGameManagerComponent Class (Sept. 26)
- [x] Increment score when there is a collisoin with eggs (Sept. 26)
- [x] Dispose of fish eggs when it has been collected (Sept. 26)
- [x] Show score on the screen (Sept. 26)
- [x] Show medals threshold on the screen (Sept. 26)
 
**Completion Deadline:** Sept. 26
 
# **Documentation**
Wiki: https://github.com/UQcsse3200/2024-studio-2/wiki/Underwater-Maze-Mini%E2%80%90Game 
Maze Mini_Game Javadoc: https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/minigames/maze/package-summary.html
 
# **Member**
Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas
