### ISSUE TITLE
Mini-game Maze Game Termination

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#442]
# **Description**
**Task:** [Mini-game Maze Game Termination](#442).
**Feature:** [Underwater Maze Mini-Game](#333)

This task works on game termination and end game screen for the Underwater Maze mini-game. The game terminated when either the player has collected all the fish eggs or has lost all of their health. Medals are determined based on the number of fish eggs that have been collected. 

# **Dependencies**

- [x] Score (#439)
- [x] Health (#416)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Set up an end game event in the maze screen (Sept. 26)
- [x] Trigger and get score from MazeGameManagerComponent class which is attached to the player (Sept. 26)
- [x] Set up the end game screen with personalised message (Sept. 26)
- [x] Adjust bugs in end game screen with back to main menu and back to game buttons (Sept. 26)
 
**Completion Deadline:** Sept. 26
 
# **Documentation**
Wiki: https://github.com/UQcsse3200/2024-studio-2/wiki/Underwater-Maze-Mini%E2%80%90Game 
Maze Mini_Game Javadoc: https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/minigames/maze/package-summary.html
 
# **Member**
Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas
