### ISSUE TITLE
Team 4 & 3: Item dropping after talking to FNPC 

### ISSUE THREAD

**Issue by BaileyS03** [UQcsse3200/2024-studio-2#443]
# **Description**
**Task:** [Item dropping after talking to FNPC](#443)
**Feature:**  [Friendly NPC Interaction Update and Extensions](#326) 

This was the beginning of implementing item dropping after discussing with a Friendly NPC. Cows and Fish have been implemented. A cow drops a milk bucket 100% of the time and the fish drops sushi 60% of the time. These increase hunger and are extended from the existing food architecture
 
# **Dependencies**
Existing requirements are already implemented in terms of the AbstractFood class.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Generation of Food PNGs (Sep. 30)
- [x] Generation of Sushi and Milk classes (Sep. 30)
- [x] Integration with PauseTask using event triggers (Sep. 30)
- [x] Finalise unit testing (Sep. 30)
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
- [Food Items](https://github.com/UQcsse3200/2024-studio-2/wiki/Food-Items)

# **Member**
- Bailey Stoodley (@BaileyS03 )
- Mittun Sudhahar (@mitsudz)
