### ISSUE TITLE
Spawn EnemyNPC as a FriendlyNPC once defeated

### ISSUE THREAD

**Issue by shubhgupta2510** [UQcsse3200/2024-studio-2#448]
# **Description**
**Task:** Spawn EnemyNPC as a FriendlyNPC once defeated
**Feature:** Friendly Animals (NPC) [Team 4]

This task is an extension to the task ticket issued during Sprint 2 (#191). This task involves modifying the game's logic to recognise when an EnemyNPC has been defeated. Upon defeat, the EnemyNPC's entity type will be updated to FriendlyNPC. This change will trigger corresponding behaviours and interactions, such as preventing the FriendlyNPC from attacking the player and potentially introducing new gameplay elements or interactions. This feature will add a dynamic element to the game world by allowing defeated enemies to become potential allies or sources of information.

# **Dependencies**
* Team 5 for combat interaction
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create FriendlyNPC instances of the EnemyNPCs (Sep. 16)
- [ ] Spawn converted FriendlyNPC in the game area (Sep. 20)
- [ ] Convert EnemyNPC to FriendlyNPC (Sep. 23)
- [x] Implement testing for the conversion of entities (Oct. 1)
- [ ] Write up the documentation for the feature (Oct. 2)
 
**Completion Deadline:** Oct. 3
 
# **Documentation**
[Entity Conversion Details](https://github.com/UQcsse3200/2024-studio-2/wiki/Enemy-Converting-to-Friendly-Upon-Defeat)
 
# **Member**
- Shubh Gupta (@shubhgupta2510)
