### ISSUE TITLE
Task Ticket: Add Cow NPC 

### ISSUE THREAD

**Issue by BaileyS03** [UQcsse3200/2024-studio-2#45]
# **Description**
Task: Add a Cow NPC.
Feature: Friendly Animals (NPC) (Team 4)
Adds an interactable NPC that resembles a Cow. Each NPC will have specific stats (possibly including but not limited to HP, Speed, Attack etc.) and perhaps slightly different roaming tasks. NPC should also allow interaction with the player with a dialogue box and accommodate quest-giving to the player. They may also offer helpful gameplay hints.
 
Part: A cow NPC sprite will wander the map, being drawn to the player if in close proximity and then pause so the player can read dialogue if nearby.
Quest/Storyline Progression/Hints: The player will then have the option to interact with the Cow and trigger dialogue and/or quests. This may either give hints or progress the storyline with a quest.

# **Dependencies**
- [x] New NPC Behaviour Components (#59)
- [x] Dialogue Box https://github.com/UQcsse3200/2024-studio-2/issues/101
- [x] Questline Flag/Trigger Handling from (Team 5) (#64)

# **Milestones**
List of steps that need to be completed for this task.
 - [x] Create base NPC behavior for Cow and document on wiki (August 15)
 - [x] Create cow sounds for when cow pauses (August 20)
 - [x] Implement tests for Cow (August 21)
 - [x] Accommodate Dialogue/Quest Progression (August 21)
 - [x] Cow NPC implemented and tested (August 25)
 - [x] Update documentation on wiki (August 25)
 
**Completion Deadline:**
Completion Deadline: Aug. 27
 
# **Documentation**
- [Friendly NPC Documentation](https://github.com/UQcsse3200/2024-studio-2/issues/5)
- [Cow (NPC) Documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Cow)
- [Dialogue Box (NPC)](https://github.com/UQcsse3200/2024-studio-2/wiki/Dialogue-Box)
 
# **Member**
- Bailey Stoodley (@BaileyS03) 
- Shubh Gupta (@shubhgupta2510 )
