### ISSUE TITLE
Update Testing Regarding Friendly NPCs

### ISSUE THREAD

**Issue by Jul-Wong** [UQcsse3200/2024-studio-2#457]
# **Description**
**Task:** [Update Testing Regarding Friendly NPCs].
**Feature:** [Friendly NPC Interaction Update and Extensions](#326)

This adds further testing to ensure a high standard of coverage in the new added features. This includes tests to ForestGameArea, NPCFactory and DialogueBoxService.
 
# **Milestones**
- [x] NPCFactory Tests Implemented 
- [x] ForestGameArea Tests Implemented
- [x] DialogueBoxService Tests Implemented
 
# **Documentation**
 
# **Member**
- Julian Wong (@Jul-Wong)
