### ISSUE TITLE
[Team 10] Displaying Status Effects from Boss Special Moves into Combat Screen

### ISSUE THREAD

**Issue by ChristianMario4** [UQcsse3200/2024-studio-2#458]
# **Description**
**Task:** [Implementing UI for Status Effects in Boss Combat].
**Feature:** [[Team 10] Combat Enhancements: UI, Animations, Items, and Multi-Attack](#334)

With the implementation of SpecialMoves with Boss Enemy NPCs, StatusEffects have now been added and implemented with CombatMoves. To accurately reflect this status effects on the combat screen, the relevant UI will be displayed on screen.
 
## **Example**
- Kanga Boss Uses Special Move: When the Kanga Boss uses his special move, there is currently a chance for any status effect to hit. This means that when used, either shock, bleeding, poison or confusion will appear in the center of the combat screen as a UI bar, with text stating "You are currently *status effect*".

# **Dependencies**
- [x] Boss Special Move Status Effects (#395)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Learn Status Effect Implementation (October 1)
- [x] Design Relevant UI Components (October 1)
- [ ] Implement the UI and Its Relevant Listeners (October 1)
- [ ] Complete Testing and Documentation (October 3)
 
**Completion Deadline:** October 3
 
# **Documentation**
- [Displaying Status Effects on Combat Screen](https://github.com/UQcsse3200/2024-studio-2/wiki/Displaying-Status-Effect-UI)
 
# **Member**
- Christian Almario (@ChristianMario4 on Github) (CAllMario101 on Discord)
