### ISSUE TITLE
Implementing Player Name on Main Screen

### ISSUE THREAD

**Issue by ArthurW4130** [UQcsse3200/2024-studio-2#46]
# **Description**
**Task:** [Implementing Player Name on Main Screen](#3).
**Feature:** #10 

Player name will be designed and allocated at the very top left of the main screen. It is above the features like health bar and hunger bar. Player can customise their names by using valid characters (not implemented in Sprint 1). In game design, the "player name" feature refers to the ability for players to input their own chosen name or alias within the game. This feature personalizes the gaming experience by allowing players to identify themselves uniquely within the virtual world. Player names can be displayed in various contexts, such as leaderboards, multiplayer matches, or in-game communication. 
 
## **Example (optional)**
- The player name will be shown on the main screen when is game is on.
- 
# **Dependencies**

- [ ] Dependent on Start Menu Team (#12)
- [ ] Dependent on Animal Team (#5)

e.g.
- [ ] Texture needs to be created for armour laying on map.
- [ ] Texture needs to be created for player wearing armour.
- [ ] Textures need to be created for partially, and then fully, broken armour.
- [ ] Mechanism needs to be implemented for armour to be placed onto map.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Player Name Design (Aug. 15)
- [ ] Learning how to implement it on the main screen  (Aug. 23)
- [ ] Implementing functions to players to customise their names (Aug. 30)
 
 
# **Documentation**
- TBC
 
# **Member**
- Jiatong Wang @ArthurW4130
