### ISSUE TITLE
Time display on main game screen

### ISSUE THREAD

**Issue by jt-09** [UQcsse3200/2024-studio-2#467]
# **Description**
**Task:** Implementing a time display on main game screen
**Feature:** #335 

Implement a time display in the main game screen, positioned next to the exit button, which will show the current in-game time. The time label must be in alignment with the existing UI elements. The time must update dynamically based on the day-night cycle of the game, and padding adjustments will ensure the label is placed neatly beside the "Exit" button.

## **Example (optional)**
- The current in-game time will be displayed as "Time: HH" next to the exit button to indicate the current in-game time in 24 hour format. 

# **Dependencies**
- [ ] Day/Night cycle #424 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ]  Initial creation of TimeDisplay class and scaling implementation (Sept. 30th)
- [ ] Integration of time label with the MainGameExitDisplay (Oct. 1st)
- [ ] Ensure testing procedures for expected functionality and adequate documentation (Oct. 2)
 
**Completion Deadline:** Oct 3.

# **Documentation**
- To be updated
 
# **Member**
- Jay Thakkar @jt-09
