### ISSUE TITLE
Team 5: Global Event Service

### ISSUE THREAD

**Issue by theboah** [UQcsse3200/2024-studio-2#47]
# **Description**
**Task:** Global Event Service and intergration into quest tasks.(#47).
**Feature:** [Quests and Progression](#13 )

Implement a global event service that allows for the listening and registering of events on all screens of the game. This is for the purposes of tracking events for the purposes of quests/achievements. This will involve creating a global event class a global event service as well as working in a quest manager to register global events for tasks for a quest and linking them to quest manager events. The event service will be utilised and intergrated into multiple features such as inventory  and combat.
 
## **Example**
- **Walking event**: Players when they walk will trigger a global steps event in the global event service. This will be recieved by a registered listener in the quest manager and then update a variable in quest manager. At specific points of numbers of steps events updating the property will progress the quest.

# **Dependencies**

- [x] Quest(#67 )
- [x] QuestManager (#64 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1  Create Global Event and EventManager (Aug. 11)
- [x] Step 2  Convert to Event Service (Aug. 12)
- [x] Step 3 Work with QuestManager to progress quest (Aug. 16)
- [x] Step 4 Documentation of Event Service created on wiki (Aug. 16).
- [x] Step 5 Intergrate Events with key features (Aug. 22)
 
**Completion Deadline:** Aug. 22
 
# **Documentation**
- (../wiki/GlobalEventService)
 
# **Member**
- Noah (@theboah)
