### ISSUE TITLE
[Team 9] Handle Post Boss Combat

### ISSUE THREAD

**Issue by callumreillyy** [UQcsse3200/2024-studio-2#474]
# **Description**
**Task:** [Handle Post Boss Combat](../issues/469)
**Feature:** [[Team 9] Boss](../issues/325)

This task aims to handle post boss fight interactions for winning and losing. The player should spawn back into world if boss is killed, or be able to start over if they are killed. This means updating player stats and experience, the achievements page must register a kill for each boss, and post combat will have boss specific dialogue for winning and losing combat.

# **Dependencies**
- [Team 5] Achievement json system
- [Team 5] Removing save file upon losing to boss

# **Milestones**
### Boss Win (sep 25)
- [x] Handle respawning boss on kill
- [x] Update player stats and experience
### Boss Loss (sep 27)
- [x] Remove game over win display
- [x] Delete player save file
- [x] Switch player screen to game over lose 
### Update Achievements (sep 30)
- [x] Give bosses functionality to "die" within the game
- [x] Register each boss within the achievements json
### Tests
- [x] Testing and documenting (Oct. 4)
 
**Completion Deadline:** Oct. 4
 
# **Documentation**
- [Post Boss Combat](../wiki/End-Game-Stats)
 
# **Member**
- Callum Reilly (callumreillyy)
