### ISSUE TITLE
[Team 2] Add a Pigeon enemy NPC

### ISSUE THREAD

**Issue by JackMccabe2** [UQcsse3200/2024-studio-2#490]
# **Description**
**Task:** [Add a Pigeon enemy NPC](https://github.com/UQcsse3200/2024-studio-2/issues/490)
**Feature:** [Enemy NPCs Interaction Feature](https://github.com/UQcsse3200/2024-studio-2/issues/156 )

Introduce a new enemy NPC, the Pigeon, to the flyingarea of the game. The task involves finding an appropriate PNG and atlas file, implement the enemy and add movement tasks, add different atlas tasks, add tests.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Find Appropriate PNG and write atlas file (Sep. 23)
- [x] Implement a visible entity, with ability to chase (Sep. 24)
- [x] Implement animations, different animations for chasing and floating (Sep. 25)
- [x] Testing and adjustments (Sep. 26)
 
**Completion Deadline:** Sep. 26

# **Documentation**
[Pigeon Documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Pigeon-(Enemy-NPC))
 
# **Member**
- Jack (@JackMccabe2 ) (Jack McCabe)
