### ISSUE TITLE
Mini-Game Sound Effects and Background Music

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#492]
# **Description**
**Task:** [Mini-Game Sound Effects and Background Music](#492).
**Feature:** [Underwater Maze Mini-Game](#333) 

This task implements backgoround music to all the mini-games and end game screen as well as sound effects to all Mini-Games.
 This includes:

- background sound track to all minigames, 
- eel static electricity, 
- eel zap (when hits player), 
- fish egg collection ding, 
- jellyfish/angler hit sound effect, 
- angler chomp sound effect, 
- coin collect sound effect, 
- bird flap sound effect, 
- snake apple sound effect,
-  end of minigame fail/bronze/silver/gold sound effects (note that the bronze/silver/gold sounds are all the same but get progressively longer)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement backgorund music for all Mini-Games (Oct. 2)
- [x] Implement sound effects for the EndGameScreen (Oct. 2)
- [x] Implement sound effects for the Snake Mini-Game (Oct. 2)
- [x] Implement sound effects for the Birdie Dash Mini-Game (Oct. 2)
- [x] Implement sound effects for the Maze Mini-Game (Oct. 2)

 
**Completion Deadline:** Oct. 2

 
# **Documentation**
Wiki: https://github.com/UQcsse3200/2024-studio-2/wiki/Underwater-Maze-Mini%E2%80%90Game 
Mini-Games JavaDoc: https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/minigames/package-summary.html
 
# **Member**
James King
@[jakingy](https://github.com/jakingy)
jakingy
