### ISSUE TITLE
[Team 2] Implement Eel Enemy NPC

### ISSUE THREAD

**Issue by JackMccabe2** [UQcsse3200/2024-studio-2#496]
# **Description**
**Task:** [Implementing Eel enemy NPCs](https://github.com/UQcsse3200/2024-studio-2/issues/496 )
**Feature:** [Enemy NPCs Special Interaction Feature](https://github.com/UQcsse3200/2024-studio-2/issues/324 )

Introduce a new enemy NPC, the Eel, to the underwater area of the game. This task involves designing the Eel, implementing its behaviour and special interaction int the overworld and before entering combat, and integrating it into the underwater environment game area.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Find Appropriate PNG and write atlas file (Sep. 21)
- [x] Implement a visible entity, with ability to chase (Sep. 22)
- [x] Implement animations, different animations for chasing and floating (Sep. 23)
- [x] Integration of animation and texture into the game (Sep. 24)
- [x] Testing and adjustments (Sep. 25)
 
**Completion Deadline:** Sep. 25
 
# **Documentation**
[Eel Documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Eel-(Enemy-NPC))
 
# **Member**
- Jack (@JackMccabe2 ) (Jack McCabe)
- Lucas (@LucasRyall ) (Lucas Ryall)
