### ISSUE TITLE
Mini-Game Maze Dynamic Difficulty Increase

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#497]
# **Description**
**Task:** [Mini-Game Maze Dynamic Difficulty Increase](#496).
**Feature:** [Underwater Maze Mini-Game](#333) 

This task implements difficulty increas ein the maze mini-game as the score increases. This will include reducing npc and player sight radius of the npcs (dims then dissapears when the score is 12), will increase enemie spawn rate (jellyfish and eels) and also change colour of the NPC's to be darker. Angular fish colour changes from green to red.

# **Dependencies**

- [x] Maze design and rendering (#378)
- [x] sight radius and shader (#418)
- [x] Eels (#415)
- [x] Jelly fish (#411)
- [x] Angular fish (#413)
- [x] Score (#439)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Decrease player sight radius as score increases (Oct. 2)
- [ ] Decrease NPC sight radius as score increases (Oct. 2)
- [ ] Increase enemy spawn rate as score increases (Oct. 2)
- [ ] Change NPC colour (Oct. 2)
 
**Completion Deadline:** Oct. 2
 
# **Documentation**
Wiki: https://github.com/UQcsse3200/2024-studio-2/wiki/Underwater-Maze-Mini%E2%80%90Game 
Maze Mini_Game Javadoc: https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/minigames/maze/package-summary.html

 
# **Member**
James King
@[jakingy](https://github.com/jakingy)
jakingy
