### ISSUE TITLE
Team 5: Logbook new entrys and detail

### ISSUE THREAD

**Issue by theboah** [UQcsse3200/2024-studio-2#499]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

Add new logbook entries for all new items, minigames, enemies and bosses. Add a detail screen which easily displays some details on the entries.
 
# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Team 5: Save Integration #115

# **Milestones**
- [x] Collect list of all new entries to be made (Oct. 2)
- [x] Create initial json (Oct. 2)
- [x] Edit and collect icons for new achievements (Oct. 2)
- [x] Test triggers for new achievements and bugfix (Oct. 2)
- [x] Implement dialogue box for detail (Oct. 3)
- [x] Visual Testing (Oct. 3)
- [x] Update documentation (Oct. 3)
 
**Completion Deadline:** Oct. 3

# **Documentation**
- [Logbook](../wiki/Logbook---Achievements)
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Noah Stevens (@theboah) (@noahxl234)
