### ISSUE TITLE
[Team 4] Friendly Animals (NPC)s

### ISSUE THREAD

**Issue by BaileyS03** [UQcsse3200/2024-studio-2#5]
# **Description**
In this feature, four pixel-art-style animals will replace the traditional ghosts, roaming freely across the map with their own unique NPC stats and abilities. Each animal will move independently within legal areas of the map, enhancing the immersive experience of being in an 'Animal Kingdom.' These creatures will interact with the main character, offering hints or advancing the storyline through their actions. This feature adds an extra layer of depth to gameplay, enriching the player's experience with dynamic and engaging interactions that contribute to the overall narrative.

## SubFeature/component (optional)
- Pixel-Art Design
- NPC Statistics
- Interaction Mechanics

## **Examples**
- **Part/Feature**: Specific NPCs will provide hints and tutorials throughout the gameplay. 
- **Part/Feature**: 3 Kingdoms representing water, air and land creatures (Animals may include: chickens, wolves, birds and some sort of swimming kingdom)
- **Part/Feature**: NPC's will roam around and interact with the player
- **Part/Feature**: NPC's will pause when a player is around them. 
- **Part/Feature**: NPC's will avoid unfriendly / enemy entities. 

# **Dependencies**
Team 5 Tasks Flag to provide the correct time to provide gameplay hints. (#64)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Pixel Art Done (August 15)
- [x] Entity specific task movements (Avoid and Pause) (August 19) (#59)
- [x] Lion Entity (Aug 19) (#14)
- [x] Cow Entity (Aug 19) (#45)
- [x] Turtle Entity (Aug 19) (#56)
- [x] Snake Entity (Aug 19) (#60)
- [x] Eagle Entity (Aug 19) (#57)
- [x] Basic dialogue for each entity (August 23) (#101)
- [x] Integrate Basic Dialogue appropriately across the game (Aug 25) (#112) 
- [x] Friendly NPC Testing (August 27)

# **Documentation**
- [Friendly NPC Documentation](../wiki/Friendly-NPC's)
- [AI Features for NPC Movement](../wiki/AI) 
- [Dialogue Box (NPC)](../wiki/Dialogue-Box)
- [Service Locator (EntityChatService)](../wiki/Service-Locator)

**Completion Deadline:** August 27

# **Members**
- Julian Wong (@Jul-Wong)
- Hyunmin Cho (@eftg1000)
- Nahin Khan (@nreyana)
- Shubh Gupta (@shubhgupta2510)
- Bailey Stoodley (@BaileyS03)
