### ISSUE TITLE
Team 9 - Kangaroo Boss

### ISSUE THREAD

**Issue by joe-thorne** [UQcsse3200/2024-studio-2#50]
# **Description**
**Task:** [Team 9 Kangaroo Boss](#3).
**Feature:** [[Team 9] End Game (Final Boss)](#9)

This ticket captures the creation of the final boss. This includes sprite/animation, enemy entity, entity behaviour and link into the combat system. The final product will be a boss entity that can participate in combat with the player and provide a reasonable challange.

# **Dependencies**

- [x] Combat System (#7)
- [x] Enemy(#11)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Find/Create Kangaroo with Sunglasses Sprite/Animation (Aug. 22)
- [x] Develop Boss abilities (Aug. 22)
- [x] Build boss entity (Aug. 25)
- [x] Script boss behaviour/link to Combat System (Aug. 27)
- [x] Test & Document(Aug. 29)
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
- [Main description of feature](../wiki/KangaBoss)
 
# **Member**
- TBC
