### ISSUE TITLE
Hive Entity

### ISSUE THREAD

**Issue by mhUnt3rS** [UQcsse3200/2024-studio-2#504]
# **Description**

**Task:** Create Hive Enemy (#504).  
**Feature:** [Enemy NPCs Special Interaction](#324).

The Hive entity introduces a new dynamic challenge for the player by creating a spawning hub for hostile insect-like creatures. The hive will regularly spawn enemies at a set rate, adding an extra layer of difficulty and strategy to gameplay. Players will need to prioritise destroying the hive or manage the enemies it spawns to avoid being overwhelmed. This entity adds depth to the gameplay by forcing players to engage in both short-term combat and long-term planning to remove the source of enemies.

The hive will appear as a stationary structure in certain game areas and will continuously spawn smaller insect enemies, attacking the player unless destroyed.

## **Examples**
- **Hive Mechanic**: The player encounters a hive that spawns insect-like enemies. To stop the continuous flow of enemies, the player must destroy the hive while fending off the spawned creatures.
- **Tactical Gameplay**: If left unchecked, the hive can overwhelm the player by spawning large numbers of enemies.

# **Dependencies**
- [x] #506 

# **Milestones**
- [x] Implemented basic hive entity with enemy spawning (Sept. 14)
- [x] Added interaction for player to damage and destroy the hive (Sept. 20)
- [x] Balanced enemy spawn rates and hive health (Sept. 25)
- [x] Completed playtesting and adjustments (Oct. 2)
- [x] JUnit testing for hive and enemy spawning mechanics (Oct. 2)

**Completion Deadline:** Oct. 2

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)

# **Members**
- Milo (@mhUnt3rS) (Milo Hunter)
