### ISSUE TITLE
Bee Enemy Npc

### ISSUE THREAD

**Issue by mhUnt3rS** [UQcsse3200/2024-studio-2#506]
# **Description**
**Task:** Implementing a Bee enemy  
**Feature:** Enemy NPCs Interaction Feature

The bee enemy will be a fast and agile creature that swarms the player in the meadow biome. It will deal moderate damage but make up for it with high-speed movement and swarming behavior. The bee enemy will have combat stats including health, attack, defense, and speed. Additionally, the bee will be part of a hive system, where multiple bees are spawned from hives to overwhelm the player.

## **Example**
- **Swarming Behavior**: Bees will spawn in groups and attempt to overwhelm the player with numbers. While individually weak, a group of bees can be dangerous if not handled quickly.
- **Hive Interaction**: Bees spawn from hives and will respawn over time if the hive is not destroyed. This forces players to prioritize hive destruction to stop bees from overwhelming them.

# **Milestones**
List of steps that need to be completed for this task:
- [x] Find and create appropriate bee enemy textures (Sep. 17)
- [x] Implement a visible bee entity with swarming behavior (Sep. 18)
- [x] Implement animations for flying and attacking (Sep. 19)
- [x] Integrate animation and texture into the game (Sep. 19)
- [x] Testing and adjustments to bee behavior and combat (Sep. 20)
- [x] JUnit testing for bee enemy mechanics (Sep. 21)

**Completion Deadline:** Sep. 21

# **Documentation**
- [Main description of feature](../wiki/Bee-Enemy-NPC)
- [JavaDoc](JavaDoc/Location/Package/Class)

# **Member**
