### ISSUE TITLE
[Team 2] Add Electric Orb Projectile

### ISSUE THREAD

**Issue by LucasRyall** [UQcsse3200/2024-studio-2#507]
# **Adding Electric Orb Projectile That Paralyses the Player**
**Task:** [[Team 2] Add Electric Orb Projectile](#3).
**Feature:** [[Team 2] Enemy NPCs Special Interaction](https://github.com/UQcsse3200/2024-studio-2/issues/324)

Add a new projectile entity called "Electric Orb", that is shot by the [Eel Enemy](https://github.com/UQcsse3200/2024-studio-2/wiki/Eel-(Enemy-NPC)).  This will act similar to other projectiles, except instead of doing damage to the player, it paralyses them for 2 seconds.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create sprite sheet (Sep. 28)
- [x] Create projectile in game, and have it be shot by the Eel (Sep. 30)
- [x] Have the electric orb paralyse the player (Oct. 2)
 
**Completion Deadline:** Oct. 2

# **Documentation**
- [Electric Orb implementation](https://github.com/UQcsse3200/2024-studio-2/wiki/Electric-Orb-(Projectile))
 
# **Member**
- Lucas Ryall (@mr._derp, https://github.com/LucasRyall)
