### ISSUE TITLE
Team 9 - Transition from regular game to Boss

### ISSUE THREAD

**Issue by joe-thorne** [UQcsse3200/2024-studio-2#51]
# **Description**
**Task:** [Team 9 - Transition from regular game to Boss](#51).
**Feature:** [[Team 9] End Game (Final Boss)](#9)

This ticket captures the events on the triggering of the Boss fight. This includes any story events, spawning of the boss in a position relative to the player or in a set spot on the map, possible change in music/lighting and creating an increased sense of dread. This will take the boss from #50 and place it into combat with the player.

# **Dependencies**
- Combat System (#7)
- Enemy(#11)
- Boss (#50)
- Tasks/Quests (#13)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Play tension music/sound for when the Boss is chasing the player
- [x] Create tension from the Screen/UI when the Boss is chasing the player
- [x] Implement trigger event/spawning logic for Boss
- [x] Transition to any relevant story events, then to combat with Boss
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
- [Transition to Boss](../wiki/Transition-to-Boss)
 
# **Member**
- Phurin Vanasrivilai (@phurinjeffy)
- Ajay Datt (@Ajay-Datt)
