### ISSUE TITLE
[Team 5] Quest Completion and System Enhancements

### ISSUE THREAD

**Issue by reemmi** [UQcsse3200/2024-studio-2#516]
# **Description**
Our team is working on enhancing the quest and achievement systems to add depth to player progression and game engagement. This feature will ensure all our quests are fully implemented and playable.  Players will be able to track their progress through a detailed quest tracker, which displays completion stats, current tasks, and relevant descriptions. By integrating experience rewards, achievements, and dynamic quest completion events, the system will enhance replayability and give players a clear sense of progression. This feature also includes a boss fight that will spawn upon completing specific quests. Other than that this feature is mainly about fixing up bugs here and there. 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Quest Tracker display completion (Oct 10)
- [x] Quest integration - make sure all quests can be completed! (Oct 12)
- [ ] Button or debug functionality to auto complete all quests (Oct 12)
- [ ] Refactor enemy and bosses defeat tracker (Oct 14)
- [ ] Save slots (Oct 14)
- [ ] Fix and improve all documentation and testing (Oct 15)

**Completion Deadline:** Oct 17

# **Documentation**
[Quests Description] (https://github.com/UQcsse3200/2024-studio-2/wiki/Quests)
[Overlays Description] (https://github.com/UQcsse3200/2024-studio-2/wiki/Overlays)
[Game State Saves] (https://github.com/UQcsse3200/2024-studio-2/wiki/Game-State-Saves)
[Event Service] (https://github.com/UQcsse3200/2024-studio-2/wiki/Eventservice)

# **Members**
Reemzheem Hossain (@reemmi)
Noah Stevens (@theboah)
Lachlan (@lellis0406)
Jaden (@jaden-z-fng)
Maree (@MargoCode)
