### ISSUE TITLE
[Team 7] Mini-Game Polishing, Fixes and User Testing

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#518]
# **Description**
This feature ticket is for sprint 4 and aims on polishing and completeing all the mini-games. This includes implementing a pop-up at the begining of every game, fixing code smell, increasing test coverage, and user testing.

## SubFeature/component
List of sub-features you intend to have done and in Master by the end of the sprint.
pre game pop ups
- [x] JUnit testing (#537)
- [x] CodeSmells (#600)
- [x] Snake, BirdieDash and Maze Game UI Updates #601
- [x] End game screen, score board and pause menu UI Update(#536)
- [x] Game balancing and user testing #604
- [x] Implementation of Particle effects into the main game (#602)
- [x] Extra features (Snake speed increasing, Octopus and Turtle entity in maze game) #610
- [x] MiniGame Pop-Ups #609 

# **Dependencies**
All mini-games to have been made including:
Birdie Dash Mini-Game #287
Underwater Maze Mini-Game #333
Snake Mini-Game #6

# **Milestones**
- [x] Mini-Game UI
- [x] Mini-Game Pop-Ups
- [x] Mini-Game Code Smells and fixes

**Completion Deadline:** Oct. 16

# **Documentation**
[Mini-Game User documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Mini%E2%80%90Games)
[Mini-Game User testing](https://github.com/UQcsse3200/2024-studio-2/wiki/Mini%E2%80%90Game-User-Testing-and-Game-Balancing)
[Snake MiniGame Technical Documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Snake-Mini%E2%80%90Game)
[Birdie Dash MiniGame Technical Documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/BirdieDash-MiniGame)
[Maze MiniGame Technical Documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Underwater-Maze-Mini%E2%80%90Game)

# **Members**
James King
@[jakingy](https://github.com/jakingy)
jakingy

Nathan Chung
@[0NATE4](https://github.com/0NATE4)
0NATE4

Manandeep Singh
@[24msingh24](https://github.com/24msingh24)
24msingh24

Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas

Rajanya Paul Choudhury
@[rp3002](https://github.com/rp3002)
rp3002
