### ISSUE TITLE
Team 9 - Post boss fight actions

### ISSUE THREAD

**Issue by joe-thorne** [UQcsse3200/2024-studio-2#52]
# **Description**
**Task:** [Team 9 - Post Boss fight actions](#52).
**Feature:** [[Team 9] End Game (Final Boss)](#9)

This ticket captures the events after the completion of the Boss fight. This includes any story events and changes in music/lighting, as well as a summary screen displaying result with a summary of statistics/occurences during the game. After later sprints this will also lead into the next area of the game, for now it should then return to the main menu.

# **Dependencies**
- [x] Tasks/Quests (#13)
- [x] Statistic/Event Tracking (#53)
- [x] Start Screen/Setting menu (#12)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] script/implement post boss fight story/game events
- [ ] Build game summary screen to display results/stats of gameplay
- [x] dispose of world and return to main title screen
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
- [Main description of feature](../wiki/WorldTransitions)
 
# **Member**
- TBC

**Comment by joe-thorne** [comment]
Post boss screen added in Pull request #147
