### ISSUE TITLE
[Team 10] Combat Sound Effects

### ISSUE THREAD

**Issue by yessica-s** [UQcsse3200/2024-studio-2#527]
# **Description**
**Task:** Combat Sound Effects
**Feature:** [Feature which this tasks contributes to implementing](#2)

Adding sound effects to combat in the game. Includes adding background music and adding sound effects for player and enemy options during combat.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add background music (Oct. 9)
- [x] Add sound effects for player attack, guard, sleep (Oct. 9)
- [x] Add sound effects for enemy attack, guard, sleep (Oct. 9)
- [x] Add sound effect for losing/winning combat (Oct. 9)
 
**Completion Deadline:** Oct. 9
 
# **Documentation**
 
# **Member**
- Yessica (@yessica-s)
- Jonah (@Jaycoba1)

**Comment by Jaycoba1** [comment]
Completed attack, guard and sleep in #608
