### ISSUE TITLE
[Team 10] Make Combat a Pausible Screen

### ISSUE THREAD

**Issue by owenrharding** [UQcsse3200/2024-studio-2#529]
# **Description**
Make it so that the combat screen can be paused, displaying the pause menu and being able to exit to the start screen.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Refactor Combat Screen to extend Pausable Screen (Oct. 10)
- [ ] Implement new methods that pausable screen may require (Oct. 10)
- [ ] Refactor Combat Screen initialisation (Oct. 11)
- [ ] Conduct testing (Oct. 12)
- [ ] Update wiki documentation
 
**Completion Deadline:** Oct. 14
 
# **Documentation**
 
# **Member**
- Owen Harding (@owenrharding ) (owen8232)
