### ISSUE TITLE
Team 9 - Game summary tracking

### ISSUE THREAD

**Issue by joe-thorne** [UQcsse3200/2024-studio-2#53]
# **Description**
**Task:** [Team 9 - Game summary tracking](#53).
**Feature:** [[Team 9] End Game (Final Boss)](#9)

This ticket captures the system that will gather data and information to display in the game summary screen once the boss has been defeated. Likely things could be no of enemies defeated, total damage recieved/given, minigame high scores etc. The data will be stored and passed to the end game screen for display.

# **Dependencies**
- [x] Post boss fight actions(#52)
- [x] Start Screen/Setting menu (#12)
- [x] Minigames (#6)
- [x] Player (#4)
- [x] Implement Saves (#15)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] determine stats to be tracked and work with other teams to implement tracking
- [x] Build data structure to store stats/information
- [x] build stats into save game system
- [x] pass stats to results screen when triggered
- [x] Unit Test Stat.class
- [ ] Unit Test StatManager.class
 
**Completion Deadline:** Aug. 29
 
# **Documentation**
- [Statistics Wiki Page](../wiki/Statistics-Tracking)
 
# **Member**
- Joe (joe-thorne)
- Jose (reonse)

**Comment by joe-thorne** [comment]
Pull request #140
