### ISSUE TITLE
[Team 10] Stamina 🙅‍♂️Hunger 👍

### ISSUE THREAD

**Issue by owenrharding** [UQcsse3200/2024-studio-2#530]
# **Description**
Refactoring combat so that the _stamina_ component is actually hunger. This gives items meaning in combat, as they only affect hunger. Will also require balancing with the _sleep_ move.

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Change stamina for hunger in combat (Oct. 10)
- [ ] Remove stamina from CombatStatsComponent and update intialisations to not have parameter errors (Oct. 10)
- [ ] Conduct testing (Oct. 11)
- [ ] Update wiki documentation (Oct. 12)
 
**Completion Deadline:** Oct. 14
 
# **Member**
- Owen Harding (@owenrharding ) (owen8232)
