### ISSUE TITLE
[Team 4] DialogueBox Styling, Bug Fixes and Documentation Improvements

### ISSUE THREAD

**Issue by BaileyS03** [UQcsse3200/2024-studio-2#532]
# **Description**
This feature will focus on fixing any bugs that are present in the game associated with entity conversion, friendly NPCs and the DialogueBox. It will also include style fixes, documentation clarification and anything else that may present itself throughout the sprint.

# **Dependencies**
This features main focus is fixing previous work hence has no dependencies. 

# **Milestones**
- [x] Overall Style Fixes (October 6) (#534) 
- [x]  Fix entities not spawning in the game and combat areas (October 8) (#573)
- [x]  Spawning entities on specific area (October 9) (#562 ) 
- [x] Improved DialogueBox Documentation including diagrams (October 9) (#541)
- [x] Add conversion of more entities and add all assets to support the converted enemy (October 10) (#575)

**Completion Deadline:** October 15

# **Documentation**
- [Fall friendly NPC pages](https://github.com/UQcsse3200/2024-studio-2/wiki/Friendly-NPCs)
- [Friendly NPC Programming guide](https://github.com/UQcsse3200/2024-studio-2/wiki/Friendly-NPC-Programming-Guide)
- [Dialogue Box](https://github.com/UQcsse3200/2024-studio-2/wiki/Dialogue-Box)
- [Dialgoue Box Programming Guide](https://github.com/UQcsse3200/2024-studio-2/wiki/Dialogue-Box-Programming-Guide)
- [Dialgoue Box Service Programming Guide](https://github.com/UQcsse3200/2024-studio-2/wiki/Dialogue-Box-Service-Programming-Guide)
- [Enemy Conversion](https://github.com/UQcsse3200/2024-studio-2/wiki/Enemy-Converting-to-Friendly-Upon-Defeat)

# **Members**
- Bailey Stoodley (@BaileyS03)
- Shubh Gupta (@shubhgupta2510)
- Nahin Khan (@nreyana)
- Julian Wong (@Jul-Wong)
- Hyunmin Cho (@eftg1000)
