### ISSUE TITLE
UI Update for End Game Screen, Scoreboard and Pause Menu

### ISSUE THREAD

**Issue by rp3002** [UQcsse3200/2024-studio-2#536]
# **Description**
**Task:** [UI Update for End Game Screen, Scoreboard and Pause Menu ](#536)
**Feature:** [Mini-Game Polishing and Fixes](#518)

This task involves refining the scoreboard displays for the SnakeGame, Birdie Dash game and UnderWater Maze Game. Like adjusting the width, height, font size and placement. 

# **Dependencies**

FIND TICKET AND UPDATE THIS!
- [ ] The Pause Menu for main game (xx)

# **Milestones**

- [x] Update the size of the Snake game and birdie Dash scoreboard (Work with the width and height). (Oct. 7)
- [x] Remove medal definitions from all the three scoreboards. (Oct. 7)
- [x] Change the font size of the Maze Underwater Mini-game and alow for resizing (Oct. 7)
- [x] Update the background image of the EndGameMinigameScreen (different for each game) (Oct. 7)
- [x] Add medal image to the end game screen (Oct. 7)
- [x] Line up buttons in one line on the End Mini-Game Screen (Oct. 7)
- [x] Update the pause menu (to be consistent with the main game) (Oct. 7)
 
**Completion Deadline:** Oct. 7
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**

- Rajanya Paul Choudhury (@rp3002)
- Ella Berglas (@EllaBerglas)
