### ISSUE TITLE
Increase Code coverage for all Mini-Games

### ISSUE THREAD

**Issue by rp3002** [UQcsse3200/2024-studio-2#537]
# **Description**
**Task:** [Increase Code coverage for all Mini-Games](#).
**Feature:** [Mini-Game Polishing and Fixes](#518).

The task involves writing all the left out JUnit tests for all three mini games. Writing the Java docs and in addition to that, the task will also include fixing identified code smells and bugs across the games to improve performance. 

# **Dependencies**

- [ ] Dependency on existing game logic for all the three mini-games (#xx)
 
# **Milestones**

- [x] Complete JUnittests for Snake (Oct.9)
- [x] Complete JUnittests for Birdie Dash (Oct.9)
- [x] Complete JUnittests for Maze(Oct.9)
- [x] Complete the Java Docs. (Oct.9)
- [x] Finalise tests, run coverage analysis, and submit all fixes for review. (Oct.10)
 
**Completion Deadline:** Oct 11
 
# **Documentation**
- [Birdie Dash Testing Plan](https://github.com/UQcsse3200/2024-studio-2/wiki/Testing-Plan-%E2%80%90-BirdieDash-Mini-Game)
- [Underwater maze Testing Plan](https://github.com/UQcsse3200/2024-studio-2/wiki/Testing-Plan-for-MazeUnderwater-Mini%E2%80%90Game)
- [Snake Testing Plan](https://github.com/UQcsse3200/2024-studio-2/wiki/Testing-Plans)
 
# **Member**
- James (@jakingy)
- Nathan (@0NATE4)
- Manandeep (@24msingh24)
- Ella (@EllaBerglas)
- Rajanya (@rp3002)
