### ISSUE TITLE
Team 1 - Animal Sprites

### ISSUE THREAD

**Issue by davidaraba** [UQcsse3200/2024-studio-2#54]
# **Description**
**Task:** Design animal sprites. 
**Feature:** Animal Selection sprites (#Task2)

This task involves designing and implementing sprites for the various animals that players can choose between on the selection screen, which was implemented in Task 1. Each animal will have a unique sprite that accurately represents its appearance and characteristics in the game. The sprites should be consistent with the overall art style of the game and be easily distinguishable from one another to enhance the player's experience. The sprites will be integrated into the selection screen, allowing players to visually identify and select their preferred animal.

 
# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Completion of the screen selection mechanism
- [x] General idea of the game's art style to ensure sprites are consistent
 
# **Milestones**
- [x] Initial concept designs for each animal sprite created and reviewed (Aug. 19).
- [x] Finalised sprite designs implemented (Aug. 20).
- [x] Integration of sprites into the selection screen (Aug. 23).
- [x] Testing and adjustment of sprite positioning on the selection screen (Aug. 23).
- [x] Ensuring right sprite loaded into game upon clicking on section screen (Aug. 25)
 
**Completion Deadline:** Aug. 30
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (@davidaraba) Discord: 9jadavid
