### ISSUE TITLE
[Team 9] Boss Spawn Fixes

### ISSUE THREAD

**Issue by phurinjeffy** [UQcsse3200/2024-studio-2#543]
# **Description**
**Task:** [Boss Spawn Fixes](../issues/543)
**Feature:** [Sprint 4 Boss](../issues/580)

Handle the spawn location of each bosses appropriately.
Once the spawn trigger is called, each bosses spawn near their area's gate going to the new area.

# **Dependencies**
- #325 

# **Milestones**
### Implementations
- [x] Determine the new positions for each bosses to spawn
- [x] Update the method to spawn boss entity into the game area
### Tests
- [ ] Testing and documenting (Oct. 13)
 
**Completion Deadline:** Oct. 13
 
# **Documentation**
- [Triggers for Bosses](https://github.com/UQcsse3200/2024-studio-2/wiki/Triggers-for-Bosses)
 
# **Member**
- Phurin Vanasrivilai (phurinjeffy)
