### ISSUE TITLE
Introduce new items and spawn control

### ISSUE THREAD

**Issue by PHONGNGYUEN1** [UQcsse3200/2024-studio-2#546]
# **Description**
**Task:** [Introduce new items and spawn control](#3).
**Feature:** [Feature which this tasks contributes to implementing](#535 )

Introduce regional items for different regions. Ensure those items can only spawn in their respective region when unlocked and introduce a spawn rate chance for items that have higher value

## **Example (optional)**
- **Candy Spaen rate**: Candy has the largest effects on hunger out of all items thus the chance of it spawning near player would be 90% chance in comparison to Apple it would be 10% chance
- **Regional Food**: region food of ocean will not be spawned until fog has been lifted

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Aug. 19)
- [ ] Step 2 (Aug. 20)
- [ ] Step 3 (Aug. 23)
- [ ] Step 4 (Aug. 23)
 
**Completion Deadline:** Aug. 23

e.g.
- [ ] Initial design of `Armour` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Phong Nguyen (@PHONGNGYUEN1 ) (beannie)
