### ISSUE TITLE
[Team 10] Combat Stats Bars UI

### ISSUE THREAD

**Issue by paulpleela** [UQcsse3200/2024-studio-2#547]
# **Description**
**Task:** [Combat Stats Bars UI]().
**Feature:** [Cleaning Up, Minor Improvements, and Bug Fixes](../issues/539)

Enhance stats bars in combat by adding an Enemy hunger bar, formatting text, and fixing positioning and resizing issues.

# **Dependencies**
- #172

# **Milestones**
- [ ] Add a Hunger bar for the Enemy.
- [ ] Ensure the added Hunger bar is functional and updates correctly (Visual or unit testing).
- [ ] Modify all combat stats bars text formatting to be {STAT}: {CURRENT_VALUE}/{MAX_VALUE}
- [ ] Fix positioning and resizing issues of the stats bars.
- [ ] Visual testing of stats bars positioning and resizing.
 
**Completion Deadline:** TBC

# **Documentation**
- [CombatStatsDisplay](../wiki/CombatStatsDisplay)

# **Member**
- Peeranat Leelawattanapanit (@paulpleela on GitHub) (pa._.l on Discord)
