### ISSUE TITLE
Inventory full alert

### ISSUE THREAD

**Issue by Pratulw5** [UQcsse3200/2024-studio-2#554]
# **Description**
**Task:** [Inventory full alert](#3).
**Feature:** [Team 3 sprint 4](#535 )

This feature is to alert players when the inventory is at its full capacity and cannot pick up more items. It will indicate with a different skin texture of inventory (which is temporary for a few seconds) with a dialogue box to inform users that the inventory is full and they can no longer pick up more items
## **Example (optional)**
- **Full inventory**: When player inventory is at capacity and they attempt to pick up an item on the map, the inventory will show an indication and will not allow the item to be added
- **Loop Boxes**: If the player receives a loot box the items will not be added or alerted by inventory. This results in the items to drop on the map 

# **Dependencies** 
- [ ] Needs texture to indicate the inventory is full

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Update the inventory check when it is full to include the texture/effect (Oct. 12)
- [ ] update the dialogue box to indicate the item is full description (Oct 14)
 
**Completion Deadline:** Oct.16

# **Documentation**
-  [InventoryAlert](https://github.com/UQcsse3200/2024-studio-2/wiki/InventoryDisplay)

 
# **Member**
- Name  Pratul (@Pratulw5 )
