### ISSUE TITLE
Task Ticket: Add Turtle NPC

### ISSUE THREAD

**Issue by nreyana** [UQcsse3200/2024-studio-2#56]
# **Description**
Task: Add a Turtle NPC.
Feature: Friendly Animals (NPC) (Team 4)
Adds an interactable NPC that resembles a Turtle. Each NPC will have specific stats (possibly including but not limited to HP, Speed, Attack etc.) and perhaps slightly different roaming tasks. NPC should also allow interaction with the player with a dialogue box and accommodate quest-giving to the player. They may also offer helpful gameplay hints.

Part: A turtle NPC sprite will wander the map, being drawn to the player if in close proximity and then pause so the player can read dialogue if nearby.
Quest/Storyline Progression/Hints: The player will then have the option to interact with the Turtle and trigger dialogue and/or quests. This may either give hints or progress the storyline with a quest.
 
# **Dependencies**
- [x]  NPC Sprite of a Turtle (@shubhgupta2510 / Team 4)
- [x] Dialogue Box https://github.com/UQcsse3200/2024-studio-2/issues/101
- [x]  Questline Flag/Trigger Handling from (Team 5)

# **Milestones**

- [x] Create base NPC behaviour for Turtle and document on wiki (August 15)
- [x] Implement tests for Turtle (August 21)
- [x] Create turtle sounds for when turtle pauses
- [x] Accommodate Dialogue/Quest Progression (August 21)
- [x] Turtle NPC implemented and tested (August 25)
- [x] Update documentation on wiki (August 25)

 
**Completion Deadline:** Aug. 25
 
# **Documentation**
- [Friendly NPC Documentation](../wiki/Friendly-NPC's)
- [Turtle NPC Documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Turtle)
- [Dialogue Box (NPC)](https://github.com/UQcsse3200/2024-studio-2/wiki/Dialogue-Box)
 
# **Member**
- Nahin (Reyana) Khan (@nreyana)
