### ISSUE TITLE
Stats and hunger change task

### ISSUE THREAD

**Issue by AndreBissell** [UQcsse3200/2024-studio-2#565]
# **Description**
**Task:** [Stats and hunger change task](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

This task ticket aims to accomplish two main things. Firstly, the hunger bar is constantly decreasing regardless of the screen, and pause status of the game. The hunger will be reworked to fix this, and only decrease when the player is moving. Secondly, the player stats will be adjusted when the player dies in combat or in game. The players level will be decreased, experience lost, and stats decreased according to the level decrease. Furthermore, tests will be conducted to ensure these new aspects. 
 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Change how hunger decreases (Oct 10)
- [x] Adjust stats upon death (Oct 12)
- [x] Complete tests (Oct 12)
 
**Completion Deadline:** Oct 12

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Andre Bissell (@AndreBissell ) (Andre)
