### ISSUE TITLE
Task Ticket: Add Eagle NPC

### ISSUE THREAD

**Issue by eftg1000** [UQcsse3200/2024-studio-2#57]
# **Description**
**Task:** Add an Eagle NPC.
**Feature:** Friendly Animals (NPC) (Team 4)

Adds an interactable NPC that resembles an Eagle. Each NPC will have specific stats (possibly including but not limited to HP, Speed, Attack etc.) and perhaps slightly different roaming tasks. NPC should also allow interaction with the player with a dialogue box and accommodate quest-giving to the player. They may also offer helpful gameplay hints.
 
## **Example (optional)**
- **Part**: An eagle NPC sprite will wander the map, being drawn to the player if in close proximity and then pause so the player can read dialogue if nearby.
- **Quest/Storyline Progression/Hints**: The player will then have the option to interact with the Eagle and trigger dialogue and/or quests. This may either give hints or progress the storyline with a quest.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] NPC Sprite of an Eagle (@shubhgupta2510 / Team 4)
- [x] Dialogue Box https://github.com/UQcsse3200/2024-studio-2/issues/101
- [x] Questline Flag/Trigger Handling from (Team 5)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create base NPC behavior for Eagle and document on wiki (August 15)
- [x] Create eagle sounds for when eagle pauses (August 20)
- [x] Implement tests for Eagle (August 21)
- [x] Accommodate Dialogue/Quest Progression (August 21)
- [x] Eagle NPC implemented and tested (August 25)
- [x] Update documentation on wiki (August 25)
 
**Completion Deadline:** Aug. 27
 
# **Documentation**
- [Friendly NPC Documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Friendly-NPC's)
- [Eagle (NPC) Documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Eagle)
- [Dialogue Box (NPC)](https://github.com/UQcsse3200/2024-studio-2/wiki/Dialogue-Box)
 
# **Member**
- Hyunmin Cho (@eftg1000)
