### ISSUE TITLE
Mini Map Enhancement

### ISSUE THREAD

**Issue by Slothlesss** [UQcsse3200/2024-studio-2#572]
# **Description**
**Task:** Mini Map Enhancement
**Feature:** #519 

Innovate a mini map with new dot points that are able to track the positions of other entities (friendly NPCs, minigame NPCs, and bosses). The mini map will update in real-time when the entities move within the game world. 
 
# **Milestones**
- [x] Implement new dot points that represent for friendly NPCs, minigame NPCs, and bosses. (Oct. 7).
- [x] Fix bugs related to enemies' dot points (Oct. 9).
- [x] Optimize Mini Map as it makes dropping FPS (Oct. 10).
- [ ] Adjust the Mini Map Testing (Oct. 11).

 
# **Member**
- Minh Long Vu (@Slothlesss)

**Comment by jt-09** [comment]
done in PR #589
