### ISSUE TITLE
[Team 4] Add conversion of more entities and add all assets to support the converted enemy

### ISSUE THREAD

**Issue by shubhgupta2510** [UQcsse3200/2024-studio-2#575]
# **Description**
**Task:** Add conversion of more entities and add all assets to support the converted enemy
**Feature:** [Team 4] DialogueBox Styling, Bug Fixes and Documentation Improvements (#532)

This task ticket focuses on adding support for more entity conversion in the game. As more enemies have been added to the game, the support must be added to correctly convert the new enemy entities. Additionally, sprites and sounds must also be added to support the converted NPCs.

# **Dependencies**
There are no dependencies for this task
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add conversion of all new entities (Oct. 9)
- [x] Add sprites for the converted NPCs (Oct. 10)
- [x] Add sounds for the converted NPCs (Oct. 11)
 
**Completion Deadline:** Oct. 13

# **Documentation**
- To be updated
 
# **Member**
- Shubh Gupta (@shubhgupta2510)
