### ISSUE TITLE
Clean up/Refactor areas Package

### ISSUE THREAD

**Issue by mitsudz** [UQcsse3200/2024-studio-2#578]
# **Description**
**Task:**
Refactor the areas package to improve modularity and coupling and reduce code smells and risks of bugs.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Refactor config files to not use json (Aug 9)
- [x] Refactor areas to separate enums (Aug 9)
- [x] Reduce Code Smells (Aug 10)
- [x] Reduce Code Duplication (Aug 11)
 
**Completion Deadline:** Aug. 11
 
# **Member**
- Mittun Sudhahar (@mitsudz )
- Howie (@Howard-12)
