### ISSUE TITLE
Reduce Code Smells

### ISSUE THREAD

**Issue by mitsudz** [UQcsse3200/2024-studio-2#579]
# **Description**
This collaboration ticket is intended to further remove code smells across the entire repository - as per SonarCloud code smells.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Identify relevant code smells to fix (Aug 11)
- [x] Remove as many code smells as possible (Aug 11)
- [x] Conduct testing and ensure functionality remains the same and add unit tests if necessary (Aug 12)
- [x] Merge to Main (Aug. 13)
 
**Completion Deadline:** Aug. 13
 
# **Member**
- Mittun Sudhahar (@mitsudz )
- Lucas Ryall (@LucasRyall )
