### ISSUE TITLE
Sound for Main Menu

### ISSUE THREAD

**Issue by jtayl647** [UQcsse3200/2024-studio-2#583]
# **Description**
**Task:** [Sound for Main Menu](#583)
**Feature:** [UI (Main Menu + Minimap) refinements] (#519)

Add sound effects for the main menu.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Find Sound (Oct. 13)
- [x] Add sound (Oct. 15)
- [x] Add setting features (Oct. 15)
- [x] Test (Oct. 15)
 
**Completion Deadline:** Oct. 16
 
# **Documentation**
- To be completed.
 
# **Member**
- Jaimee Taylor (@jtayl647)
