### ISSUE TITLE
[Team 2 & 9 & 10] Balancing Combat and Statistics in Game

### ISSUE THREAD

**Issue by ChristianMario4** [UQcsse3200/2024-studio-2#584]
# **Description**
**Task:** Balancing Combat and Statistics in Game .

Currently, combat is heavily unbalanced with regular combat being almost insta-kill, and boss combat being almost impossible. Levelling also currently only provides a miniscule increase in statistics. Balancing for each of the moves  
 

# **Dependencies**
Currently, there are no dependencies as changing statistics of different entities is not influenced by stat tickets.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Play through the game and determine the current state of the balancing in game (Oct 13) (Tentative)
- [x] Determine the balancing  (Oct 13) (Tentative)
- [x] [Edit the appropriate stats for entities](https://github.com/UQcsse3200/2024-studio-2/issues/664) (Oct 15)
- [x] Do User Testing to Validate Game Balancing (Oct 15)
 
**Completion Deadline:** Oct. 15

 
# **Documentation**
- [Combat Statistics](https://github.com/UQcsse3200/2024-studio-2/wiki/Combat-System)
- [Enemy Statistics](https://github.com/UQcsse3200/2024-studio-2/wiki/Enemy-NPC-Statistics)
 
# **Member**
- Owen Harding (@owenrharding on GitHub) (owen8232 on Discord)
- Christian Almario (@ChristianMario4 on Github) (CAllMario101 on Discord)
- Alex Johnson (@KungKemi) (KungKemi on Discord)
- Jose Leoncio (@reonse) (hose_ey on Discord)
- Jack (@JackMccabe2) (butcracjack on Discord)
