### ISSUE TITLE
[Team 2 & 9] Enemy/Boss Cutscenes Improvements

### ISSUE THREAD

**Issue by phurinjeffy** [UQcsse3200/2024-studio-2#590]
# **Description**
**Task:** [[Team 2 & 9] Enemy/Boss Cutscenes Improvements](../issues/590)
**Feature:** [[Team 9] Sprint 4 Boss](../issues/580)

Improve the transition screen that will appear before entering a combat scene involving enemy/boss NPCs. This feature aims to provide an enemy detail, and differentiate between normal gameplay and combat.

# **Dependencies**
- #178
- #463
 
# **Milestones**
- [x] Use one class for both normal enemy and boss 'PreCombatCutsceneScreen', to avoid duplication
- [ ] Remove now unused BossCutsceneScreen and EnemyCutsceneScreen
- [ ] Update the layout of the screen
- [ ] Testing and adjustments (Oct. 16)

**Completion Deadline:** Oct. 16
 
# **Documentation**
- [Transition to Combat Screen for Enemy NPCs](https://github.com/UQcsse3200/2024-studio-2/wiki/Transition-to-Combat-Screen-for-Enemy-NPCs)
- [Transition to Boss](https://github.com/UQcsse3200/2024-studio-2/wiki/Transition-to-Boss)
 
# **Member**
- Jade (@nownver) (Urawee Thani)
- Jeff (@phurinjeffy) (Phurin Vanasrivilai)
