### ISSUE TITLE
Leaderboard Implementation

### ISSUE THREAD

**Issue by Slothlesss** [UQcsse3200/2024-studio-2#591]
# **Description**
**Task:** Leaderboard Implementation
**Feature:** #519 
The leaderboard for the minigame score will track and display the top player scores for the game's competitive mini-game mode. It will dynamically update as players achieve new high scores, providing an engaging competitive element to the mini-game experience. The leaderboard will be accessible through the main menu and will feature player rankings, scores, and optional player avatars. The feature will ensure that players are motivated to improve their performance and compare their progress against others, promoting replayability and engagement.

# **Milestones**
- [x] Design leaderboard UI Layout. (Oct. 12)
- [x] Implement online storing and loading players' scores. (Oct. 12)
- [x] Sync minigame score with leaderboard. (Oct. 13)
- [x] Finalize leaderboard display in main menu. (Oct. 14)
- [ ] Test leaderboard and updates in real-time. (Oct. 15)
- [ ] Test with multiple users at the same time. (Oct. 16)
 
 
# **Member**
- Minh Long Vu (@Slothlesss)

**Comment by jt-09** [comment]
fixed in pr #653
