### ISSUE TITLE
[Team 9] Boss-related config tweaking

### ISSUE THREAD

**Issue by phurinjeffy** [UQcsse3200/2024-studio-2#595]
# **Description**
**Task:** [Boss-related config tweaking](../issues/595)
**Feature:** [Sprint 4 Boss](../issues/580)

Minor tweaking of bosses config to make the entity work as expected, for example prior to changing, the speed for kanga's joey and leviathan's water spiral was too slow causing the entity to stay in place and not move. 

In addition, add missing combat movesets component to each bosses (bug fix).

Adjust friendly NPCs dialogue related to the boss names.

# **Milestones**
- [x] Tweak bosses config in the 'enemyNPCs.json' file
- [x] Create the movesets for each bosses, and add the component to each entity
- [x] Adjust the friendly NPCs hints, changing the bosses name.
- [x] Update tests accordingly. 
 
**Completion Deadline:** Oct. 17
 
# **Member**
- Phurin Vanasrivilai (phurinjeffy)
