### ISSUE TITLE
[Team 2] Add Unit Tests for EnemyFactory 

### ISSUE THREAD

**Issue by nownver** [UQcsse3200/2024-studio-2#599]
# **Description**
**Task:** [Add EnemyFactory Unit Tests](#).
**Feature:** [Enemy NPC Improvement and Cleanup](https://github.com/UQcsse3200/2024-studio-2/issues/647) 

This task focuses on writing unit tests for the EnemyFactory class, which is responsible for creating enemy NPCs in the game. The tests should cover various NPCs like Green Macaw, Chicken, Bear, Frog, and others, ensuring that the factory correctly initializes enemies with their expected properties and behaviors. Additionally, any issues uncovered during testing will be addressed by refactoring the factory or its dependencies.

# **Dependencies**

- [x] (#156 )
 
# **Milestones**

- [x] Write unit tests for enemy NPC creation, covering all enemy types (Green Macaw, Chicken, Bear, etc.). (Oct.14)
- [x] Ensure that the created enemies have the correct initial attributes (position, animations, behaviors). (Oct.14)
- [x] Refactor the EnemyFactory if necessary based on test results. (Oct.15)
- [x] Finalize the tests, run coverage analysis, and submit for review. (Oct.16)
 
**Completion Deadline:** Oct 16
 
# **Documentation**
- [Enemy Factory Tests](https://github.com/UQcsse3200/2024-studio-2/wiki/Sprint-4-Test-Plan)
 
# **Member**
- Lucas (@LucasRyall) Lucas Ryall
- Jade (@nownver) Urawee Thani
