### ISSUE TITLE
Task Ticket: Add Snake NPC

### ISSUE THREAD

**Issue by shubhgupta2510** [UQcsse3200/2024-studio-2#60]
# **Description**
Task: Add a Snake NPC.
Feature: Friendly Animals (NPC) (Team 4)
Adds an interactable NPC that resembles a Snake. Each NPC will have specific stats (possibly including but not limited to HP, Speed, Attack etc.) and perhaps slightly different roaming tasks. NPC should also allow interaction with the player with a dialogue box and accommodate quest-giving to the player. They may also offer helpful gameplay hints.

Part: A snake NPC sprite will wander the map, being drawn to the player if in close proximity and then pause so the player can read dialogue if nearby.
Quest/Storyline Progression/Hints: The player will then have the option to interact with the Snake and trigger dialogue and/or quests. This may either give hints or progress the storyline with a quest.

# **Dependencies**

- [x] NPC Sprite of a Snake (@shubhgupta2510 / Team 4)
- [x] Dialogue Box https://github.com/UQcsse3200/2024-studio-2/issues/101
- [x] Questline Flag/Trigger Handling from (Team 5)
 
# **Milestones**
- [x] Create base NPC behavior for Snake and document on wiki (August 15)
- [x] Implement tests for Snake (August 21)
- [x] Create snake sounds for when snake pauses
- [x] Accommodate Dialogue/Quest Progression (August 21)
- [x] Snake NPC implemented and tested (August 25)
- [x] Update documentation on wiki (August 25)
 
**Completion Deadline:** 
Completion Deadline: Aug. 27
 
# **Documentation**
- [Friendly NPC Documentation](https://github.com/UQcsse3200/2024-studio-2/issues/5)
- [Snake (NPC) Documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Snake)
- [Dialogue Box (NPC)](https://github.com/UQcsse3200/2024-studio-2/wiki/Dialogue-Box)

# **Member**
- Shubh Gupta (shubhgupta2510)

**Comment by MiniSoda17** [comment]
Hi there, please remember to add the specified labels like assignees, projects and milestones
