### ISSUE TITLE
Mini-Game Code Smells and Bug Fixes

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#600]
# **Description**
**Task:** [Mini-Game Code Smells and Bug Fixes](#3).
**Feature:** [Mini-Game Polishing and Fixes](#518)

This task ticket works on improving code qualist and code smells for all the Mini-Games
 
# **Dependencies**
- [ ] Birdie Dash Mini-Game #287 
- [ ] Underwater Maze Mini-Game #333 
- [ ] Snake Mini-Game #6
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] resizing screen minimising crashing (Oct. 13)
- [ ] reduce memory usage maze (Oct 13)
- [ ] fix sonar cloud code smells for all Mini-Games (Oct. 16)
 
**Completion Deadline:** Oct. 16
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
James King
@[jakingy](https://github.com/jakingy)
jakingy

Nathan Chung
@[0NATE4](https://github.com/0NATE4)
0NATE4

Manandeep Singh
@[24msingh24](https://github.com/24msingh24)
24msingh24

Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas

Rajanya Paul Choudhury
@[rp3002](htt
