### ISSUE TITLE
Mini-Game UI Update

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#601]
# **Description**
**Task:** [Mini-Game UI Update](#601).
**Feature:** [Mini-Game Polishing and Fixes](#518)

This task works on implementing UI that is more inline with the game art style.

# **Dependencies**
- [x] Birdie Dash Mini-Game #287 
- [x] Underwater Maze Mini-Game #333 
- [x] Snake Mini-Game #6
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Snake UI Update (Oct. 13)
  - [x]  Snake grid 
  - [x] Snake tail
- [x] Birdie Dash UI Update (Oct. 13)
  - [x] Bird icon
  - [x] Coins spinning
  - [x] Spikes 
  - [x] Pipes
- [x] Maze Game UI Update (Oct. 13)
  - [x] Maze walls
 
**Completion Deadline:** Oct. 13
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
James King
@[jakingy](https://github.com/jakingy)
jakingy

Nathan Chung
@[0NATE4](https://github.com/0NATE4)
0NATE4

Manandeep Singh
@[24msingh24](https://github.com/24msingh24)
24msingh24

Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas
