### ISSUE TITLE
Particle Effect Service

### ISSUE THREAD

**Issue by jakingy** [UQcsse3200/2024-studio-2#602]
# **Description**
**Task:** [Particle Effect Service](#3)
**Feature:** [Overall game features](#335 )

Refactors the particle effects from the maze minigame into a service that can be used in other parts of the game.
 
## **Example**
```java
ServiceLocator.getParticleService().playEffect(ParticleService.ParticleType.DAMAGE10, 1.2f, 1.5f);
```
 
# **Milestones**
- [x] Create particle service (Oct. 7).
- [x] Create particle effect renderer (Oct. 8).
- [x] Create tests (Oct. 10).
- [x] Documentation of `Particle Effects` updated on wiki (Oct. 10).
 
**Completion Deadline:** Oct. 10
 
# **Documentation**
- [Particle Effects](https://github.com/UQcsse3200/2024-studio-2/wiki/Particle-Effects)
- [JavaDoc](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/particles/package-summary.html)
 
# **Member**
- James (@jakingy) (James King)
