### ISSUE TITLE
Mini-Game User Testing and Game Balancing

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#604]
# **Description**
**Task:** [Mini-Game User Testing and Game Balancing](#604).
**Feature:** [Mini-Game Polishing and Fixes](#518)

Complete user testing and adjust the game medal thresholds.

# **Dependencies**
- [ ] Birdie Dash Mini-Game #287 
- [ ] Underwater Maze Mini-Game #333 
- [ ] Snake Mini-Game #6
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Set up plan (Oct. 9)
- [x] Conduct user testing (Oct. 14)
- [x] Analyse Results (Oct. 15)
- [x] Implement changed (Oct. 15)
 
**Completion Deadline:** Oct. 15
 
# **Documentation**
- [User Testing Report](https://github.com/UQcsse3200/2024-studio-2/wiki/Mini%E2%80%90Game-User-Testing-and-Game-Balancing)
 
# **Member**
Ella Berglas
@[EllaBerglas](https://github.com/EllaBerglas)
EllaBerglas
