### ISSUE TITLE
[Team 9] Update bosses tension music

### ISSUE THREAD

**Issue by phurinjeffy** [UQcsse3200/2024-studio-2#605]
# **Description**
**Task:** [Update bosses tension music](../issues/605)
**Feature:** [Sprint 4 Boss](../issues/580)

Update the bosses chase functionality which plays tension music during the chase sequence and restores the previous background music once the chase ends, using the AudioManager class.

# **Dependencies**
- #51 

# **Milestones**
### For the land boss in ChaseTask
- [x] Find suitable tension music for the boss
- [x] Update the methods playTensionMusic() and stopTensionMusic().
### For the water boss in LeviathanTask
- [x] Find suitable tension music for the boss
- [x] Update the methods playTensionMusic() and stopTensionMusic().
### For the air boss in GriffinTask
- [x] Find suitable tension music for the boss
- [x] Update the methods playTensionMusic() and stopTensionMusic().

### Tests
- [ ] Testing and documenting (Oct. 13)
 
**Completion Deadline:** Oct. 13
 
# **Documentation**
- [Transition to Boss](https://github.com/UQcsse3200/2024-studio-2/wiki/Transition-to-Boss)
 
# **Member**
- Phurin Vanasrivilai (phurinjeffy)
