### ISSUE TITLE
Adjusting sprite and stats for animal chosen

### ISSUE THREAD

**Issue by AndreBissell** [UQcsse3200/2024-studio-2#61]
# **Description
**Task:** [](#4 ).
**Feature:** [Animal player](#1)

Implement the relevant sprites for the user's choice of animal, and adjust the starting stats for each animal. This would include size adjustments for the sprites so ensure they are reasonable sizes. The starting stats will depend on the animal's real life attributes. 

- **Animal Statistics**: Statistics will vary for animals and will affect combat, with stats like Attack, Defence, amount of health, speed. Speed will also affect traversing speed.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [x] Dependency 1 (#54 )

- [x] Sprites need to be made to add them to the screen.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Change the main player sprite for which animal is picked (Aug. 19)
- [x] Change the statistics depending on animal chosen (Aug. 20)
- [x] Display the statistics in the main game. (Aug. 22)

 
**Completion Deadline:** Aug. 23

 
# **Documentation**
- [Player wiki page](../wiki/Player)

 
# **Member**
- Name (GitHub Username) (Discord Handle)
- Andre Bissell (@AndreBissell ) (@dr.dre2725)

**Comment by AndreBissell** [comment]
Complete, although after initial deadline.
