### ISSUE TITLE
Mini-Game Extra Features (Octopus and Snake speed)

### ISSUE THREAD

**Issue by EllaBerglas** [UQcsse3200/2024-studio-2#610]
# **Description**
**Task:** [Mini-Game Extra Features (Octopus, Turtle and Snake speed)](#610).
**Feature:** [Mini-Game Polishing and Fixes](#518)

Adding additional features to the minigames including two new maze entities and speeding up the snake after each apple.

The octopus entity will spray ink over the player's screen when attacked.
The turtle entity will carry fish eggs on its back.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement octopus entity (Oct. 10)
- [x] Implement octopus entity (Oct. 10)
- [x] Speed up snake over time (Oct. 10)
- [ ] Update snake documentation to refer to this feature (Oct. 14)
- [ ] Update maze documentation to refer to the new entities (Oct. 14)
 
**Completion Deadline:** Oct 14

# **Documentation**
- [Snake Mini-game](https://github.com/UQcsse3200/2024-studio-2/wiki/Snake-Mini%E2%80%90Game)
- [Maze Mini-game](https://github.com/UQcsse3200/2024-studio-2/wiki/Underwater-Maze-Mini%E2%80%90Game)
- [Octopus JavaDoc](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/minigames/maze/entities/mazenpc/Octopus.html)
- [Turtle JavaDoc](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/minigames/maze/entities/mazenpc/Turtle.html)
 
# **Member**
- James (@jakingy) (James King)
- Rajanya (@rp3002) (Rajanya Paul Choudhury)
