### ISSUE TITLE
Furthering the map tab

### ISSUE THREAD

**Issue by BenGhahramaniUQ** [UQcsse3200/2024-studio-2#612]
# **Description**
**Task:** [Furthering the map tab](#612).
**Feature:** [Finalising the map](#513 )

This task focuses on enhancing the existing MapTabComponent to improve the user experience by adding more features and making the component more polished. The improvements include refactoring of images, introducing new borders to give the map a more refined look, and ensuring the map maintains its correct aspect ratio regardless of window size.
 
## **Example (optional)**
More detailed images representing different regions (e.g., grass, ocean, sky) will be added. A new border will frame the map, and the map layout will be responsive, adjusting to different window sizes while preserving its aspect ratio

# **Milestones**
List of steps that need to be completed for this task.
- [x] Finalise and implement new visuals (Oct. 10)
- [x] Add adherence to current window size (Oct. 12)
- [x] Final testing (Oct. 14)
 
**Completion Deadline:** Oct. 17
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
