### ISSUE TITLE
Sound implementation

### ISSUE THREAD

**Issue by ishusharma13** [UQcsse3200/2024-studio-2#613]
# **Description**
**Task:** Sound for buttons
**Feature:** Main menu sound

Implement sound effects for all the buttons in the MainMenuDisplay. This will include adding distinct sound effects when a user clicks on any button, as well as when a user hovers over the buttons
 
## **Example (optional)**
- Sound for when you click night toggle button

# **Milestones**
List of steps that need to be completed for this task.
- [x] Finalising the sound for buttons and hovering (Oct 14)
- [x] Implementing the click and hovering sound (Oct 14)
- [x] Finalising sound for close and exit (Oct 16)
- [x] Implmenting the sound (Oct 16)
- [x] Testing (Oct 16)
 
**Completion Deadline:** Oct 17

 
# **Documentation**

 
# **Member**
- Ishu (@ishusharma13 ) (discord- ishusharrma)
