### ISSUE TITLE
[Team 9 & 10] Scale-up boss in Combat

### ISSUE THREAD

**Issue by phurinjeffy** [UQcsse3200/2024-studio-2#617]
# **Description**
**Task:** [[Team 9 & 10] Scale-up boss in Combat](../issues/)
**Feature:** [[Team 9] Sprint 4 Boss](../issues/580)

Improve the presentation of the bosses in the combat screen.
Scale up the boss to make it bigger, and update animations.
Remove unused combat entity from Boss Factory.

# **Dependencies**
- #340 
 
# **Milestones**
- [x] Adjust the grid points which bosses are spawn on CombatArea
- [x] Adjust the scaling size of the bosses entity
- [x] Testing and adjustments (Oct. 16)

**Completion Deadline:** Oct. 16

# **Member**
- Peeranat Leelawattanapanit (@paulpleela on GitHub) (pa._.l on Discord)
- Phurin Vanasrivilai (@phurinjeffy) (jeff.)
