### ISSUE TITLE
Inventory UI

### ISSUE THREAD

**Issue by mitsudz** [UQcsse3200/2024-studio-2#62]
# **Description**
**Task:** [Inventory Render Component](#3 ).
**Feature:** [Items and Inventory](#3 )

A class to support various types of inventory's (e.g. combat inventory, general inventory etc.). Should implement abstract interface for handling using, adding and removing from inventory. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create an Inventory Component for the Player Entity to hold (18 Aug)
- [ ] Test Inventory Component (18 Aug)
- [x] Create Inventory Render Component and implement textures (19 Aug)
- [x] Ensure Inventory is renderable on screen via button (e.g. 'u') press (19 Aug)
- [ ] Create inventory button on screen  (20 Aug)
- [ ] Test Render Component for mouse click on Inventory button (20 Aug)
- [ ] Write wiki (21 Aug)
 
**Completion Deadline:** Aug. 21

# **Documentation**
- [Inventory Wiki Page](https://github.com/UQcsse3200/2024-studio-2/wiki/Inventory) (NOT YET UPDATED TO INCLUDE RENDER INFORMATION)
 
# **Member**
- Name (Github Username) `Discord Username`
- Mittun (@mitsudz ) `mitsudz`
