### ISSUE TITLE
[Team 9 & 10] Add boss combat music 

### ISSUE THREAD

**Issue by phurinjeffy** [UQcsse3200/2024-studio-2#620]
# **Description**
**Task:** [[Team 9 & 10] Fix Combat Audio](../issues/620)
**Feature:** [[Team 9] Sprint 4 Boss](../issues/580)

Fix issue when exiting combat, the main game music plays multiple times.
Add music unique to the boss fights.

# **Milestones**
- [x] Update to use the AudioManager class to play/pause music
- [x] Add combat music specifically for the bosses
- [x] Testing and adjustments (Oct. 16)

**Completion Deadline:** Oct. 16

# **Member**
- Peeranat Leelawattanapanit (@paulpleela on GitHub) (pa._.l on Discord)
- Phurin Vanasrivilai (@phurinjeffy) (jeff.)
