### ISSUE TITLE
Map Obstacles

### ISSUE THREAD

**Issue by chloemicah** [UQcsse3200/2024-studio-2#622]
# **Description**
**Task:** [Map Obstacles](#3).
**Feature:** [Finalising the Map](#513)

Implement appropriate Map Obstacles on the map in their respective Kingdoms to improve overall aesthetic appeal and add onto the difficulty of the game.

Players cannot traverse due to a Collider Function (i.e. Player cannot run through the tree item, has to run around the item). Whilst, this design choice does not affect player statistics, it will add complexity to player navigation when being chased by an enemy.
 
## **Example (optional)**
- **Trees**: Land Kingdom
- **Seaweed**: Ocean Kingdom
- **Starfish**: Ocean Kingdom
- **Cloud**: Sky Kingdom

# **Dependencies**
- [ ] Map Generation (#23)
- [ ] Ocean Kingdom (#353)
- [ ] Sky Kingdom (#355)

e.g.
- [ ] Pixel arts created for each item.
- [ ] Pixel art .png's need to be imported
- [ ] Items to be spawned on Map
- [ ] Items to be spawned in correct areas/Kingdoms on the Map
- [ ] Collider Function adjusted 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create Pixel Art (Oct. 7)
- [ ] Import Pixel Art (Oct. 8)
- [ ] Spawn Pixel Art (Oct. 8)
- [ ] Collider Adjustments (Oct. 16)
- [ ] Testing (Oct. 16)
 
**Completion Deadline:** Oct 16

e.g.
- [ ] Initial design of `Armour` created and documented on wiki (Aug. 19).
- [ ] Unit tests implemented for `Armour` (Aug. 20).
- [ ] `Armour` class implemented and tested (Aug. 23).
- [ ] Documentation of `Armour` updated on wiki (Aug. 23).
 
# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2024-studio-2/wiki/Map-Design)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- @chloemicah
- @JonnaHerman
