### ISSUE TITLE
[Team 5] Fixing quest implementation and accounting for biomes

### ISSUE THREAD

**Issue by MargoCode** [UQcsse3200/2024-studio-2#635]
# **Description**
**Task:** Fixing quest implementation and accounting for biome .
**Feature:** [Quests](#67)

Updating the quest design to better suit existing biome setup and fix non working quests.
 
# **Dependencies**
- [x] Quest Completion and System Enhancements (#516)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Changing quest design (NPC, enemies and items) to suit biome setup (Oct. 16)
- [x] Adding mini game quests progression triggers (Oct. 16)
- [x] Fixing quest order to suit final boss summoning triggers (Oct. 16)
- [x] Adding final boss summoning triggers (overlooked last sprint) (Oct. 16)
- [x] Fixing final boss defeat quest triggers (not working currently) (Oct. 16)
 
**Completion Deadline:** Oct. 17

# **Documentation**
[Quests Description] (https://github.com/UQcsse3200/2024-studio-2/wiki/Quests)

# **Member**
Reemzheem Hossain (@reemmi)
Maree Robinson (@MargoCode)
