### ISSUE TITLE
[Team 2] Add StealTask Unit Tests

### ISSUE THREAD

**Issue by nownver** [UQcsse3200/2024-studio-2#637]
# **Description**
**Task:** [Add StealTask Unit Tests](#)
**Feature:** [Enemy NPC Improvement and Cleanup](https://github.com/UQcsse3200/2024-studio-2/issues/647) 

This task focuses on writing unit tests for the StealTask class, which defines a special interaction for pigeons and other NPCs that allows them to collect items around the map. The tests will verify the correct behavior of pigeons as they move to collect items, as well as ensure proper functionality for other NPCs like Green Macaw, Chicken, Bear, and Frog. The goal is to validate that the factory initializes enemies with their expected properties and that pigeons perform their stealing behavior correctly.

# **Dependencies**

- [x] (#156 )
 
# **Milestones**

- [x] Write unit tests for enemy creation, focusing on StealTask for pigeon interaction. (Oct.14)
- [x]  Ensure pigeons exhibit proper item collection behavior in tests, including movement to item location and removal of the item from the map. (Oct.14)
- [x] Refactor the EnemyFactory if necessary based on test results. (Oct.15)
- [x] Finalize the tests, run coverage analysis, and submit for review. (Oct.16)
 
**Completion Deadline:** Oct 16
 
# **Documentation**
- [Programming guide](https://github.com/UQcsse3200/2024-studio-2/wiki/Enemy-NPCs-Programming-Guide)
- [User documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Enemy-NPC's)
- [Steal Task Tests](https://github.com/UQcsse3200/2024-studio-2/wiki/Sprint-4-Test-Plan)
 
# **Member**
- Jade (@nownver) Urawee Thani
- Lily (@jl1324) Lily Ji
