### ISSUE TITLE
Team 5: QuestManager

### ISSUE THREAD

**Issue by theboah** [UQcsse3200/2024-studio-2#64]
# **Description**
**Task:** QuestManager
**Feature:** Team 5: Progression (#13 )

QuestManager is a component that setups and tracks quests for the player including secret and achievement quests. The QuestManager loads quests based on the gamestate and achievement (lifetime) data.
 
# **Dependencies**
- [x] Team 5: Quests (#67)
- [x] Team 5: Tasks (#68 )
- [x] Team 5: Global Event Service (#47 )
- [x] Team 5: Saving (#15  )
 
# **Milestones**
**Completion Deadline:** Aug. 29
List of steps that need to be completed for this task.
- [x] Implement basic functionality (Aug. 16)
- [x] Write access methods for other entities (Aug. 20)
- [x] Saving and Loading Quests (22 Aug.)
- [x] (Integration) Quest dependant actions (25 Aug.)
- [x] Functionality Completed (25th Aug.)
- [x] User Testing Started (25th Aug.)
- [x]  All Documentation Completed (26th Aug.)
- [x]  All Unit Tests Completed (27th Aug.)
- [x] User Testing Completed (29th Aug.)
- [x]  Reference Assets (29th Aug.)

# **Documentation**
- [QuestManager](../wiki/QuestManager)
 
# **Member**
- e.g. Noah Stevens (@theboah)
Reemzheem Hossain (@reemmi)
