### ISSUE TITLE
[Team 2] Resolve Reliability Issues

### ISSUE THREAD

**Issue by nownver** [UQcsse3200/2024-studio-2#643]
# **Description**
**Task:** [Resolve Reliability Issues](#).
**Feature:** [Feature which this tasks contributes to implementing](#2)

This task focuses on fixing all reliability issues present in the project. The goal is to ensure that the existing code functions as expected without introducing any breaking changes.

# **Milestones**
- [x] Identify and fix reliability issues across the project files. (Oct. 10)
- [x] Ensure no game behavior or functionality has been altered after the fix. (Oct. 10)
- [x] Run existing unit tests to verify no regressions or new errors have been introduced. (Oct. 160)
- [x] Perform a self-review and add comments to areas where the code might be difficult to understand. (Oct. 11)
- [x] Finalize changes, ensure they meet style guidelines, and submit for review. (Oct. 11)
 
**Completion Deadline:** Oct. 11

# **Member**
- Lucas (@LucasRyall) Lucas Ryall
