### ISSUE TITLE
[Team 5] AchievementPopup, QuestPopup Improvements

### ISSUE THREAD

**Issue by jaden-z-fng** [UQcsse3200/2024-studio-2#649]
# **Description**
**Task:** [Achievement and quest popup improvements](#649)
**Feature:** [Quest Completion and System Enhancements](#516)

Improve the visuals of both the AchievementPopup and QuestPopup classes. Currently, both implementations are fairly basic, and improvements can be made to both the graphical fidelity of the popups, as well as their appearance on screen.
 
# **Dependencies**

- [x] The achievements.json file must be up to date with new npcs and quests.

# **Milestones**

- [x] New graphics created (Sep. 10).
- [x] Graphics integrated into existing functionality, old functionality removed (Sep. 12).
- [x] Animations added to graphics (Sep. 14).
- [x] Formatting and linting checked (Sep. 16).
 
**Completion Deadline:** Sep. 17

# **Documentation**
- [Quests](https://github.com/UQcsse3200/2024-studio-2/wiki/Quests)
- [QuestPopup](https://github.com/UQcsse3200/2024-studio-2/blob/main/source/core/src/main/com/csse3200/game/components/quests/QuestPopup.java)
- [AchievementPopup](https://github.com/UQcsse3200/2024-studio-2/blob/main/source/core/src/main/com/csse3200/game/components/quests/AchievementPopup.java)
 
# **Member**
- Zhengde Fang (@jaden-z-fng)
