### ISSUE TITLE
Team 5: QuestTracker

### ISSUE THREAD

**Issue by theboah** [UQcsse3200/2024-studio-2#65]
# **Description**
**Task:** [QuestTracker](#65).
**Feature:** [Team 5: Progression](#13)

QuestTracker is a UI componant that presents information about the users current non-secret non-achievement quests. This includes descriptions, icons, task descriptions and current progress on the task and quest.

# **Dependencies**
- [x] Quest (#67 )
- [x] Task (#68 )
- [x]  QuestManager  (#64)

# **Milestones**
**Completion Deadline:** Aug. 25
List of steps that need to be completed for this task.
- [x] QuestTracker: (Integration) Pausing Integration completed (22 Aug.)
- [x] QuestTracker: Quest Tracker screen opens (23 Aug.)
- [x] QuestTracker: Quest Tracker presents quests details and current progression (24 Aug.)
- [x] QuestTracker: Quest details screen (per quest) (25 Aug.)
 
# **Documentation**
- [QuestTracker](../wiki/QuestTracker)

 
# **Member**
- Lachlan (@lellis0406 )
- Noah (@theboah )
- Reemzheem (@reemmi)
