### ISSUE TITLE
[Team 10] Combat Enemy Move Selector

### ISSUE THREAD

**Issue by paulpleela** [UQcsse3200/2024-studio-2#660]
# **Description**
**Task:** [Combat Enemy Move Selector]()
**Feature:** [Cleaning Up, Minor Improvements, and Bug Fixes](../issues/539)

Currently enemy moves in combat are selected randomly. This task aims to create a more sophisticated algorithm to select the enemy's combat move based on stats (player/enemy health, hunger, etc.). This should increase engagement between the player and enemy in each combat turn.

# **Dependencies**
- #171 

# **Milestones**
- [x] Add conditions to filter out moves that don't have impact, e.g. healing when health is full. (Oct. 15)
- [x] Implement a weighted randomisation algorithm. (Oct. 15)
- [x] Add move probabilities based on stats, e.g. the enemy has a higher chance of attacking if the player's health is low. (Oct. 16)
- [x] Handle conditions for selecting / disabling Boss Special Moves. (Oct. 16)
- [x] Testing and documentation. (Oct. 17)
 
**Completion Deadline:** Oct. 17

# **Documentation**
- [Combat Manager](../wiki/CombatManager)

# **Member**
- Peeranat Leelawattanapanit (@paulpleela on GitHub) (pa._.l on Discord)
