### ISSUE TITLE
Team 5: Quests

### ISSUE THREAD

**Issue by theboah** [UQcsse3200/2024-studio-2#67]
# **Description**
**Task:** [Quest](#67).
**Feature:** [Team 5: Progression](#13)

Quests is a class and feature that involves progressive tasks that the player must complete to recieve some reward. The class contains an array of tasks and is managed by QuestManager. This task includes the creation of the actual tasks and implementation of its hooks in the other related tasks
 
## **Example (optional)**
- **“The stomping”**: 1st Kingdom Kangaroo Boss quest
		Tasks (Talk to Guide, Following his teachings, Collect food for the Guide, Watch Guides death, Listen to Guide’s Deathrattle, Explore the wilds, Ask animals about the Kangaroo Boss, Learn about the Eucalyptus sword, Retrieve the weapon, Return to the last known location of the Kangaroo boss, Defeat the Kangaroo boss)

# **Dependencies**
- [x] Tasks (#68 )

# **Milestones**
**Completion Deadline:** Aug. 25
List of steps that need to be completed for this task.

- [x] Abstract Quest and extend abstract QuestHidden from there abstract questBasic, questAchievement, (21 Aug.) 
- [x] Story: Quest design principles (22 Aug.)
- [x] Story: Sprint 1 Quest Brainstorming (22 Aug.)
- [x] Story: Sprint 1 Quest Design (22 Aug.)
- [x]  (Integration) Completion of quests tutorial ("First steps" & "2 Step Quests" covered for this sprint (25th Aug.)
- [x] (Integration) Completion of Final Boss Quest (25th Aug.)

 
# **Documentation**
- [Quests](../wiki/Quests)
- Design Document https://docs.google.com/document/d/1wU8tCjtxcwhCAz9ChNnB_ZTt52dNG77u0xnt-aH6nrA/edit?usp=sharing
 
# **Member**
- Maree (@MargoCode )
- Noah (@theboah )
