### ISSUE TITLE
Team 5: Tasks

### ISSUE THREAD

**Issue by theboah** [UQcsse3200/2024-studio-2#68]
# **Description**
**Task:** [Team 5: Tasks](#68).
**Feature:** [Quests and Progression](#13 )

Tasks are the specific tasks that make up a progression point in a quest. Each task has a required number of event triggers that it tracks have occured.
 
## **Example (optional)**
- **Task("steps", "Take your first steps", "Just start moving!", 5);**: Players walking is a basic task and this Task tracks that 5 walking actions have occured before it notes itself as complete.

# **Dependencies**
- [x] Team 5: Global Event Service (#47 )

# **Milestones**
**Completion Deadline:** Aug. 25
List of steps that need to be completed for this task.
- [x] Basic implementation (16 Aug.)
- [x] (Integration) Integrations with NPC (25 Aug.)
- [x] Functionality Completed (25th Aug.)
- [x] User Testing Started (25th Aug.)
- [x] Unit Tests Completed (27th Aug.)
- [x] Testing Completed (29th Aug.)
- [x] Reference Assets (29th Aug.)

# **Documentation**
- [Tasks](../wiki/Tasks)
 
# **Member**
- Noah Stevens (@theboah )
- Reemzheem Hossain (@reemmi)
