### ISSUE TITLE
Team 5: Achievements

### ISSUE THREAD

**Issue by theboah** [UQcsse3200/2024-studio-2#69]
# **Description**
**Task:** [Team 5: Achievements](#69).
**Feature:** [Team 5: Progression](#13)

Achievements are life time records of the completion of quests within the game. This may include specific Achievement quests which serve only to denote an achievement for instance the defeat of 100 enemies. These achievements are store seperately from the current save of the game.
 
## **Example (optional)**
- **First Steps**: Players first steps in the game are recorded as an achievement with an assosciated description and icon that they can see in the achievements screen on the main menu.

# **Dependencies**
- [ ] Team 5: Quests (#68)
- [ ] Team 5: QuestManager (#64 )

# **Milestones**
**Completion Deadline:** Aug. 25
List of steps that need to be completed for this task.
- [ ] Achievements: Tutorial achievements creation (22 Aug.)
- [ ] Achievements: Achievements Screen in Main menu (22 Aug.)
- [ ]  Achievements :Saving and Loading Achievements (22 Aug.)
- [ ] Functionality Completed (25th Aug.)
- [ ] User Testing Started (25th Aug.)
- [ ] Documentation Completed (26th Aug.)
- [ ] Unit Tests Completed (27th Aug.)
- [ ] Testing Completed (29th Aug.)
- [ ] Reference Assets (29th Aug.)

 
# **Documentation**
- [Achievements](../wiki/Achievements)
 
# **Member**
- Jaden (GitHub Username) (Slack Handle)
