### ISSUE TITLE
[Team 10] Combat System

### ISSUE THREAD

**Issue by owenrharding** [UQcsse3200/2024-studio-2#7]
# **Description**
Implement a rudimentary turn-based combat system - heavily Pokemon inspired. 
A Player entity battles an Enemy entity. The Player controls their entity's moves, while the Enemy operates on a computer-generated program, with the goal of depleting the opponent's health to zero to win. 
Unique stats and attack ordering will influence the outcome of each battle.

## SubFeature/component
- Incorporates a 'Player' entity battling an 'Enemy' entity.
- Player will be able control Player entity's 'moves' - which would be available from a discrete set of entity-inherited moves.
- Enemy will act based on a computer-generated program - simualting AI behaviour.
- 'Winning' system - based on health depleting to zero. This would be dependent on the stats unique to each player and enemy entities.
- Attack ordering.
- [x] #80
- [x] #85 
- [x] #78 
- [x] #75 
- [x] #73 
- [x] #127 

# **Dependencies**
- Requires (#4) and (#11) entities to be implemented.

# **Milestones**
- [x] Create new combat screen. [Aug 20]
- [x] Implement trigger to bring up new combat screen. [Aug. 22]
- [x] Implement basic 'win' / 'lose' exiting and returning to Main Game Screen [Aug. 24]
- [ ] Implement unit testing for combat screen entering/extiting. [Aug. 26]
- [ ] *If there's time* add scaffold for combat functionality (player vs enemy turn-based system). [Aug. 26]
- [ ] Integration with Player, Enemy, and Final Boss Teams. [Aug. 27]

**Completion Deadline:** Aug. 29

# **Members**
- Owen Harding (owenrharding on GitHub) (owen8232 on Discord)
- Jonah Ting (Jonah on GitHub) (Jaycoba1 on Discord)
- Yessica Samtani (Jessica-s on GitHub) (yessica3301 on Discord)
- Peeranat Leelawattanapanit (paulpleela on GitHub) (pa._.l on Discord)
- Sneha Zazen Theruvile Sajan (sneha-zazen on GitHub) (zaza7_13 on Discord)
