### ISSUE TITLE
Snake Mini-Game Documentation and Designs

### ISSUE THREAD

**Issue by rp3002** [UQcsse3200/2024-studio-2#70]
# **Description**
**Task:** Documentation and Design(#70)
**Feature:** Mini Games(#6)
 
## **Example (optional)**

# **Dependencies**
- [x] Code completion for sprint 1

# **Milestones**
- [x] Git wiki completion (Aug 28)
- [x] Method comments for java doc (Aug 26)
- [x] Task and feature ticket documentation (Aug 19)
- [x] Code styling (Aug 26)
- [x] UML diagrams (Aug 28)
 
**Completion Deadline:** Aug. 28
 
# **Documentation**
- put wiki and javadoc link etc
 
# **Member**
- Rajanya Paul Choudhury (@rp3002) 
- Ella Berglas (@EllaBerglas)
- Manandeep Singh (@24msingh24)

**Comment by rp3002** [comment]
Completed in Sprint 1
