### ISSUE TITLE
Snake Mini-Game Grid and Apple Spawning

### ISSUE THREAD

**Issue by 0NATE4** [UQcsse3200/2024-studio-2#72]
# **Description**
**Task:** Snake Grid and Apple Spawnking (#72)
**Feature:** Mini Games (#6)

This task involves implementing the snake grid and apple spawning, essential for the minigame. The grid enables gameplay, while the apple spawning mechanism allows the snake to eat, grow, and score points.

# **Dependencies**

- [x] Minigame screen pop up for the game to take place on.

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement Grid (Aug. 17)
- [x] Test Grid (Aug. 18)
- [x] Implement Apples (Aug. 18)
- [x] Test Apples and Grid (Aug. 19)
 
**Completion Deadline:** Aug. 20

# **Documentation**
- [Apple](https://github.com/UQcsse3200/2024-studio-2/wiki/Apple-Component-(Snakes's-Food))
- [Snake Grid](https://github.com/UQcsse3200/2024-studio-2/wiki/Snake-Grid)
- [SnakeGrid](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/components/minigame/snake/SnakeGrid.html)
- [Apple](https://uqcsse3200.github.io/2024-studio-2/com/csse3200/game/components/minigame/snake/Apple.html)

 
# **Member**
- [0NATE4](https://github.com/0NATE4)
