### ISSUE TITLE
Team 10: Combat Screen

### ISSUE THREAD

**Issue by yessica-s** [UQcsse3200/2024-studio-2#73]
# **Description**
**Task:** Combat Screen (#73).
**Feature:** Combat Feature (#7)

Implementing new combat screen UI to be invoked when player comes into contact with enemies. Combat Screen should present combat options throuhg buttons to users e.g. weapons, attack options, food/potions. Create base combat screen area.

# **Dependencies**
- Textures need to be created for new button designs
- Image designs to be chosen, implemented, and image files to be added to project directory
- Combat Screen to be added as screen type in Gdx.game file
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create base combat screen (Aug. 19)
- [x] Implement buttons for combat options (Aug. 23)
- [x] Implement event handlers and action listeners for buttons; contribution to win/loss condition (Aug. 29)

**Completion Deadline:** Aug 29
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Yessica Samtani (@yessica-s)
