### ISSUE TITLE
Team 10: Combat Trigger/Exit From Main Screen

### ISSUE THREAD

**Issue by owenrharding** [UQcsse3200/2024-studio-2#75]
# **Description**
**Task:** [Combat Trigger/Exit](#3).
**Feature:** [Combat System](#7)

Implement pre- and post-combat conditions that allows a new combat encounter to be instantiated. A trigger which creates a new combat encounter needs to be modular, so it can be easily called by other teams' conditions, as well as preparing for integration with Player and Enemy teams in later sprints. Outside the scope of the combat itself, a both win and loss scenarios have to be established for post-combat handling.
The win condition of #9 for this sprint is dependent on the combat system being triggered and exiting upon a win/loss, so this task ticket is aiming to be completed early.

# **Dependencies**
- [x] Requires Combat Screen components to be implemented. (#73)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a way to enter a new combat screen from the MainGame screen. (Aug. 19)
- [x] Create a way to exit from the combat screen to the MainGame screen (Aug. 20)
- [x] Create a win condition/scenario on exit of combat screen. (Aug. 22)
- [x] Create a loss condition/scenario on exit of combat screen. (Aug. 23)
 
**Completion Deadline:** Aug. 23

# **Member**
- Owen Harding (@owenrharding) (owen8232)
