### ISSUE TITLE
Start Screen / Exit button

### ISSUE THREAD

**Issue by ishusharma13** [UQcsse3200/2024-studio-2#76]
# **Description**
**Task:** Exit Button 
**Feature:** Allows to exit the game from the start menu.

This exit button will allow a player to quit the game, typically after confirming the action to avoid accidental closures.

# **Dependencies**

- [x]  It should be integrated with the game's UI system to ensure it displays correctly and responds to user inputs.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Planning and design of button  (Aug. 19)
- [x] Setup and Preparation (Aug. 23)
- [x] Implementation (Aug. 25)
- [ ] Integrate and testing  (Aug. 27)
- [ ] Finalization (Aug.29) 
 
**Completion Deadline:** Aug. 26
 
# **Documentation**
To be updated
 
# **Member**
- Ishu (@ishusharma13 ) (Discord: ishusharrma)
- Tarushi (@TarushiG ) (Discord: tarushigera)
