### ISSUE TITLE
Team 10: Adding functionality to combat screen

### ISSUE THREAD

**Issue by yessica-s** [UQcsse3200/2024-studio-2#78]
# **Description**
**Task:** Combat button and screen functionality (#78)
**Feature:** Combat Screen (#7)

Add functionality to the buttons through actionListeners and event handling and integrate with a combat function to impact stats like health, inventory etc. E.g. bag button should display inventory and hit button should conduct some attack on enemy players.

# **Dependencies**

- [ ] Base Combat Screen (#73)
- [ ] Combat logic
- [ ] Inventory loading

 
# **Milestones**
- [ ] Create actionListeners for buttons
- [ ] Provide functionality for attack buttons
- [ ] Provide functionality to allow player to access inventory during battle
 
**Completion Deadline:** (end date of sprint 2)
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Yessica (@yessica-s  )

**Comment by sneha-zazen** [comment]
created a new issue for sprint 2
