### ISSUE TITLE
[Team2] Have the enemies initiate combat and pause main game

### ISSUE THREAD

**Issue by LucasRyall** [UQcsse3200/2024-studio-2#79]
# **Description**
**Task:**  Have the enemies initiate combat and pause main game
**Feature:** Enemy NPCs 

All enemies will be able to initiate combat, which will be cause by the enemy being within some minimum range of the player character (accomplished through detecting collision via the physics engine, where enemies have a hitbox larger than their texture which initiates combat). This minimum range will be dependent on the type of enemy to allow for some variability in the behavior of enemies outside of combat.
When the enemy NPC initiates combat, the main game will need to be paused so that nothing else can advance, and then switch screens to the combat screen. 

# **Dependencies**
- [x] #78, This task does not cover any of the behavior of the combat screen, but rather having the enemies detect that the player is in range to initiate combat, and then changing to the combat screen. Hence, in order for this to not cause the game to crash the combat screen must already be created and be possible to transfer to.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement a method of pausing the main game so that nothing happens while combat takes place (Aug 20)
- [x] Have the enemies be able to trigger the above, and make a call that switches to the combat screen (Aug 21)
- [x] Enemies have a box of customizable size, which if the player enters causes the game to pause and switch to the combat screen (Aug 22)
- [x] Tests and documentation (Aug 28)
 
**Completion Deadline:** Aug 22, Aug 28 for tests and documentation.

# **Documentation**
***TO DO***
 
# **Member**
- LucasRyall (Lucas Ryall)
