### ISSUE TITLE
[Team 8] Map

### ISSUE THREAD

**Issue by BenGhahramaniUQ** [UQcsse3200/2024-studio-2#8]
# **Description**
In this feature, the initial Land Kingdom map will be created using tiling algorithms.  

Although Sprint 1 focuses on initiating and implementing the forest map, elements from the other kingdoms/maps (water and air) will be visible. Additionally, some of the maps will be procedural generated to provide variation.

Maps will be stored in grids instead of a massive texture to improve the Performance.

## SubFeatures
- [x] Generate Initial/Forest Map (#23)
- [x] Integrate Wave Algorithm into Map (#81)
- [x] Animate Tiles (#88)
- [x] Interactive Tile Collision (#89)

The Player can enter each kingdom through walking towards a corner/object. i.e. player can walk towards the ocean to go into Water Kingdom, or player can walk toward a tall tree to enter the Air Kingdom.
 
## **Examples**
- In Pokemon, when the player enters a room, the screen fades to black and transitions into the new 'map'/screen.

- The main map allows the player move freely across areas, battle, play mini games, expand the team, enter a certain area or explorw the map.

- Kindoms map has no difference to the main map, but require player the go to certain area on the main map to enter (accomplish task, solve puzzle, or defeat boss)

- Use algorithm such as wave function collapse to generate the map.

# ** Dependencies**
Initiating mini-games, [Team 7] Mini Games (#6)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.

- [x] Usable map (Aug. 21) 
- [ ] Map Objects (loot) (Aug. 24) 
- [ ] Refinements and Integration (Aug. 29) 

**Completion Deadline:** Aug. 30

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [[User documentation](https://github.com/UQcsse3200/2024-studio-2/wiki/Map)](../wiki/Terrain)

# **Members**
BenGhahramaniUQ (@BenGhahramaniUQ)
Howie (@Howard-12)
Praneet (@praneetdhoolia)
JonnaHerman (@JonnaHerman)
Chloe Catane (@chloemicah)

**Comment by praneetdhoolia** [comment]
Wave function partially implemented.
