### ISSUE TITLE
Integrate Wave Algorithm into Map

### ISSUE THREAD

**Issue by chloemicah** [UQcsse3200/2024-studio-2#81]
# **Description**
**Task:** [Integrate Wave Algorithm into Map](#3).
**Feature:** [[Team 8] Map](#8)

A forest map would be procedurally generated using tiling algorithms. The tiles will be filled in with map objects such as grass, water, etc. These tiles should have a base (for the terrain) and a tile object (for items such as trees, rocks, etc.). Bounds will be established so that players can only roam within a certain area.
 
## **Example (optional)**
- **Tiling Algorithm**: Players can roam around the Map, outside the current boundaries.
- **Bounds**: For the forest map, fences/trees will represent the bounds of the game.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Tiles needs to be created for trees/fences/grass/water.
- [ ] Generate Initial/Forest Map (#23)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create graphics and tile assets for trees and fences (Aug 19)
- [ ] Procedural tiling ready (Aug. 22)
- [ ] Set map bounds (Aug 23)
- [ ] Map Objects randomized on tiles (Aug. 25)
- [ ] Testing and Documentation of 'Map' is updated on wiki (Aug. 28)
 
**Completion Deadline:** Aug. 28
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
Howie (@Howard-12)
Praneet (@praneetdhoolia)
BenGhahramaniUQ (@BenGhahramaniUQ)
