### ISSUE TITLE
[Team 2] Implement the stats for enemies, and the moves that they will have in combat

### ISSUE THREAD

**Issue by JackMccabe2** [UQcsse3200/2024-studio-2#82]
# **Description**
Task: Implement the stats for enemies, and the moves that they will have in combat
Feature: Enemy NPCs

Every enemy NPC instance will have associated stats. These will mirror the main player's stats, but be a fraction of the player's total. Statistics will also vary depending on what animal it is. For example, a chicken would have a lower attack stat than a bear. 
Speaking of the stats, we will incorporate: Attack, Defense, Health and Speed. 
There will be a slight randomization (perhaps 10%) for all stats, including a slight gameplay variability. 
The associated stats will be incorporated so that when the user interacts with an enemy NPC and initiates a battle, the stats will transfer to the combat screen and the battle. 
Additionally, enemy NPCs will have an associated move set which will depend on the animal type, but in a similar way to the stats, will need to be transferred to the combat screen.

# **Dependencies**
#78 Adding functionality to combat screen, to verify this task is working fully, it will need to be tested across the main screen and the combat screen.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Identify the best way to transfer statistics over to the combat screen (Aug. 19)
- [x] Implement the method, and verify stats appear in-game (Aug. 21)
- [x] Verify stats transfer over, and are usable, on the combat screen (Aug. 22)
 
**Completion Deadline:** Aug. 22

# **Documentation**
To Do...
 
# **Member**
- Jack (JackMccabe2) (Jack McCabe)
