### ISSUE TITLE
[Team 2] Idle animation and a texture for the first animals

### ISSUE THREAD

**Issue by nownver** [UQcsse3200/2024-studio-2#83]
# **Description**
**Task:** [Idle animation and a texture for the first animals](#83).
**Feature:** [Enemy Feature](#11 )

Enemies remain invisible and do not spawn until the player gets within a certain range. When the player enters the designated range, the enemies will spawn and become visible. This will be optimized to ensure smooth spawning and will be configurable to adjust the detection range based on game difficulty or level design.
 

# **Dependencies**

- [initiating the enemy characters on start of level] Dependency 1 (#8)

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial concept sketches for idle animation and texture (Aug. 23)
- [x] Approval of concept designs by the art team (Aug. 24)
- [x] Implementation of idle animation and creation of texture (Aug. 25)
- [x] Player Detection (Aug. 26)
- [x] Spawn animation (Aug. 26)
- [x] Integration of animation and texture into the game (Aug. 26)
- [x] Testing and adjustments (Aug. 27)

**Completion Deadline:** Aug. 28
 
# **Documentation**
- [Spawn Animation](../wiki/Spawn-animation)
 * [Chicken (Enemy NPC)](https://github.com/UQcsse3200/2024-studio-2/wiki/Chicken-(Enemy-NPC))
 
# **Member**
- Jade (@nownver) (Urawee Thani)
- Lily (@jl1324) (Lily Ji)
