### ISSUE TITLE
Implement Experience Health Bar for Main Game Screen

### ISSUE THREAD

**Issue by Jared946** [UQcsse3200/2024-studio-2#84]
# **Description**
**Task:** [XP bar implementation](#84)
**Feature:** [Feature-1: Player Statistics](#10 )

Implementation of a player XP bar, showing the player's level and their progression towards the next level. The bar has a pixelated design and will fill up and reset once the player levels up.
 

# **Dependencies**

- [x] Feature-1: Player Statistics (#10 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Graphical design of the XP bar (Aug. 18)
- [x] Design and implementation of XP bar (Aug. 21)
- [x] Implementation of XP bar fill-up animation (Aug. 22)
- [x] XP bar completed and tested (Aug. 23)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Jared (@Jared946)

**Comment by ChristianMario4** [comment]
Feature implemented and merged to main.
