### ISSUE TITLE
[Team 2] Implement Tests and Remove Bugs 

### ISSUE THREAD

**Issue by jl1324** [UQcsse3200/2024-studio-2#86]
# **Description**
**Task:** [Implement tests and remove bugs]
**Feature:** [Enemy NPCS](#11 )

Debug and refine the sub-features implemented for the first sprint, i.e. enemy combat and idle animation features in the game. This task involves identifying and fixing issues with the enemy's ability to initiate combat, ensuring they correctly spawn from being "invisible", initiate combat with the player and visually testing that their idle animation looks correct. The goal is to create a smooth experience and expected enemy behaviour based on sub-feature functionality.

# **Dependencies**
- [x] Enemy NPC idle animation and texture sub-feature (#83 )
- [x]  Enemy stat and combat move implementation (#82 )
- [x] Enemy combat initiation + main game pausing (#79 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement unit tests for enemy stats and combat moves (Aug 22)
- [x] Implement unit tests for enemy combat initiation (Aug 27)
- [x] Visually testing on idle animation and enemy NPC spawn functionality (Aug 27) 

**Completion Deadline:** Aug. 28
 
# **Documentation**
- [Enemy NPC's](https://github.com/UQcsse3200/2024-studio-2/wiki/Enemy-NPC's)
 
# **Member**
- @nownver) (Urawee Thani)
- (@LucasRyall) (Lucas Ryall)
- (@mhUnt3rS) (Milo Hunter)
- (@jl1324) (Lily Ji)
- (@JackMccabe2) (Jack McCabe)
