### ISSUE TITLE
Snake Movement and Keyboard Input

### ISSUE THREAD

**Issue by jakingy** [UQcsse3200/2024-studio-2#87]
# **Description**
**Task:** Implement snake movement and keyboard input (#87)
**Feature:** Mini Games (#6)

This task involves capturing keyboard inputs from the player and using those inputs to move the snake around the grid. If the snake moves over an apple, it will also need to grow.

# **Dependencies**
- [x] Snake grid and apples implemented (#72)
- [x] Minigame screen pop up for the game to take place on.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Capture keyboard input (Aug. 20)
- [x] Implement snake movement (Aug. 22)
- [x] Test snake movement (Aug. 22)
- [x] Implement snake growth (Aug. 23)
- [x] Test snake growth (Aug. 23)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- James (@jakingy)
