### ISSUE TITLE
Animated tiles

### ISSUE THREAD

**Issue by BenGhahramaniUQ** [UQcsse3200/2024-studio-2#88]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

The task involves implementing animations for tiles on the map. This will be done by cycling through similar-looking PNG images to create smooth animations for elements like water, grass, clouds, etc. The animation will help bring the map to life and provide visual feedback based on player interaction or environmental changes.

 
## **Example **
Grass sways back and forth when the player is nearby, water ripples along the shore, clouds move subtly across the sky.

For example, water tiles will alternate between two or more textures to simulate movement, giving the appearance of a flowing body of water.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

TODO
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Aug. 19)
- [ ] Create animated tile assets (e.g., sequence of PNGs for water, grass, clouds) (Aug. 20).
- [ ] Implement the tile animation cycling mechanism (Aug. 21).
- [ ] Integrate animated tiles into the map system (Aug. 22).
- [ ] Finalize animation behaviour based on player proximity or environmental changes (Aug. 23). 

 
# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)

 
# **Member**
BenGhahramaniUQ (@BenGhahramaniUQ)
Howie (@Howard-12)
Praneet (@praneetdhoolia)
JonnaHerman (@JonnaHerman)
Chloe Catane (@chloemicah)
