### ISSUE TITLE
Map Transition 

### ISSUE THREAD

**Issue by BenGhahramaniUQ** [UQcsse3200/2024-studio-2#90]
# **Description**
**Task:** [Map Transition](#3).
**Feature:** [Map](#8 )

The task involves implementing map transitioning mechanisms that allow players to move between different areas or kingdoms on the map through teleport shrines or normal gates. This includes creating teleportation points (shrines) that move players instantly to designated locations and creating gates that transition the player to different areas of the map after interacting with them. The transitions should be smooth and seamless, ensuring no loading screens during gameplay.

 
## **Example (optional)**
Teleport Shrines: When the player interacts with a teleport shrine (e.g., an ancient ruin), they are instantly transported to a specific location on the map, such as another kingdom or a distant area.
Gates: When the player interacts with a gate, they are taken to the corresponding map section (e.g., passing through a gate moves the player from the forest kingdom to the water kingdom).

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 (Aug. 19)
- [ ] Step 2 (Aug. 20)
- [ ] Step 3 (Aug. 23)
- [ ] Step 4 (Aug. 23)
 
**Completion Deadline:** Aug. 23

e.g.
- [ ] Usable map (Aug. 21)
- [ ] Map Objects (loot) (Aug. 24)
- [ ] Refinements and Integration (Aug. 29)
Completion Deadline: Aug. 31
 
# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)

# **Members**
BenGhahramaniUQ (@BenGhahramaniUQ)
Howie (@Howard-12)
Praneet (@praneetdhoolia)
JonnaHerman (@JonnaHerman)
Chloe Catane (@chloemicah)

**Comment by praneetdhoolia** [comment]
Not implemented, possible task for sprint 2.

**Comment by praneetdhoolia** [comment]
Not implemented, possible task for sprint 2.
