### ISSUE TITLE
Abstract Item V2

### ISSUE THREAD

**Issue by tompreston1** [UQcsse3200/2024-studio-2#94]
# **Description**
**Task:** Implement new features to abstract item.
**Feature:** Inventory and Items (#3)

Abstract class will be updated so that inventory items can be rendered. Abstract item class will also have an item description which will show items abilities and stats. Item concrete sub-classes will also have to be modified so that the inherit the updated abstract item functionality. 

# **Milestones**
List of steps that need to be completed for this task.
- [x] get texture in abstract item (Aug. 22)
- [x] get description in abstract item (Aug. 22)
- [x] update concrete sub-classes (Aug. 23)
- [x] update all test and java docs (Aug. 24)
- [ ] Merge into main (27 Aug)
 
**Completion Deadline:** Aug. 28

# **Documentation**
- [Items Wiki Page](https://github.com/UQcsse3200/2024-studio-2/wiki/Items)
 
# **Member**
- Tom Preston (tompreston1) 
- Phonh Nguyen (PHONGNGUYEN1)
