### ISSUE TITLE
Inventory Management

### ISSUE THREAD

**Issue by s-shalomi** [UQcsse3200/2024-studio-2#95]
# **Description**
**Task:** Managing and sorting inventory (#3).
**Feature:** Inventory and Items (#2)

Update inventory class to enable categorising and sorting inventory by item name/code.

# **Dependencies**
- [x] AbstractItem (#18)
- [x] Concrete Item classes 
 
# **Milestones**
- [x] Update AbstractItem class with a category and description field and relevant accessor and mutator methods
- [x] Implement sorting functionality, based on item name, item code, quantity
- [ ] Implement a categorization functionality
- [ ] Implement search functionality, based on item name, item code, 
- [ ] Merge into main

**Completion Deadline:** Aug. 25
 
# **Documentation**
- [Inventory Wiki Page](https://github.com/UQcsse3200/2024-studio-2/wiki/Items)
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Senuri Panadura Arachchige (s-shalomi)
