### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by Slothlesss** [UQcsse3200/2024-studio-2#98]
# **Description**
**Task:** Loading Screen.
**Feature:** Indication of progress while assets are being loaded.

The loading screen provides visualization of the progress while assets are being loaded. The loading screen will include a progress bar that updates the asset loading status, so it will help to minimize the waiting feeling and improve gaming experience. 

# **Dependencies**
- [ ] UI design for progress bar background and filter need to be created.
- [ ] Tips for game need to be created. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement loading screen by adding constant value to the progress value (Aug. 23).
- [ ] Update the progress value based on resourceService().progress() of the next screen (Aug. 23).
 
# **Member**
- Minh (@Slothlesss) (Discord: Slothless)
